apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: peisschtappern
  namespace: helved
  labels:
    team: helved
spec:
  image: {{ image }}
  liveness:
    path: /probes/health
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /probes/health
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /probes/metric
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 512Mi
      cpu: 200m
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
  secureLogs:
    enabled: true
  leaderElection: true
  kafka:
    pool: nav-dev
    streams: true
  azure:
    application:
      enabled: true
      claims:
        extra:
          - NAVident
          - azp_name
  accessPolicy:
    inbound:
      rules:
        - application: helved-peisen
  gcp:
    sqlInstances:
      - type: "POSTGRES_15" # WARN: IF This is changed, all data will be lost. Read on nais.io how to upgrade
        diskAutoresize: true
        tier: "db-f1-micro"
        cascadingDelete: false
        highAvailability: false 
        pointInTimeRecovery: true
        maintenance:
          day: 7
          hour: 23
        databases:
          - name: peisschtappern
            envVarPrefix: DB
