apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: utsjekk-simulering
  namespace: helved
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "900"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "900"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "900"
  labels:
    team: helved
spec:
  image: {{image}}
  accessPolicy:
    inbound:
      rules:
        - application: utsjekk
    outbound:
      external:
        - host: helved-ws-proxy.dev-fss-pub.nais.io
      rules:
        - application: logging
          namespace: nais-system
        - application: helved-ws-proxy
          cluster: dev-fss
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 300Mi
      cpu: 20m
  replicas:
    min: 1
    max: 1
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "928636f4-fd0d-4149-978e-a6fb68bb19de"
  liveness:
    path: /actuator/live
  readiness:
    path: /actuator/ready
  prometheus:
    path: /actuator/metrics
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  envFrom:
    - secret: utsjekk-oppdrag-simulering
  env:
    - name: PROXY_HOST
      value: https://helved-ws-proxy.dev-fss-pub.nais.io
    - name: PROXY_SCOPE
      value: api://dev-fss.helved.ws-proxy/.default
    - name: SIMULERING_PATH
      value: cics/oppdrag/simulerFpServiceWSBinding
