apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: helved
  name: smokesignal
  namespace: helved
spec:
  schedule: "0 5 * * *"
  image: {{ image }} 
  ttlSecondsAfterFinished: 14400
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      memory: 1Gi
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
        - application: vedskiva
  env:
    - name: VEDSKIVA_SCOPE
      value: api://prod-gcp.helved.vedskiva/.default
