apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: urskog-alerts
  namespace: helved
  labels:
    team: helved
spec:
  groups:
    - name: app
      rules:
        - alert: unavailable
          expr: sum(kube_deployment_status_replicas_available{app="urskog", namespace="helved"} offset 5m) by (deployment, namespace) == 0
          for: 5m
          annotations:
            consequence: 'urskog er dau'
            action: '`kubectl describe pod -l app=urskog` -> `kubectl logs -l app=urskog`'
          labels:
            namespace: helved
            severity: critical

    - name: kafka
      rules:
        - alert: lag
          expr: sum(kafka_consumer_records_lag{app="urskog", namespace="helved"}) by(topic) > 5
          for: 10m
          annotations:
            summary: topic {{ labels.topic }} har uleste records.
            action:  mest sansynlig en feil så vi ikke får lest neste record.
            consequence: bottleneck
          labels:
            namespace: helved
            severity: warning

    # - name: kvittering
    #   rules:
    #     - alert: mangler kvittering
    #       expr: sum(helved_oppdrag_mq_total{status="Sendt"}) - sum(helved_kvitteringer_total) != 0 and (hour() >= 6 and hour() < 22) and (day_of_week() >= 1 and day_of_week() <= 5) and is_helligdag == 0
    #       for: 10m
    #       annotations:
    #         summary: mangler kvittering for oppdrag
    #         action: sjekk peisen
    #       labels:
    #         namespace: helved
    #         severity: warning

    - name: vulnerabilities
      rules:
        - alert: CriticalVulnerability
          expr: sum by (workload_name, workload_namespace) (nais_workload_vulnerabilities{severity="CRITICAL", workload_namespace="helved", workload_type!="platform", workload_cluster="prod"}) > 0
          for: 10m
          annotations:
            summary: "Kritisk sårbarhet (CVSS >= 9.0) i {{ $labels.workload_name }}"
            action: "NAIS Console: https://console.nav.cloud.nais.io/team/helved/prod-gcp/app/{{ $labels.workload_name }}/vulnerabilities"
          labels:
            namespace: helved
            severity: critical
            alert_type: custom
            slack_layout: helved-vulnerability

        - alert: HighVulnerability
          expr: sum by (workload_name, workload_namespace) (nais_workload_vulnerabilities{severity="HIGH", workload_namespace="helved", workload_type!="platform", workload_cluster="prod"}) > 0
          for: 10m
          annotations:
            summary: "Høy sårbarhet (CVSS 7.0-8.9) i {{ $labels.workload_name }}"
            action: "NAIS Console: https://console.nav.cloud.nais.io/team/helved/prod-gcp/app/{{ $labels.workload_name }}/vulnerabilities"
          labels:
            namespace: helved
            severity: high
            alert_type: custom
            slack_layout: helved-vulnerability