apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: urskog-alerts
  namespace: helved
  labels:
    team: helved
spec:
  groups:
    - name: urskog-alerts
      rules:
        - alert: kafka - lag
          expr: sum(kafka_consumer_records_lag{app="urskog", namespace="helved"}) by(topic) > 5
          for: 10m
          annotations:
            summary: topic {{ labels.topic }} har uleste records.
            action:  mest sansynlig en feil så vi ikke får lest neste record.
            consequence: flaskehals/propp 
          labels:
            namespace: helved
            severity: warning

