apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: urskog
  namespace: helved
  labels:
    team: helved
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
  image: {{ image }}
  accessPolicy:
    outbound:
      external:
        - host: helved-ws-proxy.dev-fss-pub.nais.io
        - host: mqls02.preprod.local
          ports:
            - port: 1413
      rules:
        - application: helved-ws-proxy
          cluster: dev-fss
  azure:
    application:
      enabled: true
  liveness:
    path: /actuator/live
  readiness:
    path: /actuator/ready
  prometheus:
    enabled: true
    path: /actuator/metric
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 512Mi
      cpu: 200m
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev
    streams: true
  envFrom:
     # TODO: sjekk hva disse inneholder, er det samme eller noe ulikt?
    - secret: utsjekk-oppdrag-simulering
    - secret: utsjekk-oppdrag
  env:
    - name: PROXY_HOST
      value: https://helved-ws-proxy.dev-fss-pub.nais.io
    - name: PROXY_SCOPE
      value: api://dev-fss.helved.ws-proxy/.default
    - name: SIMULERING_PATH
      value: cics/oppdrag/simulerFpServiceWSBinding
    - name: MQ_HOSTNAME
      value: mqls02.preprod.local
    - name: MQ_PORT
      value: "1413"
    - name: MQ_MANAGER
      value: MQLS02
    - name: MQ_CHANNEL
      value: Q1_DP_OPPDRAG
    - name: MQ_OPPDRAG_QUEUE
      value: QA.Q1_231.OB04_OPPDRAG_XML
    - name: MQ_OPPDRAG_KVITTERING_QUEUE
      value: QA.Q1_DP_OPPDRAG.OPPDRAG_DP_XML_KVITT
    - name: MQ_AVSTEMMING_QUEUE
      value: QA.Q1_234.OB29_AVSTEMMING_XML
