apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: abetal-alerts
  namespace: helved
  labels:
    team: helved
spec:
  groups:
    - name: app
      rules:
        - alert: unavailable
          expr: sum(kube_deployment_status_replicas_available{app="abetal", namespace="helved"} offset 5m) by (deployment, namespace) == 0
          for: 5m
          annotations:
            consequence: 'abetal er dau'
            action: '`kubectl describe pod -l app=abetal` -> `kubectl logs -l app=abetal`'
          labels:
            namespace: helved
            severity: critical
    - name: kafka
      rules:
        - alert: lag
          expr: sum(kafka_consumer_records_lag{app="abetal", namespace="helved"}) by(topic) > 5
          for: 10m
          annotations:
            summary: topic {{ labels.topic }} har uleste records.
            action:  mest sansynlig en feil så vi ikke får lest neste record.
            consequence: bottleneck
          labels:
            namespace: helved
            severity: warning
