apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: abetal
  namespace: helved
  labels:
    team: helved
spec:
  image: {{ image }}
  terminationGracePeriodSeconds: 60
  preStopHook:
    exec:
      # Execute sleep before SIGTERM is sent.
      # Give 10 sec for the pod to be removed from service endpoints,
      # ensuring no new traffic hits the app before it closes.
      # We need this to graceful shutdown kafka streams to solve race-condition in rocksdb
      command: ["/bin/sh", "-c", "sleep 10"]
  liveness:
    path: /actuator/live
    failureThreshold: 60
    initialDelay: 1
    periodSeconds: 1
  readiness:
    path: /actuator/ready
    failureThreshold: 60
    initialDelay: 1
    periodSeconds: 1
  prometheus:
    path: /actuator/metric
    enabled: true
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 4096Mi
    requests:
      memory: 4096Mi
      cpu: 1000m
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: utsjekk
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  kafka:
    pool: nav-dev
    streams: true
