apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: abetal
  namespace: helved
  labels:
    team: helved
spec:
  image: {{ image }}
  ingresses:
    - https://abetal.intern.dev.nav.no
  liveness:
    path: /actuator/live
  readiness:
    path: /actuator/ready
  prometheus:
    path: /actuator/metric
    enabled: true
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 512Mi
      cpu: 200m
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  kafka:
    pool: nav-dev
    streams: true
