apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: simulering-alerts
  namespace: helved
  labels:
    team: helved
spec:
  groups:
    - name: app
      rules:
        - alert: unavailable
          expr: sum(kube_deployment_status_replicas_available{app="simulering", namespace="helved"} offset 5m) by (deployment, namespace) == 0
          for: 5m
          annotations:
            consequence: 'simulering er dau'
            action: '`kubectl describe pod -l app=simulering` -> `kubectl logs -l app=simulering`'
          labels:
            namespace: helved
            severity: critical
