apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: peisschtappern
  namespace: helved
  labels:
    team: helved
spec:
  image: {{ image }}
  liveness:
    path: /actuator/live
  readiness:
    path: /actuator/ready
  prometheus:
    enabled: true
    path: /actuator/metric
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 512Mi
      cpu: 300m
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev
    streams: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: helved-peisen
        - application: vedskiva
  gcp:
    sqlInstances:
      - type: "POSTGRES_15" # WARN: IF This is changed, all data will be lost. Read on nais.io how to upgrade
        diskAutoresize: true
        tier: "db-f1-micro"
        cascadingDelete: false
        highAvailability: false 
        pointInTimeRecovery: true
        maintenance:
          day: 7
          hour: 23
        databases:
          - name: peisschtappern
            envVarPrefix: DB
