apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: utsjekk
  namespace: helved
  labels:
    team: helved
spec:
  terminationGracePeriodSeconds: 70
  image: {{ image }}
  ingresses:
    - https://utsjekk.intern.dev.nav.no
  liveness:
    path: /actuator/live
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /actuator/ready
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    path: /actuator/metric
    enabled: true
  replicas:
    min: 3
    max: 3
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 512Mi
      cpu: 200m
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  kafka:
    pool: nav-dev
    streams: true
  env:
    - name: SIMULERING_SCOPE
      value: api://dev-gcp.helved.utsjekk-simulering/.default
    - name: ENV
      value: dev
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: dec3ee50-b683-4644-9507-520e8f054ac2 # Alle brukere
        extra:
          - NAVident
          - azp_name
  accessPolicy:
    inbound:
      rules:
        - application: abetal
        - application: helved-peisen
        - application: snickerboa
        - application: tiltakspenger-saksbehandling-api
          namespace: tpts
        - application: tilleggsstonader-sak
          namespace: tilleggsstonader
          # generer obo token: https://azure-token-generator.intern.dev.nav.no/api/obo?aud=dev-gcp.helved.utsjekk
          #ref https://docs.nais.io/auth/entra-id/how-to/generate/?h=azure+token
        - application: azure-token-generator
          namespace: nais
          cluster: dev-gcp
        - application: utbetal
          namespace: aap
    outbound:
      rules:
        - application: logging
          namespace: nais-system
        - application: utsjekk-simulering
  gcp:
    sqlInstances:
      - type: "POSTGRES_15" # WARN: IF This is changed, all data will be lost. Read on nais.io how to upgrade
        diskAutoresize: true
        tier: "db-f1-micro"
        cascadingDelete: false
        highAvailability: false 
        pointInTimeRecovery: true
        maintenance:
          day: 7
          hour: 23
        databases:
          - name: utsjekk
            envVarPrefix: DB
