apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: utsjekk
  namespace: helved
  labels:
    team: helved
spec:
  image: {{ image }}
  ingresses:
      - https://utsjekk.intern.dev.nav.no
  liveness:
    path: /probes/health
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /probes/health
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /probes/metric
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi
      cpu: 100m
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  secureLogs:
    enabled: true
  leaderElection: true
  kafka:
    pool: nav-dev
  envFrom:
    - secret: utsjekk-unleash-api-token
  env:
    - name: OPPDRAG_SCOPE
      value: api://dev-gcp.helved.utsjekk-oppdrag/.default
    - name: SIMULERING_SCOPE
      value: api://dev-gcp.helved.utsjekk-simulering/.default
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "3e28466f-c53d-46da-8b44-a4abc2ad4593" # 0000-GA-Dagpenger-Saksbehandler
          - id: "11b8475a-fb12-41aa-b1f6-8497c1b5385b" # 0000-GA-Dagpenger-Beslutter
          - id: "1b3a2c4d-d620-4fcf-a29b-a6cdadf29680" # saksbehandler tiltakspenger
          - id: "79985315-b2de-40b8-a740-9510796993c6" # beslutter tiltakspenger
          - id: "31a99292-9461-40bf-b2d0-a815697dfbb4" # beslutter tilleggstønader
        extra:
          - NAVident
          - azp_name
  accessPolicy:
    inbound:
      rules:
        - application: helved-peisen
        - application: utsjekk
        - application: helved-performance
        - application: tiltakspenger-saksbehandling-api
          namespace: tpts
        - application: tilleggsstonader-sak
          namespace: tilleggsstonader
          # generer obo token: https://azure-token-generator.intern.dev.nav.no/api/obo?aud=dev-gcp.helved.utsjekk
          #ref https://docs.nais.io/auth/entra-id/how-to/generate/?h=azure+token
        - application: azure-token-generator
          namespace: aura
          cluster: dev-gcp
    outbound:
      rules:
        - application: utsjekk-oppdrag
        - application: utsjekk-simulering
      external:
        - host: helved-unleash-api.nav.cloud.nais.io
  gcp:
    sqlInstances:
      - type: "POSTGRES_15" # WARN: IF This is changed, all data will be lost. Read on nais.io how to upgrade
        diskAutoresize: true
        tier: "db-f1-micro"
        cascadingDelete: false
        highAvailability: false 
        pointInTimeRecovery: true
        maintenance:
          day: 7
          hour: 23
        databases:
          - name: utsjekk
            envVarPrefix: DB
