apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: utsjekk
  namespace: helved
  labels:
    team: helved
spec:
  terminationGracePeriodSeconds: 70
  image: {{ image }}
  liveness:
    path: /actuator/health
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /actuator/health
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /actuator/metric
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 512Mi
      cpu: 200m
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  kafka:
    pool: nav-prod
    streams: true
  env:
    - name: OPPDRAG_SCOPE
      value: api://prod-gcp.helved.utsjekk-oppdrag/.default
    - name: SIMULERING_SCOPE
      value: api://prod-gcp.helved.utsjekk-simulering/.default
    - name: ENV
      value: prod
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "2e9c63d8-322e-4c1f-b500-a0abb812761c" # 0000-GA-Dagpenger-Saksbehandler
          - id: "70d54cad-53a3-4788-bbe3-565096f01da7" # 0000-GA-Dagpenger-Beslutter
          - id: "6c6ce2e8-b2e2-4c4b-8194-215c8e27a5c7" # saksbehandler tiltakspenger
          - id: "de518927-f657-4f37-9a64-14fdfd968dd2" # beslutter tiltakspenger
          - id: "c1e9edec-0c10-4df2-8c74-324ab9922220" # saksbehandler tilleggsstønader
        extra:
          - NAVident
          - azp_name
  accessPolicy:
    inbound:
      rules:
        - application: helved-peisen
        - application: tiltakspenger-saksbehandling-api
          namespace: tpts
        - application: tilleggsstonader-sak
          namespace: tilleggsstonader
        - application: utbetal
          namespace: aap
    outbound:
      rules:
        - application: logging
          namespace: nais-system
        - application: utsjekk-oppdrag
        - application: utsjekk-simulering
  gcp:
    sqlInstances:
      - type: "POSTGRES_15" #WARN: IF This is changed, all data will be lost. Read on nais.io how to upgrade
        diskAutoresize: true
        tier: "db-custom-1-3840"
        cascadingDelete: false
        highAvailability: true
        pointInTimeRecovery: true
        maintenance:
          day: 7
          hour: 23
        databases:
          - name: utsjekk
            envVarPrefix: DB
        flags:
          - name: "cloudsql.enable_pgaudit"
            value: "on"
          - name: "pgaudit.log"
            value: "write,ddl"
