@startuml
!theme black-knight
queue "helved.utbetalinger.v1" <<topic>> as helved_utbetalinger_v1
queue "ktable-helved.pending-utbetalinger.v1-repartition" <<topic>> as ktable_helved_pending_utbetalinger_v1_repartition
queue "helved.pending-utbetalinger.v1" <<topic>> as helved_pending_utbetalinger_v1
queue "pk-leftjoin-pending-repartition" <<topic>> as pk_leftjoin_pending_repartition
queue "ktable-helved.saker.v1-repartition" <<topic>> as ktable_helved_saker_v1_repartition
queue "helved.saker.v1" <<topic>> as helved_saker_v1
queue "helved.status.v1" <<topic>> as helved_status_v1
queue "helved.simuleringer.v1" <<topic>> as helved_simuleringer_v1
queue "helved.oppdrag.v1" <<topic>> as helved_oppdrag_v1
queue "helved.fk.v1" <<topic>> as helved_fk_v1
queue "dptuple-leftjoin-saker-repartition" <<topic>> as dptuple_leftjoin_saker_repartition
queue "aaptuple-leftjoin-saker-repartition" <<topic>> as aaptuple_leftjoin_saker_repartition
queue "historisktuple-leftjoin-saker-repartition" <<topic>> as historisktuple_leftjoin_saker_repartition
queue "tptuple-leftjoin-saker-repartition" <<topic>> as tptuple_leftjoin_saker_repartition
queue "tstuple-leftjoin-saker-repartition" <<topic>> as tstuple_leftjoin_saker_repartition
queue "ktable-helved.fk.v1-repartition" <<topic>> as ktable_helved_fk_v1_repartition
queue "oppdrag-leftjoin-fks-repartition" <<topic>> as oppdrag_leftjoin_fks_repartition
queue "from-teamdagpenger.utbetaling.v1-repartition" <<topic>> as from_teamdagpenger_utbetaling_v1_repartition
queue "teamdagpenger.utbetaling.v1" <<topic>> as teamdagpenger_utbetaling_v1
queue "helved.utbetalinger-dp.v1" <<topic>> as helved_utbetalinger_dp_v1
queue "from-aap.utbetaling.v1-repartition" <<topic>> as from_aap_utbetaling_v1_repartition
queue "aap.utbetaling.v1" <<topic>> as aap_utbetaling_v1
queue "helved.utbetalinger-aap.v1" <<topic>> as helved_utbetalinger_aap_v1
queue "from-tilleggsstonader.utbetaling.v1-repartition" <<topic>> as from_tilleggsstonader_utbetaling_v1_repartition
queue "tilleggsstonader.utbetaling.v1" <<topic>> as tilleggsstonader_utbetaling_v1
queue "helved.utbetalinger-ts.v1" <<topic>> as helved_utbetalinger_ts_v1
queue "helved.utbetalinger-tp.v1" <<topic>> as helved_utbetalinger_tp_v1
queue "from-historisk.utbetaling.v1-repartition" <<topic>> as from_historisk_utbetaling_v1_repartition
queue "historisk.utbetaling.v1" <<topic>> as historisk_utbetaling_v1
queue "helved.utbetalinger-historisk.v1" <<topic>> as helved_utbetalinger_historisk_v1
package "Sub-topology: 0" {
	database "helved.utbetalinger.v1-state-store-v4" <<State Store>> as helved_utbetalinger_v1_state_store_v4
	helved_utbetalinger_v1 --> KSTREAM_SOURCE_0000000000
	helved_utbetalinger_v1_state_store_v4 -- KTABLE_SOURCE_0000000001
}
package "Sub-topology: 1" {
	agent "consume-helved.pending-utbetalinger.v1" <<Source>> as consume_helved_pending_utbetalinger_v1
	agent "KSTREAM-PROCESSOR-0000000003" <<Processor>> as KSTREAM_PROCESSOR_0000000003
	agent "KSTREAM-PROCESSOR-0000000004" <<Processor>> as KSTREAM_PROCESSOR_0000000004
	agent "ktable-helved.pending-utbetalinger.v1-repartition-filter" <<Processor>> as ktable_helved_pending_utbetalinger_v1_repartition_filter
	agent "ktable-helved.pending-utbetalinger.v1-repartition-sink" <<Sink>> as ktable_helved_pending_utbetalinger_v1_repartition_sink
	helved_pending_utbetalinger_v1 --> consume_helved_pending_utbetalinger_v1
	ktable_helved_pending_utbetalinger_v1_repartition <-- ktable_helved_pending_utbetalinger_v1_repartition_sink
	consume_helved_pending_utbetalinger_v1 --> KSTREAM_PROCESSOR_0000000003
	KSTREAM_PROCESSOR_0000000003 --> KSTREAM_PROCESSOR_0000000004
	KSTREAM_PROCESSOR_0000000004 --> ktable_helved_pending_utbetalinger_v1_repartition_filter
	ktable_helved_pending_utbetalinger_v1_repartition_filter --> ktable_helved_pending_utbetalinger_v1_repartition_sink
}
package "Sub-topology: 2" {
	database "helved.pending-utbetalinger.v1-state-store-v4" <<State Store>> as helved_pending_utbetalinger_v1_state_store_v4
	agent "pk-leftjoin-pending-repartition-source" <<Source>> as pk_leftjoin_pending_repartition_source
	agent "pk-leftjoin-pending" <<Processor>> as pk_leftjoin_pending
	agent "KSTREAM-MAPVALUES-0000000273" <<Processor>> as KSTREAM_MAPVALUES_0000000273
	agent "KSTREAM-FILTER-0000000274" <<Processor>> as KSTREAM_FILTER_0000000274
	agent "KSTREAM-PROCESSOR-0000000275" <<Processor>> as KSTREAM_PROCESSOR_0000000275
	agent "ktable-helved.pending-utbetalinger.v1-repartition-source" <<Source>> as ktable_helved_pending_utbetalinger_v1_repartition_source
	agent "KSTREAM-SINK-0000000276" <<Sink>> as KSTREAM_SINK_0000000276
	agent "ktable-helved.pending-utbetalinger.v1" <<Processor>> as ktable_helved_pending_utbetalinger_v1
	pk_leftjoin_pending_repartition --> pk_leftjoin_pending_repartition_source
	helved_pending_utbetalinger_v1_state_store_v4 -- pk_leftjoin_pending
	ktable_helved_pending_utbetalinger_v1_repartition --> ktable_helved_pending_utbetalinger_v1_repartition_source
	helved_utbetalinger_v1 <-- KSTREAM_SINK_0000000276
	helved_pending_utbetalinger_v1_state_store_v4 -- ktable_helved_pending_utbetalinger_v1
	pk_leftjoin_pending_repartition_source --> pk_leftjoin_pending
	pk_leftjoin_pending --> KSTREAM_MAPVALUES_0000000273
	KSTREAM_MAPVALUES_0000000273 --> KSTREAM_FILTER_0000000274
	KSTREAM_FILTER_0000000274 --> KSTREAM_PROCESSOR_0000000275
	KSTREAM_PROCESSOR_0000000275 --> KSTREAM_SINK_0000000276
	ktable_helved_pending_utbetalinger_v1_repartition_source --> ktable_helved_pending_utbetalinger_v1
}
package "Sub-topology: 3" {
	agent "consume-helved.saker.v1" <<Source>> as consume_helved_saker_v1
	agent "KSTREAM-PROCESSOR-0000000010" <<Processor>> as KSTREAM_PROCESSOR_0000000010
	agent "KSTREAM-PROCESSOR-0000000011" <<Processor>> as KSTREAM_PROCESSOR_0000000011
	agent "ktable-helved.saker.v1-repartition-filter" <<Processor>> as ktable_helved_saker_v1_repartition_filter
	agent "ktable-helved.saker.v1-repartition-sink" <<Sink>> as ktable_helved_saker_v1_repartition_sink
	helved_saker_v1 --> consume_helved_saker_v1
	ktable_helved_saker_v1_repartition <-- ktable_helved_saker_v1_repartition_sink
	consume_helved_saker_v1 --> KSTREAM_PROCESSOR_0000000010
	KSTREAM_PROCESSOR_0000000010 --> KSTREAM_PROCESSOR_0000000011
	KSTREAM_PROCESSOR_0000000011 --> ktable_helved_saker_v1_repartition_filter
	ktable_helved_saker_v1_repartition_filter --> ktable_helved_saker_v1_repartition_sink
}
package "Sub-topology: 4" {
	database "helved.saker.v1-state-store" <<State Store>> as helved_saker_v1_state_store
	agent "dptuple-leftjoin-saker-repartition-source" <<Source>> as dptuple_leftjoin_saker_repartition_source
	agent "dptuple-leftjoin-saker" <<Processor>> as dptuple_leftjoin_saker
	agent "KSTREAM-PEEK-0000000039" <<Processor>> as KSTREAM_PEEK_0000000039
	agent "KSTREAM-PROCESSOR-0000000040" <<Processor>> as KSTREAM_PROCESSOR_0000000040
	agent "KSTREAM-BRANCH-0000000041" <<Processor>> as KSTREAM_BRANCH_0000000041
	agent "aaptuple-leftjoin-saker-repartition-source" <<Source>> as aaptuple_leftjoin_saker_repartition_source
	agent "historisktuple-leftjoin-saker-repartition-source" <<Source>> as historisktuple_leftjoin_saker_repartition_source
	agent "tptuple-leftjoin-saker-repartition-source" <<Source>> as tptuple_leftjoin_saker_repartition_source
	agent "tstuple-leftjoin-saker-repartition-source" <<Source>> as tstuple_leftjoin_saker_repartition_source
	agent "aaptuple-leftjoin-saker" <<Processor>> as aaptuple_leftjoin_saker
	agent "historisktuple-leftjoin-saker" <<Processor>> as historisktuple_leftjoin_saker
	agent "tptuple-leftjoin-saker" <<Processor>> as tptuple_leftjoin_saker
	agent "tstuple-leftjoin-saker" <<Processor>> as tstuple_leftjoin_saker
	agent "KSTREAM-PEEK-0000000093" <<Processor>> as KSTREAM_PEEK_0000000093
	agent "KSTREAM-PEEK-0000000140" <<Processor>> as KSTREAM_PEEK_0000000140
	agent "KSTREAM-PEEK-0000000180" <<Processor>> as KSTREAM_PEEK_0000000180
	agent "KSTREAM-PEEK-0000000227" <<Processor>> as KSTREAM_PEEK_0000000227
	agent "KSTREAM-BRANCH-00000000410" <<Processor>> as KSTREAM_BRANCH_00000000410
	agent "KSTREAM-PROCESSOR-0000000094" <<Processor>> as KSTREAM_PROCESSOR_0000000094
	agent "KSTREAM-PROCESSOR-0000000141" <<Processor>> as KSTREAM_PROCESSOR_0000000141
	agent "KSTREAM-PROCESSOR-0000000181" <<Processor>> as KSTREAM_PROCESSOR_0000000181
	agent "KSTREAM-PROCESSOR-0000000228" <<Processor>> as KSTREAM_PROCESSOR_0000000228
	agent "KSTREAM-MAPVALUES-0000000048" <<Processor>> as KSTREAM_MAPVALUES_0000000048
	agent "KSTREAM-MAPVALUES-0000000095" <<Processor>> as KSTREAM_MAPVALUES_0000000095
	agent "KSTREAM-MAPVALUES-0000000142" <<Processor>> as KSTREAM_MAPVALUES_0000000142
	agent "KSTREAM-MAPVALUES-0000000182" <<Processor>> as KSTREAM_MAPVALUES_0000000182
	agent "KSTREAM-MAPVALUES-0000000229" <<Processor>> as KSTREAM_MAPVALUES_0000000229
	agent "KSTREAM-KEY-SELECT-0000000049" <<Processor>> as KSTREAM_KEY_SELECT_0000000049
	agent "KSTREAM-KEY-SELECT-0000000096" <<Processor>> as KSTREAM_KEY_SELECT_0000000096
	agent "KSTREAM-KEY-SELECT-0000000143" <<Processor>> as KSTREAM_KEY_SELECT_0000000143
	agent "KSTREAM-KEY-SELECT-0000000183" <<Processor>> as KSTREAM_KEY_SELECT_0000000183
	agent "KSTREAM-KEY-SELECT-0000000230" <<Processor>> as KSTREAM_KEY_SELECT_0000000230
	agent "KSTREAM-MAPVALUES-0000000050" <<Processor>> as KSTREAM_MAPVALUES_0000000050
	agent "KSTREAM-MAPVALUES-0000000097" <<Processor>> as KSTREAM_MAPVALUES_0000000097
	agent "KSTREAM-MAPVALUES-0000000144" <<Processor>> as KSTREAM_MAPVALUES_0000000144
	agent "KSTREAM-MAPVALUES-0000000184" <<Processor>> as KSTREAM_MAPVALUES_0000000184
	agent "KSTREAM-MAPVALUES-0000000231" <<Processor>> as KSTREAM_MAPVALUES_0000000231
	agent "KSTREAM-BRANCH-0000000051" <<Processor>> as KSTREAM_BRANCH_0000000051
	agent "KSTREAM-BRANCH-0000000098" <<Processor>> as KSTREAM_BRANCH_0000000098
	agent "KSTREAM-BRANCH-0000000145" <<Processor>> as KSTREAM_BRANCH_0000000145
	agent "KSTREAM-BRANCH-0000000185" <<Processor>> as KSTREAM_BRANCH_0000000185
	agent "KSTREAM-BRANCH-0000000232" <<Processor>> as KSTREAM_BRANCH_0000000232
	agent "KSTREAM-BRANCH-00000000510" <<Processor>> as KSTREAM_BRANCH_00000000510
	agent "KSTREAM-BRANCH-00000000980" <<Processor>> as KSTREAM_BRANCH_00000000980
	agent "KSTREAM-BRANCH-00000001450" <<Processor>> as KSTREAM_BRANCH_00000001450
	agent "KSTREAM-BRANCH-00000001850" <<Processor>> as KSTREAM_BRANCH_00000001850
	agent "KSTREAM-BRANCH-00000002320" <<Processor>> as KSTREAM_BRANCH_00000002320
	agent "KSTREAM-MAPVALUES-0000000057" <<Processor>> as KSTREAM_MAPVALUES_0000000057
	agent "KSTREAM-MAPVALUES-0000000104" <<Processor>> as KSTREAM_MAPVALUES_0000000104
	agent "KSTREAM-MAPVALUES-0000000151" <<Processor>> as KSTREAM_MAPVALUES_0000000151
	agent "KSTREAM-MAPVALUES-0000000191" <<Processor>> as KSTREAM_MAPVALUES_0000000191
	agent "KSTREAM-MAPVALUES-0000000238" <<Processor>> as KSTREAM_MAPVALUES_0000000238
	agent "KSTREAM-FLATMAPVALUES-0000000064" <<Processor>> as KSTREAM_FLATMAPVALUES_0000000064
	agent "KSTREAM-FLATMAPVALUES-0000000111" <<Processor>> as KSTREAM_FLATMAPVALUES_0000000111
	agent "KSTREAM-FLATMAPVALUES-0000000158" <<Processor>> as KSTREAM_FLATMAPVALUES_0000000158
	agent "KSTREAM-FLATMAPVALUES-0000000198" <<Processor>> as KSTREAM_FLATMAPVALUES_0000000198
	agent "KSTREAM-FLATMAPVALUES-0000000245" <<Processor>> as KSTREAM_FLATMAPVALUES_0000000245
	agent "KSTREAM-BRANCH-00000000411" <<Processor>> as KSTREAM_BRANCH_00000000411
	agent "KSTREAM-BRANCH-00000000511" <<Processor>> as KSTREAM_BRANCH_00000000511
	agent "KSTREAM-BRANCH-00000000981" <<Processor>> as KSTREAM_BRANCH_00000000981
	agent "KSTREAM-BRANCH-00000001451" <<Processor>> as KSTREAM_BRANCH_00000001451
	agent "KSTREAM-BRANCH-00000001851" <<Processor>> as KSTREAM_BRANCH_00000001851
	agent "KSTREAM-BRANCH-00000002321" <<Processor>> as KSTREAM_BRANCH_00000002321
	agent "KSTREAM-FILTER-0000000070" <<Processor>> as KSTREAM_FILTER_0000000070
	agent "KSTREAM-FILTER-0000000117" <<Processor>> as KSTREAM_FILTER_0000000117
	agent "KSTREAM-FILTER-0000000164" <<Processor>> as KSTREAM_FILTER_0000000164
	agent "KSTREAM-FILTER-0000000204" <<Processor>> as KSTREAM_FILTER_0000000204
	agent "KSTREAM-FILTER-0000000251" <<Processor>> as KSTREAM_FILTER_0000000251
	agent "KSTREAM-KEY-SELECT-0000000043" <<Processor>> as KSTREAM_KEY_SELECT_0000000043
	agent "KSTREAM-FLATMAP-0000000058" <<Processor>> as KSTREAM_FLATMAP_0000000058
	agent "KSTREAM-FLATMAP-0000000074" <<Processor>> as KSTREAM_FLATMAP_0000000074
	agent "KSTREAM-FLATMAP-0000000105" <<Processor>> as KSTREAM_FLATMAP_0000000105
	agent "KSTREAM-FLATMAP-0000000121" <<Processor>> as KSTREAM_FLATMAP_0000000121
	agent "KSTREAM-FLATMAP-0000000152" <<Processor>> as KSTREAM_FLATMAP_0000000152
	agent "KSTREAM-FLATMAP-0000000168" <<Processor>> as KSTREAM_FLATMAP_0000000168
	agent "KSTREAM-FLATMAP-0000000192" <<Processor>> as KSTREAM_FLATMAP_0000000192
	agent "KSTREAM-FLATMAP-0000000208" <<Processor>> as KSTREAM_FLATMAP_0000000208
	agent "KSTREAM-FLATMAP-0000000239" <<Processor>> as KSTREAM_FLATMAP_0000000239
	agent "KSTREAM-FLATMAP-0000000255" <<Processor>> as KSTREAM_FLATMAP_0000000255
	agent "KSTREAM-FLATMAPVALUES-0000000061" <<Processor>> as KSTREAM_FLATMAPVALUES_0000000061
	agent "KSTREAM-FLATMAPVALUES-0000000108" <<Processor>> as KSTREAM_FLATMAPVALUES_0000000108
	agent "KSTREAM-FLATMAPVALUES-0000000155" <<Processor>> as KSTREAM_FLATMAPVALUES_0000000155
	agent "KSTREAM-FLATMAPVALUES-0000000195" <<Processor>> as KSTREAM_FLATMAPVALUES_0000000195
	agent "KSTREAM-FLATMAPVALUES-0000000242" <<Processor>> as KSTREAM_FLATMAPVALUES_0000000242
	agent "KSTREAM-MAPVALUES-0000000044" <<Processor>> as KSTREAM_MAPVALUES_0000000044
	agent "KSTREAM-MAPVALUES-0000000053" <<Processor>> as KSTREAM_MAPVALUES_0000000053
	agent "KSTREAM-MAPVALUES-0000000067" <<Processor>> as KSTREAM_MAPVALUES_0000000067
	agent "KSTREAM-MAPVALUES-0000000071" <<Processor>> as KSTREAM_MAPVALUES_0000000071
	agent "KSTREAM-MAPVALUES-0000000100" <<Processor>> as KSTREAM_MAPVALUES_0000000100
	agent "KSTREAM-MAPVALUES-0000000114" <<Processor>> as KSTREAM_MAPVALUES_0000000114
	agent "KSTREAM-MAPVALUES-0000000118" <<Processor>> as KSTREAM_MAPVALUES_0000000118
	agent "KSTREAM-MAPVALUES-0000000147" <<Processor>> as KSTREAM_MAPVALUES_0000000147
	agent "KSTREAM-MAPVALUES-0000000161" <<Processor>> as KSTREAM_MAPVALUES_0000000161
	agent "KSTREAM-MAPVALUES-0000000165" <<Processor>> as KSTREAM_MAPVALUES_0000000165
	agent "KSTREAM-MAPVALUES-0000000187" <<Processor>> as KSTREAM_MAPVALUES_0000000187
	agent "KSTREAM-MAPVALUES-0000000201" <<Processor>> as KSTREAM_MAPVALUES_0000000201
	agent "KSTREAM-MAPVALUES-0000000205" <<Processor>> as KSTREAM_MAPVALUES_0000000205
	agent "KSTREAM-MAPVALUES-0000000234" <<Processor>> as KSTREAM_MAPVALUES_0000000234
	agent "KSTREAM-MAPVALUES-0000000248" <<Processor>> as KSTREAM_MAPVALUES_0000000248
	agent "KSTREAM-MAPVALUES-0000000252" <<Processor>> as KSTREAM_MAPVALUES_0000000252
	agent "KSTREAM-PROCESSOR-0000000045" <<Processor>> as KSTREAM_PROCESSOR_0000000045
	agent "KSTREAM-PROCESSOR-0000000054" <<Processor>> as KSTREAM_PROCESSOR_0000000054
	agent "KSTREAM-PROCESSOR-0000000059" <<Processor>> as KSTREAM_PROCESSOR_0000000059
	agent "KSTREAM-PROCESSOR-0000000062" <<Processor>> as KSTREAM_PROCESSOR_0000000062
	agent "KSTREAM-PROCESSOR-0000000065" <<Processor>> as KSTREAM_PROCESSOR_0000000065
	agent "KSTREAM-PROCESSOR-0000000068" <<Processor>> as KSTREAM_PROCESSOR_0000000068
	agent "KSTREAM-PROCESSOR-0000000072" <<Processor>> as KSTREAM_PROCESSOR_0000000072
	agent "KSTREAM-PROCESSOR-0000000075" <<Processor>> as KSTREAM_PROCESSOR_0000000075
	agent "KSTREAM-PROCESSOR-0000000101" <<Processor>> as KSTREAM_PROCESSOR_0000000101
	agent "KSTREAM-PROCESSOR-0000000106" <<Processor>> as KSTREAM_PROCESSOR_0000000106
	agent "KSTREAM-PROCESSOR-0000000109" <<Processor>> as KSTREAM_PROCESSOR_0000000109
	agent "KSTREAM-PROCESSOR-0000000112" <<Processor>> as KSTREAM_PROCESSOR_0000000112
	agent "KSTREAM-PROCESSOR-0000000115" <<Processor>> as KSTREAM_PROCESSOR_0000000115
	agent "KSTREAM-PROCESSOR-0000000119" <<Processor>> as KSTREAM_PROCESSOR_0000000119
	agent "KSTREAM-PROCESSOR-0000000122" <<Processor>> as KSTREAM_PROCESSOR_0000000122
	agent "KSTREAM-PROCESSOR-0000000148" <<Processor>> as KSTREAM_PROCESSOR_0000000148
	agent "KSTREAM-PROCESSOR-0000000153" <<Processor>> as KSTREAM_PROCESSOR_0000000153
	agent "KSTREAM-PROCESSOR-0000000156" <<Processor>> as KSTREAM_PROCESSOR_0000000156
	agent "KSTREAM-PROCESSOR-0000000159" <<Processor>> as KSTREAM_PROCESSOR_0000000159
	agent "KSTREAM-PROCESSOR-0000000162" <<Processor>> as KSTREAM_PROCESSOR_0000000162
	agent "KSTREAM-PROCESSOR-0000000166" <<Processor>> as KSTREAM_PROCESSOR_0000000166
	agent "KSTREAM-PROCESSOR-0000000169" <<Processor>> as KSTREAM_PROCESSOR_0000000169
	agent "KSTREAM-PROCESSOR-0000000188" <<Processor>> as KSTREAM_PROCESSOR_0000000188
	agent "KSTREAM-PROCESSOR-0000000193" <<Processor>> as KSTREAM_PROCESSOR_0000000193
	agent "KSTREAM-PROCESSOR-0000000196" <<Processor>> as KSTREAM_PROCESSOR_0000000196
	agent "KSTREAM-PROCESSOR-0000000199" <<Processor>> as KSTREAM_PROCESSOR_0000000199
	agent "KSTREAM-PROCESSOR-0000000202" <<Processor>> as KSTREAM_PROCESSOR_0000000202
	agent "KSTREAM-PROCESSOR-0000000206" <<Processor>> as KSTREAM_PROCESSOR_0000000206
	agent "KSTREAM-PROCESSOR-0000000209" <<Processor>> as KSTREAM_PROCESSOR_0000000209
	agent "KSTREAM-PROCESSOR-0000000235" <<Processor>> as KSTREAM_PROCESSOR_0000000235
	agent "KSTREAM-PROCESSOR-0000000240" <<Processor>> as KSTREAM_PROCESSOR_0000000240
	agent "KSTREAM-PROCESSOR-0000000243" <<Processor>> as KSTREAM_PROCESSOR_0000000243
	agent "KSTREAM-PROCESSOR-0000000246" <<Processor>> as KSTREAM_PROCESSOR_0000000246
	agent "KSTREAM-PROCESSOR-0000000249" <<Processor>> as KSTREAM_PROCESSOR_0000000249
	agent "KSTREAM-PROCESSOR-0000000253" <<Processor>> as KSTREAM_PROCESSOR_0000000253
	agent "KSTREAM-PROCESSOR-0000000256" <<Processor>> as KSTREAM_PROCESSOR_0000000256
	agent "ktable-helved.saker.v1-repartition-source" <<Source>> as ktable_helved_saker_v1_repartition_source
	agent "KSTREAM-SINK-0000000046" <<Sink>> as KSTREAM_SINK_0000000046
	agent "KSTREAM-SINK-0000000055" <<Sink>> as KSTREAM_SINK_0000000055
	agent "KSTREAM-SINK-0000000060" <<Sink>> as KSTREAM_SINK_0000000060
	agent "KSTREAM-SINK-0000000063" <<Sink>> as KSTREAM_SINK_0000000063
	agent "KSTREAM-SINK-0000000066" <<Sink>> as KSTREAM_SINK_0000000066
	agent "KSTREAM-SINK-0000000069" <<Sink>> as KSTREAM_SINK_0000000069
	agent "KSTREAM-SINK-0000000073" <<Sink>> as KSTREAM_SINK_0000000073
	agent "KSTREAM-SINK-0000000076" <<Sink>> as KSTREAM_SINK_0000000076
	agent "KSTREAM-SINK-0000000102" <<Sink>> as KSTREAM_SINK_0000000102
	agent "KSTREAM-SINK-0000000107" <<Sink>> as KSTREAM_SINK_0000000107
	agent "KSTREAM-SINK-0000000110" <<Sink>> as KSTREAM_SINK_0000000110
	agent "KSTREAM-SINK-0000000113" <<Sink>> as KSTREAM_SINK_0000000113
	agent "KSTREAM-SINK-0000000116" <<Sink>> as KSTREAM_SINK_0000000116
	agent "KSTREAM-SINK-0000000120" <<Sink>> as KSTREAM_SINK_0000000120
	agent "KSTREAM-SINK-0000000123" <<Sink>> as KSTREAM_SINK_0000000123
	agent "KSTREAM-SINK-0000000149" <<Sink>> as KSTREAM_SINK_0000000149
	agent "KSTREAM-SINK-0000000154" <<Sink>> as KSTREAM_SINK_0000000154
	agent "KSTREAM-SINK-0000000157" <<Sink>> as KSTREAM_SINK_0000000157
	agent "KSTREAM-SINK-0000000160" <<Sink>> as KSTREAM_SINK_0000000160
	agent "KSTREAM-SINK-0000000163" <<Sink>> as KSTREAM_SINK_0000000163
	agent "KSTREAM-SINK-0000000167" <<Sink>> as KSTREAM_SINK_0000000167
	agent "KSTREAM-SINK-0000000170" <<Sink>> as KSTREAM_SINK_0000000170
	agent "KSTREAM-SINK-0000000189" <<Sink>> as KSTREAM_SINK_0000000189
	agent "KSTREAM-SINK-0000000194" <<Sink>> as KSTREAM_SINK_0000000194
	agent "KSTREAM-SINK-0000000197" <<Sink>> as KSTREAM_SINK_0000000197
	agent "KSTREAM-SINK-0000000200" <<Sink>> as KSTREAM_SINK_0000000200
	agent "KSTREAM-SINK-0000000203" <<Sink>> as KSTREAM_SINK_0000000203
	agent "KSTREAM-SINK-0000000207" <<Sink>> as KSTREAM_SINK_0000000207
	agent "KSTREAM-SINK-0000000210" <<Sink>> as KSTREAM_SINK_0000000210
	agent "KSTREAM-SINK-0000000236" <<Sink>> as KSTREAM_SINK_0000000236
	agent "KSTREAM-SINK-0000000241" <<Sink>> as KSTREAM_SINK_0000000241
	agent "KSTREAM-SINK-0000000244" <<Sink>> as KSTREAM_SINK_0000000244
	agent "KSTREAM-SINK-0000000247" <<Sink>> as KSTREAM_SINK_0000000247
	agent "KSTREAM-SINK-0000000250" <<Sink>> as KSTREAM_SINK_0000000250
	agent "KSTREAM-SINK-0000000254" <<Sink>> as KSTREAM_SINK_0000000254
	agent "KSTREAM-SINK-0000000257" <<Sink>> as KSTREAM_SINK_0000000257
	agent "ktable-helved.saker.v1" <<Processor>> as ktable_helved_saker_v1
	dptuple_leftjoin_saker_repartition --> dptuple_leftjoin_saker_repartition_source
	helved_saker_v1_state_store -- dptuple_leftjoin_saker
	aaptuple_leftjoin_saker_repartition --> aaptuple_leftjoin_saker_repartition_source
	historisktuple_leftjoin_saker_repartition --> historisktuple_leftjoin_saker_repartition_source
	tptuple_leftjoin_saker_repartition --> tptuple_leftjoin_saker_repartition_source
	tstuple_leftjoin_saker_repartition --> tstuple_leftjoin_saker_repartition_source
	helved_saker_v1_state_store -- aaptuple_leftjoin_saker
	helved_saker_v1_state_store -- historisktuple_leftjoin_saker
	helved_saker_v1_state_store -- tptuple_leftjoin_saker
	helved_saker_v1_state_store -- tstuple_leftjoin_saker
	ktable_helved_saker_v1_repartition --> ktable_helved_saker_v1_repartition_source
	helved_status_v1 <-- KSTREAM_SINK_0000000046
	helved_status_v1 <-- KSTREAM_SINK_0000000055
	helved_pending_utbetalinger_v1 <-- KSTREAM_SINK_0000000060
	helved_simuleringer_v1 <-- KSTREAM_SINK_0000000063
	helved_oppdrag_v1 <-- KSTREAM_SINK_0000000066
	helved_status_v1 <-- KSTREAM_SINK_0000000069
	helved_status_v1 <-- KSTREAM_SINK_0000000073
	helved_fk_v1 <-- KSTREAM_SINK_0000000076
	helved_status_v1 <-- KSTREAM_SINK_0000000102
	helved_pending_utbetalinger_v1 <-- KSTREAM_SINK_0000000107
	helved_simuleringer_v1 <-- KSTREAM_SINK_0000000110
	helved_oppdrag_v1 <-- KSTREAM_SINK_0000000113
	helved_status_v1 <-- KSTREAM_SINK_0000000116
	helved_status_v1 <-- KSTREAM_SINK_0000000120
	helved_fk_v1 <-- KSTREAM_SINK_0000000123
	helved_status_v1 <-- KSTREAM_SINK_0000000149
	helved_pending_utbetalinger_v1 <-- KSTREAM_SINK_0000000154
	helved_simuleringer_v1 <-- KSTREAM_SINK_0000000157
	helved_oppdrag_v1 <-- KSTREAM_SINK_0000000160
	helved_status_v1 <-- KSTREAM_SINK_0000000163
	helved_status_v1 <-- KSTREAM_SINK_0000000167
	helved_fk_v1 <-- KSTREAM_SINK_0000000170
	helved_status_v1 <-- KSTREAM_SINK_0000000189
	helved_pending_utbetalinger_v1 <-- KSTREAM_SINK_0000000194
	helved_simuleringer_v1 <-- KSTREAM_SINK_0000000197
	helved_oppdrag_v1 <-- KSTREAM_SINK_0000000200
	helved_status_v1 <-- KSTREAM_SINK_0000000203
	helved_status_v1 <-- KSTREAM_SINK_0000000207
	helved_fk_v1 <-- KSTREAM_SINK_0000000210
	helved_status_v1 <-- KSTREAM_SINK_0000000236
	helved_pending_utbetalinger_v1 <-- KSTREAM_SINK_0000000241
	helved_simuleringer_v1 <-- KSTREAM_SINK_0000000244
	helved_oppdrag_v1 <-- KSTREAM_SINK_0000000247
	helved_status_v1 <-- KSTREAM_SINK_0000000250
	helved_status_v1 <-- KSTREAM_SINK_0000000254
	helved_fk_v1 <-- KSTREAM_SINK_0000000257
	helved_saker_v1_state_store -- ktable_helved_saker_v1
	dptuple_leftjoin_saker_repartition_source --> dptuple_leftjoin_saker
	dptuple_leftjoin_saker --> KSTREAM_PEEK_0000000039
	KSTREAM_PEEK_0000000039 --> KSTREAM_PROCESSOR_0000000040
	KSTREAM_PROCESSOR_0000000040 --> KSTREAM_BRANCH_0000000041
	KSTREAM_BRANCH_0000000041 --> KSTREAM_BRANCH_00000000411
	KSTREAM_BRANCH_0000000041 --> KSTREAM_BRANCH_00000000410
	aaptuple_leftjoin_saker_repartition_source --> aaptuple_leftjoin_saker
	historisktuple_leftjoin_saker_repartition_source --> historisktuple_leftjoin_saker
	tptuple_leftjoin_saker_repartition_source --> tptuple_leftjoin_saker
	tstuple_leftjoin_saker_repartition_source --> tstuple_leftjoin_saker
	aaptuple_leftjoin_saker --> KSTREAM_PEEK_0000000093
	historisktuple_leftjoin_saker --> KSTREAM_PEEK_0000000227
	tptuple_leftjoin_saker --> KSTREAM_PEEK_0000000180
	tstuple_leftjoin_saker --> KSTREAM_PEEK_0000000140
	KSTREAM_PEEK_0000000093 --> KSTREAM_PROCESSOR_0000000094
	KSTREAM_PEEK_0000000140 --> KSTREAM_PROCESSOR_0000000141
	KSTREAM_PEEK_0000000180 --> KSTREAM_PROCESSOR_0000000181
	KSTREAM_PEEK_0000000227 --> KSTREAM_PROCESSOR_0000000228
	KSTREAM_BRANCH_00000000410 --> KSTREAM_MAPVALUES_0000000048
	KSTREAM_PROCESSOR_0000000094 --> KSTREAM_MAPVALUES_0000000095
	KSTREAM_PROCESSOR_0000000141 --> KSTREAM_MAPVALUES_0000000142
	KSTREAM_PROCESSOR_0000000181 --> KSTREAM_MAPVALUES_0000000182
	KSTREAM_PROCESSOR_0000000228 --> KSTREAM_MAPVALUES_0000000229
	KSTREAM_MAPVALUES_0000000048 --> KSTREAM_KEY_SELECT_0000000049
	KSTREAM_MAPVALUES_0000000095 --> KSTREAM_KEY_SELECT_0000000096
	KSTREAM_MAPVALUES_0000000142 --> KSTREAM_KEY_SELECT_0000000143
	KSTREAM_MAPVALUES_0000000182 --> KSTREAM_KEY_SELECT_0000000183
	KSTREAM_MAPVALUES_0000000229 --> KSTREAM_KEY_SELECT_0000000230
	KSTREAM_KEY_SELECT_0000000049 --> KSTREAM_MAPVALUES_0000000050
	KSTREAM_KEY_SELECT_0000000096 --> KSTREAM_MAPVALUES_0000000097
	KSTREAM_KEY_SELECT_0000000143 --> KSTREAM_MAPVALUES_0000000144
	KSTREAM_KEY_SELECT_0000000183 --> KSTREAM_MAPVALUES_0000000184
	KSTREAM_KEY_SELECT_0000000230 --> KSTREAM_MAPVALUES_0000000231
	KSTREAM_MAPVALUES_0000000050 --> KSTREAM_BRANCH_0000000051
	KSTREAM_MAPVALUES_0000000097 --> KSTREAM_BRANCH_0000000098
	KSTREAM_MAPVALUES_0000000144 --> KSTREAM_BRANCH_0000000145
	KSTREAM_MAPVALUES_0000000184 --> KSTREAM_BRANCH_0000000185
	KSTREAM_MAPVALUES_0000000231 --> KSTREAM_BRANCH_0000000232
	KSTREAM_BRANCH_0000000051 --> KSTREAM_BRANCH_00000000510
	KSTREAM_BRANCH_0000000051 --> KSTREAM_BRANCH_00000000511
	KSTREAM_BRANCH_0000000098 --> KSTREAM_BRANCH_00000000980
	KSTREAM_BRANCH_0000000098 --> KSTREAM_BRANCH_00000000981
	KSTREAM_BRANCH_0000000145 --> KSTREAM_BRANCH_00000001450
	KSTREAM_BRANCH_0000000145 --> KSTREAM_BRANCH_00000001451
	KSTREAM_BRANCH_0000000185 --> KSTREAM_BRANCH_00000001850
	KSTREAM_BRANCH_0000000185 --> KSTREAM_BRANCH_00000001851
	KSTREAM_BRANCH_0000000232 --> KSTREAM_BRANCH_00000002320
	KSTREAM_BRANCH_0000000232 --> KSTREAM_BRANCH_00000002321
	KSTREAM_BRANCH_00000000510 --> KSTREAM_MAPVALUES_0000000057
	KSTREAM_BRANCH_00000000980 --> KSTREAM_MAPVALUES_0000000104
	KSTREAM_BRANCH_00000001450 --> KSTREAM_MAPVALUES_0000000151
	KSTREAM_BRANCH_00000001850 --> KSTREAM_MAPVALUES_0000000191
	KSTREAM_BRANCH_00000002320 --> KSTREAM_MAPVALUES_0000000238
	KSTREAM_MAPVALUES_0000000057 --> KSTREAM_FLATMAPVALUES_0000000064
	KSTREAM_MAPVALUES_0000000057 --> KSTREAM_FILTER_0000000070
	KSTREAM_MAPVALUES_0000000057 --> KSTREAM_FLATMAP_0000000058
	KSTREAM_MAPVALUES_0000000057 --> KSTREAM_FLATMAPVALUES_0000000061
	KSTREAM_MAPVALUES_0000000057 --> KSTREAM_FLATMAP_0000000074
	KSTREAM_MAPVALUES_0000000104 --> KSTREAM_FLATMAPVALUES_0000000111
	KSTREAM_MAPVALUES_0000000104 --> KSTREAM_FILTER_0000000117
	KSTREAM_MAPVALUES_0000000104 --> KSTREAM_FLATMAP_0000000105
	KSTREAM_MAPVALUES_0000000104 --> KSTREAM_FLATMAP_0000000121
	KSTREAM_MAPVALUES_0000000104 --> KSTREAM_FLATMAPVALUES_0000000108
	KSTREAM_MAPVALUES_0000000151 --> KSTREAM_FILTER_0000000164
	KSTREAM_MAPVALUES_0000000151 --> KSTREAM_FLATMAP_0000000152
	KSTREAM_MAPVALUES_0000000151 --> KSTREAM_FLATMAPVALUES_0000000155
	KSTREAM_MAPVALUES_0000000151 --> KSTREAM_FLATMAPVALUES_0000000158
	KSTREAM_MAPVALUES_0000000151 --> KSTREAM_FLATMAP_0000000168
	KSTREAM_MAPVALUES_0000000191 --> KSTREAM_FLATMAP_0000000208
	KSTREAM_MAPVALUES_0000000191 --> KSTREAM_FLATMAPVALUES_0000000198
	KSTREAM_MAPVALUES_0000000191 --> KSTREAM_FLATMAP_0000000192
	KSTREAM_MAPVALUES_0000000191 --> KSTREAM_FLATMAPVALUES_0000000195
	KSTREAM_MAPVALUES_0000000191 --> KSTREAM_FILTER_0000000204
	KSTREAM_MAPVALUES_0000000238 --> KSTREAM_FLATMAPVALUES_0000000245
	KSTREAM_MAPVALUES_0000000238 --> KSTREAM_FILTER_0000000251
	KSTREAM_MAPVALUES_0000000238 --> KSTREAM_FLATMAP_0000000239
	KSTREAM_MAPVALUES_0000000238 --> KSTREAM_FLATMAPVALUES_0000000242
	KSTREAM_MAPVALUES_0000000238 --> KSTREAM_FLATMAP_0000000255
	KSTREAM_FLATMAPVALUES_0000000064 --> KSTREAM_PROCESSOR_0000000065
	KSTREAM_FLATMAPVALUES_0000000064 --> KSTREAM_MAPVALUES_0000000067
	KSTREAM_FLATMAPVALUES_0000000111 --> KSTREAM_MAPVALUES_0000000114
	KSTREAM_FLATMAPVALUES_0000000111 --> KSTREAM_PROCESSOR_0000000112
	KSTREAM_FLATMAPVALUES_0000000158 --> KSTREAM_MAPVALUES_0000000161
	KSTREAM_FLATMAPVALUES_0000000158 --> KSTREAM_PROCESSOR_0000000159
	KSTREAM_FLATMAPVALUES_0000000198 --> KSTREAM_MAPVALUES_0000000201
	KSTREAM_FLATMAPVALUES_0000000198 --> KSTREAM_PROCESSOR_0000000199
	KSTREAM_FLATMAPVALUES_0000000245 --> KSTREAM_MAPVALUES_0000000248
	KSTREAM_FLATMAPVALUES_0000000245 --> KSTREAM_PROCESSOR_0000000246
	KSTREAM_BRANCH_00000000411 --> KSTREAM_KEY_SELECT_0000000043
	KSTREAM_BRANCH_00000000511 --> KSTREAM_MAPVALUES_0000000053
	KSTREAM_BRANCH_00000000981 --> KSTREAM_MAPVALUES_0000000100
	KSTREAM_BRANCH_00000001451 --> KSTREAM_MAPVALUES_0000000147
	KSTREAM_BRANCH_00000001851 --> KSTREAM_MAPVALUES_0000000187
	KSTREAM_BRANCH_00000002321 --> KSTREAM_MAPVALUES_0000000234
	KSTREAM_FILTER_0000000070 --> KSTREAM_MAPVALUES_0000000071
	KSTREAM_FILTER_0000000117 --> KSTREAM_MAPVALUES_0000000118
	KSTREAM_FILTER_0000000164 --> KSTREAM_MAPVALUES_0000000165
	KSTREAM_FILTER_0000000204 --> KSTREAM_MAPVALUES_0000000205
	KSTREAM_FILTER_0000000251 --> KSTREAM_MAPVALUES_0000000252
	KSTREAM_KEY_SELECT_0000000043 --> KSTREAM_MAPVALUES_0000000044
	KSTREAM_FLATMAP_0000000058 --> KSTREAM_PROCESSOR_0000000059
	KSTREAM_FLATMAP_0000000074 --> KSTREAM_PROCESSOR_0000000075
	KSTREAM_FLATMAP_0000000105 --> KSTREAM_PROCESSOR_0000000106
	KSTREAM_FLATMAP_0000000121 --> KSTREAM_PROCESSOR_0000000122
	KSTREAM_FLATMAP_0000000152 --> KSTREAM_PROCESSOR_0000000153
	KSTREAM_FLATMAP_0000000168 --> KSTREAM_PROCESSOR_0000000169
	KSTREAM_FLATMAP_0000000192 --> KSTREAM_PROCESSOR_0000000193
	KSTREAM_FLATMAP_0000000208 --> KSTREAM_PROCESSOR_0000000209
	KSTREAM_FLATMAP_0000000239 --> KSTREAM_PROCESSOR_0000000240
	KSTREAM_FLATMAP_0000000255 --> KSTREAM_PROCESSOR_0000000256
	KSTREAM_FLATMAPVALUES_0000000061 --> KSTREAM_PROCESSOR_0000000062
	KSTREAM_FLATMAPVALUES_0000000108 --> KSTREAM_PROCESSOR_0000000109
	KSTREAM_FLATMAPVALUES_0000000155 --> KSTREAM_PROCESSOR_0000000156
	KSTREAM_FLATMAPVALUES_0000000195 --> KSTREAM_PROCESSOR_0000000196
	KSTREAM_FLATMAPVALUES_0000000242 --> KSTREAM_PROCESSOR_0000000243
	KSTREAM_MAPVALUES_0000000044 --> KSTREAM_PROCESSOR_0000000045
	KSTREAM_MAPVALUES_0000000053 --> KSTREAM_PROCESSOR_0000000054
	KSTREAM_MAPVALUES_0000000067 --> KSTREAM_PROCESSOR_0000000068
	KSTREAM_MAPVALUES_0000000071 --> KSTREAM_PROCESSOR_0000000072
	KSTREAM_MAPVALUES_0000000100 --> KSTREAM_PROCESSOR_0000000101
	KSTREAM_MAPVALUES_0000000114 --> KSTREAM_PROCESSOR_0000000115
	KSTREAM_MAPVALUES_0000000118 --> KSTREAM_PROCESSOR_0000000119
	KSTREAM_MAPVALUES_0000000147 --> KSTREAM_PROCESSOR_0000000148
	KSTREAM_MAPVALUES_0000000161 --> KSTREAM_PROCESSOR_0000000162
	KSTREAM_MAPVALUES_0000000165 --> KSTREAM_PROCESSOR_0000000166
	KSTREAM_MAPVALUES_0000000187 --> KSTREAM_PROCESSOR_0000000188
	KSTREAM_MAPVALUES_0000000201 --> KSTREAM_PROCESSOR_0000000202
	KSTREAM_MAPVALUES_0000000205 --> KSTREAM_PROCESSOR_0000000206
	KSTREAM_MAPVALUES_0000000234 --> KSTREAM_PROCESSOR_0000000235
	KSTREAM_MAPVALUES_0000000248 --> KSTREAM_PROCESSOR_0000000249
	KSTREAM_MAPVALUES_0000000252 --> KSTREAM_PROCESSOR_0000000253
	KSTREAM_PROCESSOR_0000000045 --> KSTREAM_SINK_0000000046
	KSTREAM_PROCESSOR_0000000054 --> KSTREAM_SINK_0000000055
	KSTREAM_PROCESSOR_0000000059 --> KSTREAM_SINK_0000000060
	KSTREAM_PROCESSOR_0000000062 --> KSTREAM_SINK_0000000063
	KSTREAM_PROCESSOR_0000000065 --> KSTREAM_SINK_0000000066
	KSTREAM_PROCESSOR_0000000068 --> KSTREAM_SINK_0000000069
	KSTREAM_PROCESSOR_0000000072 --> KSTREAM_SINK_0000000073
	KSTREAM_PROCESSOR_0000000075 --> KSTREAM_SINK_0000000076
	KSTREAM_PROCESSOR_0000000101 --> KSTREAM_SINK_0000000102
	KSTREAM_PROCESSOR_0000000106 --> KSTREAM_SINK_0000000107
	KSTREAM_PROCESSOR_0000000109 --> KSTREAM_SINK_0000000110
	KSTREAM_PROCESSOR_0000000112 --> KSTREAM_SINK_0000000113
	KSTREAM_PROCESSOR_0000000115 --> KSTREAM_SINK_0000000116
	KSTREAM_PROCESSOR_0000000119 --> KSTREAM_SINK_0000000120
	KSTREAM_PROCESSOR_0000000122 --> KSTREAM_SINK_0000000123
	KSTREAM_PROCESSOR_0000000148 --> KSTREAM_SINK_0000000149
	KSTREAM_PROCESSOR_0000000153 --> KSTREAM_SINK_0000000154
	KSTREAM_PROCESSOR_0000000156 --> KSTREAM_SINK_0000000157
	KSTREAM_PROCESSOR_0000000159 --> KSTREAM_SINK_0000000160
	KSTREAM_PROCESSOR_0000000162 --> KSTREAM_SINK_0000000163
	KSTREAM_PROCESSOR_0000000166 --> KSTREAM_SINK_0000000167
	KSTREAM_PROCESSOR_0000000169 --> KSTREAM_SINK_0000000170
	KSTREAM_PROCESSOR_0000000188 --> KSTREAM_SINK_0000000189
	KSTREAM_PROCESSOR_0000000193 --> KSTREAM_SINK_0000000194
	KSTREAM_PROCESSOR_0000000196 --> KSTREAM_SINK_0000000197
	KSTREAM_PROCESSOR_0000000199 --> KSTREAM_SINK_0000000200
	KSTREAM_PROCESSOR_0000000202 --> KSTREAM_SINK_0000000203
	KSTREAM_PROCESSOR_0000000206 --> KSTREAM_SINK_0000000207
	KSTREAM_PROCESSOR_0000000209 --> KSTREAM_SINK_0000000210
	KSTREAM_PROCESSOR_0000000235 --> KSTREAM_SINK_0000000236
	KSTREAM_PROCESSOR_0000000240 --> KSTREAM_SINK_0000000241
	KSTREAM_PROCESSOR_0000000243 --> KSTREAM_SINK_0000000244
	KSTREAM_PROCESSOR_0000000246 --> KSTREAM_SINK_0000000247
	KSTREAM_PROCESSOR_0000000249 --> KSTREAM_SINK_0000000250
	KSTREAM_PROCESSOR_0000000253 --> KSTREAM_SINK_0000000254
	KSTREAM_PROCESSOR_0000000256 --> KSTREAM_SINK_0000000257
	ktable_helved_saker_v1_repartition_source --> ktable_helved_saker_v1
}
package "Sub-topology: 5" {
	agent "consume-helved.fk.v1" <<Source>> as consume_helved_fk_v1
	agent "KSTREAM-PROCESSOR-0000000017" <<Processor>> as KSTREAM_PROCESSOR_0000000017
	agent "KSTREAM-PROCESSOR-0000000018" <<Processor>> as KSTREAM_PROCESSOR_0000000018
	agent "ktable-helved.fk.v1-repartition-filter" <<Processor>> as ktable_helved_fk_v1_repartition_filter
	agent "ktable-helved.fk.v1-repartition-sink" <<Sink>> as ktable_helved_fk_v1_repartition_sink
	helved_fk_v1 --> consume_helved_fk_v1
	ktable_helved_fk_v1_repartition <-- ktable_helved_fk_v1_repartition_sink
	consume_helved_fk_v1 --> KSTREAM_PROCESSOR_0000000017
	KSTREAM_PROCESSOR_0000000017 --> KSTREAM_PROCESSOR_0000000018
	KSTREAM_PROCESSOR_0000000018 --> ktable_helved_fk_v1_repartition_filter
	ktable_helved_fk_v1_repartition_filter --> ktable_helved_fk_v1_repartition_sink
}
package "Sub-topology: 6" {
	database "helved.fk.v1-state-store-v4" <<State Store>> as helved_fk_v1_state_store_v4
	agent "oppdrag-leftjoin-fks-repartition-source" <<Source>> as oppdrag_leftjoin_fks_repartition_source
	agent "oppdrag-leftjoin-fks" <<Processor>> as oppdrag_leftjoin_fks
	agent "KSTREAM-FLATMAP-0000000268" <<Processor>> as KSTREAM_FLATMAP_0000000268
	agent "ktable-helved.fk.v1-repartition-source" <<Source>> as ktable_helved_fk_v1_repartition_source
	agent "pk-leftjoin-pending-repartition-filter" <<Processor>> as pk_leftjoin_pending_repartition_filter
	agent "ktable-helved.fk.v1" <<Processor>> as ktable_helved_fk_v1
	agent "pk-leftjoin-pending-repartition-sink" <<Sink>> as pk_leftjoin_pending_repartition_sink
	oppdrag_leftjoin_fks_repartition --> oppdrag_leftjoin_fks_repartition_source
	helved_fk_v1_state_store_v4 -- oppdrag_leftjoin_fks
	ktable_helved_fk_v1_repartition --> ktable_helved_fk_v1_repartition_source
	helved_fk_v1_state_store_v4 -- ktable_helved_fk_v1
	pk_leftjoin_pending_repartition <-- pk_leftjoin_pending_repartition_sink
	oppdrag_leftjoin_fks_repartition_source --> oppdrag_leftjoin_fks
	oppdrag_leftjoin_fks --> KSTREAM_FLATMAP_0000000268
	KSTREAM_FLATMAP_0000000268 --> pk_leftjoin_pending_repartition_filter
	ktable_helved_fk_v1_repartition_source --> ktable_helved_fk_v1
	pk_leftjoin_pending_repartition_filter --> pk_leftjoin_pending_repartition_sink
}
package "Sub-topology: 7" {
	agent "consume-teamdagpenger.utbetaling.v1" <<Source>> as consume_teamdagpenger_utbetaling_v1
	agent "KSTREAM-PROCESSOR-0000000024" <<Processor>> as KSTREAM_PROCESSOR_0000000024
	agent "KSTREAM-FILTER-0000000025" <<Processor>> as KSTREAM_FILTER_0000000025
	agent "from-teamdagpenger.utbetaling.v1-repartition-filter" <<Processor>> as from_teamdagpenger_utbetaling_v1_repartition_filter
	agent "from-teamdagpenger.utbetaling.v1-repartition-sink" <<Sink>> as from_teamdagpenger_utbetaling_v1_repartition_sink
	teamdagpenger_utbetaling_v1 --> consume_teamdagpenger_utbetaling_v1
	from_teamdagpenger_utbetaling_v1_repartition <-- from_teamdagpenger_utbetaling_v1_repartition_sink
	consume_teamdagpenger_utbetaling_v1 --> KSTREAM_PROCESSOR_0000000024
	KSTREAM_PROCESSOR_0000000024 --> KSTREAM_FILTER_0000000025
	KSTREAM_FILTER_0000000025 --> from_teamdagpenger_utbetaling_v1_repartition_filter
	from_teamdagpenger_utbetaling_v1_repartition_filter --> from_teamdagpenger_utbetaling_v1_repartition_sink
}
package "Sub-topology: 8" {
	agent "consume-helved.utbetalinger-dp.v1" <<Source>> as consume_helved_utbetalinger_dp_v1
	agent "KSTREAM-PROCESSOR-0000000030" <<Processor>> as KSTREAM_PROCESSOR_0000000030
	agent "KSTREAM-FILTER-0000000031" <<Processor>> as KSTREAM_FILTER_0000000031
	agent "from-teamdagpenger.utbetaling.v1-repartition-source" <<Source>> as from_teamdagpenger_utbetaling_v1_repartition_source
	agent "KSTREAM-MERGE-0000000032" <<Processor>> as KSTREAM_MERGE_0000000032
	agent "KSTREAM-MAPVALUES-0000000033" <<Processor>> as KSTREAM_MAPVALUES_0000000033
	agent "KSTREAM-KEY-SELECT-0000000034" <<Processor>> as KSTREAM_KEY_SELECT_0000000034
	agent "dptuple-leftjoin-saker-repartition-filter" <<Processor>> as dptuple_leftjoin_saker_repartition_filter
	agent "dptuple-leftjoin-saker-repartition-sink" <<Sink>> as dptuple_leftjoin_saker_repartition_sink
	helved_utbetalinger_dp_v1 --> consume_helved_utbetalinger_dp_v1
	from_teamdagpenger_utbetaling_v1_repartition --> from_teamdagpenger_utbetaling_v1_repartition_source
	dptuple_leftjoin_saker_repartition <-- dptuple_leftjoin_saker_repartition_sink
	consume_helved_utbetalinger_dp_v1 --> KSTREAM_PROCESSOR_0000000030
	KSTREAM_PROCESSOR_0000000030 --> KSTREAM_FILTER_0000000031
	KSTREAM_FILTER_0000000031 --> KSTREAM_MERGE_0000000032
	from_teamdagpenger_utbetaling_v1_repartition_source --> KSTREAM_MERGE_0000000032
	KSTREAM_MERGE_0000000032 --> KSTREAM_MAPVALUES_0000000033
	KSTREAM_MAPVALUES_0000000033 --> KSTREAM_KEY_SELECT_0000000034
	KSTREAM_KEY_SELECT_0000000034 --> dptuple_leftjoin_saker_repartition_filter
	dptuple_leftjoin_saker_repartition_filter --> dptuple_leftjoin_saker_repartition_sink
}
package "Sub-topology: 9" {
	agent "consume-aap.utbetaling.v1" <<Source>> as consume_aap_utbetaling_v1
	agent "KSTREAM-PROCESSOR-0000000078" <<Processor>> as KSTREAM_PROCESSOR_0000000078
	agent "KSTREAM-FILTER-0000000079" <<Processor>> as KSTREAM_FILTER_0000000079
	agent "from-aap.utbetaling.v1-repartition-filter" <<Processor>> as from_aap_utbetaling_v1_repartition_filter
	agent "from-aap.utbetaling.v1-repartition-sink" <<Sink>> as from_aap_utbetaling_v1_repartition_sink
	aap_utbetaling_v1 --> consume_aap_utbetaling_v1
	from_aap_utbetaling_v1_repartition <-- from_aap_utbetaling_v1_repartition_sink
	consume_aap_utbetaling_v1 --> KSTREAM_PROCESSOR_0000000078
	KSTREAM_PROCESSOR_0000000078 --> KSTREAM_FILTER_0000000079
	KSTREAM_FILTER_0000000079 --> from_aap_utbetaling_v1_repartition_filter
	from_aap_utbetaling_v1_repartition_filter --> from_aap_utbetaling_v1_repartition_sink
}
package "Sub-topology: 10" {
	agent "consume-helved.utbetalinger-aap.v1" <<Source>> as consume_helved_utbetalinger_aap_v1
	agent "KSTREAM-PROCESSOR-0000000084" <<Processor>> as KSTREAM_PROCESSOR_0000000084
	agent "KSTREAM-FILTER-0000000085" <<Processor>> as KSTREAM_FILTER_0000000085
	agent "from-aap.utbetaling.v1-repartition-source" <<Source>> as from_aap_utbetaling_v1_repartition_source
	agent "KSTREAM-MERGE-0000000086" <<Processor>> as KSTREAM_MERGE_0000000086
	agent "KSTREAM-MAPVALUES-0000000087" <<Processor>> as KSTREAM_MAPVALUES_0000000087
	agent "KSTREAM-KEY-SELECT-0000000088" <<Processor>> as KSTREAM_KEY_SELECT_0000000088
	agent "aaptuple-leftjoin-saker-repartition-filter" <<Processor>> as aaptuple_leftjoin_saker_repartition_filter
	agent "aaptuple-leftjoin-saker-repartition-sink" <<Sink>> as aaptuple_leftjoin_saker_repartition_sink
	helved_utbetalinger_aap_v1 --> consume_helved_utbetalinger_aap_v1
	from_aap_utbetaling_v1_repartition --> from_aap_utbetaling_v1_repartition_source
	aaptuple_leftjoin_saker_repartition <-- aaptuple_leftjoin_saker_repartition_sink
	consume_helved_utbetalinger_aap_v1 --> KSTREAM_PROCESSOR_0000000084
	KSTREAM_PROCESSOR_0000000084 --> KSTREAM_FILTER_0000000085
	KSTREAM_FILTER_0000000085 --> KSTREAM_MERGE_0000000086
	from_aap_utbetaling_v1_repartition_source --> KSTREAM_MERGE_0000000086
	KSTREAM_MERGE_0000000086 --> KSTREAM_MAPVALUES_0000000087
	KSTREAM_MAPVALUES_0000000087 --> KSTREAM_KEY_SELECT_0000000088
	KSTREAM_KEY_SELECT_0000000088 --> aaptuple_leftjoin_saker_repartition_filter
	aaptuple_leftjoin_saker_repartition_filter --> aaptuple_leftjoin_saker_repartition_sink
}
package "Sub-topology: 11" {
	agent "consume-tilleggsstonader.utbetaling.v1" <<Source>> as consume_tilleggsstonader_utbetaling_v1
	agent "KSTREAM-PROCESSOR-0000000125" <<Processor>> as KSTREAM_PROCESSOR_0000000125
	agent "KSTREAM-FILTER-0000000126" <<Processor>> as KSTREAM_FILTER_0000000126
	agent "from-tilleggsstonader.utbetaling.v1-repartition-filter" <<Processor>> as from_tilleggsstonader_utbetaling_v1_repartition_filter
	agent "from-tilleggsstonader.utbetaling.v1-repartition-sink" <<Sink>> as from_tilleggsstonader_utbetaling_v1_repartition_sink
	tilleggsstonader_utbetaling_v1 --> consume_tilleggsstonader_utbetaling_v1
	from_tilleggsstonader_utbetaling_v1_repartition <-- from_tilleggsstonader_utbetaling_v1_repartition_sink
	consume_tilleggsstonader_utbetaling_v1 --> KSTREAM_PROCESSOR_0000000125
	KSTREAM_PROCESSOR_0000000125 --> KSTREAM_FILTER_0000000126
	KSTREAM_FILTER_0000000126 --> from_tilleggsstonader_utbetaling_v1_repartition_filter
	from_tilleggsstonader_utbetaling_v1_repartition_filter --> from_tilleggsstonader_utbetaling_v1_repartition_sink
}
package "Sub-topology: 12" {
	agent "consume-helved.utbetalinger-ts.v1" <<Source>> as consume_helved_utbetalinger_ts_v1
	agent "KSTREAM-PROCESSOR-0000000131" <<Processor>> as KSTREAM_PROCESSOR_0000000131
	agent "KSTREAM-FILTER-0000000132" <<Processor>> as KSTREAM_FILTER_0000000132
	agent "from-tilleggsstonader.utbetaling.v1-repartition-source" <<Source>> as from_tilleggsstonader_utbetaling_v1_repartition_source
	agent "KSTREAM-MERGE-0000000133" <<Processor>> as KSTREAM_MERGE_0000000133
	agent "KSTREAM-MAPVALUES-0000000134" <<Processor>> as KSTREAM_MAPVALUES_0000000134
	agent "KSTREAM-KEY-SELECT-0000000135" <<Processor>> as KSTREAM_KEY_SELECT_0000000135
	agent "tstuple-leftjoin-saker-repartition-filter" <<Processor>> as tstuple_leftjoin_saker_repartition_filter
	agent "tstuple-leftjoin-saker-repartition-sink" <<Sink>> as tstuple_leftjoin_saker_repartition_sink
	helved_utbetalinger_ts_v1 --> consume_helved_utbetalinger_ts_v1
	from_tilleggsstonader_utbetaling_v1_repartition --> from_tilleggsstonader_utbetaling_v1_repartition_source
	tstuple_leftjoin_saker_repartition <-- tstuple_leftjoin_saker_repartition_sink
	consume_helved_utbetalinger_ts_v1 --> KSTREAM_PROCESSOR_0000000131
	KSTREAM_PROCESSOR_0000000131 --> KSTREAM_FILTER_0000000132
	KSTREAM_FILTER_0000000132 --> KSTREAM_MERGE_0000000133
	from_tilleggsstonader_utbetaling_v1_repartition_source --> KSTREAM_MERGE_0000000133
	KSTREAM_MERGE_0000000133 --> KSTREAM_MAPVALUES_0000000134
	KSTREAM_MAPVALUES_0000000134 --> KSTREAM_KEY_SELECT_0000000135
	KSTREAM_KEY_SELECT_0000000135 --> tstuple_leftjoin_saker_repartition_filter
	tstuple_leftjoin_saker_repartition_filter --> tstuple_leftjoin_saker_repartition_sink
}
package "Sub-topology: 13" {
	agent "consume-helved.utbetalinger-tp.v1" <<Source>> as consume_helved_utbetalinger_tp_v1
	agent "KSTREAM-PROCESSOR-0000000172" <<Processor>> as KSTREAM_PROCESSOR_0000000172
	agent "KSTREAM-FILTER-0000000173" <<Processor>> as KSTREAM_FILTER_0000000173
	agent "KSTREAM-MAPVALUES-0000000174" <<Processor>> as KSTREAM_MAPVALUES_0000000174
	agent "KSTREAM-KEY-SELECT-0000000175" <<Processor>> as KSTREAM_KEY_SELECT_0000000175
	agent "tptuple-leftjoin-saker-repartition-filter" <<Processor>> as tptuple_leftjoin_saker_repartition_filter
	agent "tptuple-leftjoin-saker-repartition-sink" <<Sink>> as tptuple_leftjoin_saker_repartition_sink
	helved_utbetalinger_tp_v1 --> consume_helved_utbetalinger_tp_v1
	tptuple_leftjoin_saker_repartition <-- tptuple_leftjoin_saker_repartition_sink
	consume_helved_utbetalinger_tp_v1 --> KSTREAM_PROCESSOR_0000000172
	KSTREAM_PROCESSOR_0000000172 --> KSTREAM_FILTER_0000000173
	KSTREAM_FILTER_0000000173 --> KSTREAM_MAPVALUES_0000000174
	KSTREAM_MAPVALUES_0000000174 --> KSTREAM_KEY_SELECT_0000000175
	KSTREAM_KEY_SELECT_0000000175 --> tptuple_leftjoin_saker_repartition_filter
	tptuple_leftjoin_saker_repartition_filter --> tptuple_leftjoin_saker_repartition_sink
}
package "Sub-topology: 14" {
	agent "consume-historisk.utbetaling.v1" <<Source>> as consume_historisk_utbetaling_v1
	agent "KSTREAM-PROCESSOR-0000000212" <<Processor>> as KSTREAM_PROCESSOR_0000000212
	agent "KSTREAM-FILTER-0000000213" <<Processor>> as KSTREAM_FILTER_0000000213
	agent "from-historisk.utbetaling.v1-repartition-filter" <<Processor>> as from_historisk_utbetaling_v1_repartition_filter
	agent "from-historisk.utbetaling.v1-repartition-sink" <<Sink>> as from_historisk_utbetaling_v1_repartition_sink
	historisk_utbetaling_v1 --> consume_historisk_utbetaling_v1
	from_historisk_utbetaling_v1_repartition <-- from_historisk_utbetaling_v1_repartition_sink
	consume_historisk_utbetaling_v1 --> KSTREAM_PROCESSOR_0000000212
	KSTREAM_PROCESSOR_0000000212 --> KSTREAM_FILTER_0000000213
	KSTREAM_FILTER_0000000213 --> from_historisk_utbetaling_v1_repartition_filter
	from_historisk_utbetaling_v1_repartition_filter --> from_historisk_utbetaling_v1_repartition_sink
}
package "Sub-topology: 15" {
	agent "consume-helved.utbetalinger-historisk.v1" <<Source>> as consume_helved_utbetalinger_historisk_v1
	agent "KSTREAM-PROCESSOR-0000000218" <<Processor>> as KSTREAM_PROCESSOR_0000000218
	agent "KSTREAM-FILTER-0000000219" <<Processor>> as KSTREAM_FILTER_0000000219
	agent "from-historisk.utbetaling.v1-repartition-source" <<Source>> as from_historisk_utbetaling_v1_repartition_source
	agent "KSTREAM-MERGE-0000000220" <<Processor>> as KSTREAM_MERGE_0000000220
	agent "KSTREAM-MAPVALUES-0000000221" <<Processor>> as KSTREAM_MAPVALUES_0000000221
	agent "KSTREAM-KEY-SELECT-0000000222" <<Processor>> as KSTREAM_KEY_SELECT_0000000222
	agent "historisktuple-leftjoin-saker-repartition-filter" <<Processor>> as historisktuple_leftjoin_saker_repartition_filter
	agent "historisktuple-leftjoin-saker-repartition-sink" <<Sink>> as historisktuple_leftjoin_saker_repartition_sink
	helved_utbetalinger_historisk_v1 --> consume_helved_utbetalinger_historisk_v1
	from_historisk_utbetaling_v1_repartition --> from_historisk_utbetaling_v1_repartition_source
	historisktuple_leftjoin_saker_repartition <-- historisktuple_leftjoin_saker_repartition_sink
	consume_helved_utbetalinger_historisk_v1 --> KSTREAM_PROCESSOR_0000000218
	KSTREAM_PROCESSOR_0000000218 --> KSTREAM_FILTER_0000000219
	KSTREAM_FILTER_0000000219 --> KSTREAM_MERGE_0000000220
	from_historisk_utbetaling_v1_repartition_source --> KSTREAM_MERGE_0000000220
	KSTREAM_MERGE_0000000220 --> KSTREAM_MAPVALUES_0000000221
	KSTREAM_MAPVALUES_0000000221 --> KSTREAM_KEY_SELECT_0000000222
	KSTREAM_KEY_SELECT_0000000222 --> historisktuple_leftjoin_saker_repartition_filter
	historisktuple_leftjoin_saker_repartition_filter --> historisktuple_leftjoin_saker_repartition_sink
}
package "Sub-topology: 16" {
	agent "consume-helved.oppdrag.v1" <<Source>> as consume_helved_oppdrag_v1
	agent "KSTREAM-PROCESSOR-0000000259" <<Processor>> as KSTREAM_PROCESSOR_0000000259
	agent "KSTREAM-FILTER-0000000260" <<Processor>> as KSTREAM_FILTER_0000000260
	agent "KSTREAM-FILTER-0000000261" <<Processor>> as KSTREAM_FILTER_0000000261
	agent "KSTREAM-KEY-SELECT-0000000262" <<Processor>> as KSTREAM_KEY_SELECT_0000000262
	agent "KSTREAM-MAPVALUES-0000000263" <<Processor>> as KSTREAM_MAPVALUES_0000000263
	agent "oppdrag-leftjoin-fks-repartition-filter" <<Processor>> as oppdrag_leftjoin_fks_repartition_filter
	agent "oppdrag-leftjoin-fks-repartition-sink" <<Sink>> as oppdrag_leftjoin_fks_repartition_sink
	helved_oppdrag_v1 --> consume_helved_oppdrag_v1
	oppdrag_leftjoin_fks_repartition <-- oppdrag_leftjoin_fks_repartition_sink
	consume_helved_oppdrag_v1 --> KSTREAM_PROCESSOR_0000000259
	KSTREAM_PROCESSOR_0000000259 --> KSTREAM_FILTER_0000000260
	KSTREAM_FILTER_0000000260 --> KSTREAM_FILTER_0000000261
	KSTREAM_FILTER_0000000261 --> KSTREAM_KEY_SELECT_0000000262
	KSTREAM_KEY_SELECT_0000000262 --> KSTREAM_MAPVALUES_0000000263
	KSTREAM_MAPVALUES_0000000263 --> oppdrag_leftjoin_fks_repartition_filter
	oppdrag_leftjoin_fks_repartition_filter --> oppdrag_leftjoin_fks_repartition_sink
}
@enduml