
%%{init: {'theme': 'dark', 'themeVariables': { 'primaryColor': '#07cff6', 'textColor': '#dad9e0', 'lineColor': '#07cff6'}}}%%

graph LR

subgraph Topologi
    %% TOPICS
    helved.pending-utbetalinger.v1([helved.pending-utbetalinger.v1])
	ktable-helved.pending-utbetalinger.v1-repartition([ktable-helved.pending-utbetalinger.v1-repartition])
	pk-leftjoin-pending-repartition([pk-leftjoin-pending-repartition])
	helved.utbetalinger.v1([helved.utbetalinger.v1])
	helved.saker.v1([helved.saker.v1])
	ktable-helved.saker.v1-repartition([ktable-helved.saker.v1-repartition])
	dptuple-leftjoin-saker-repartition([dptuple-leftjoin-saker-repartition])
	tstuple-leftjoin-saker-repartition([tstuple-leftjoin-saker-repartition])
	aaptuple-leftjoin-saker-repartition([aaptuple-leftjoin-saker-repartition])
	historisktuple-leftjoin-saker-repartition([historisktuple-leftjoin-saker-repartition])
	tptuple-leftjoin-saker-repartition([tptuple-leftjoin-saker-repartition])
	helved.status.v1([helved.status.v1])
	helved.simuleringer.v1([helved.simuleringer.v1])
	helved.oppdrag.v1([helved.oppdrag.v1])
	helved.dryrun-aap.v1([helved.dryrun-aap.v1])
	helved.dryrun-dp.v1([helved.dryrun-dp.v1])
	helved.dryrun-ts.v1([helved.dryrun-ts.v1])
	helved.dryrun-tp.v1([helved.dryrun-tp.v1])
	teamdagpenger.utbetaling.v1([teamdagpenger.utbetaling.v1])
	from-teamdagpenger.utbetaling.v1-repartition([from-teamdagpenger.utbetaling.v1-repartition])
	helved.utbetalinger-dp.v1([helved.utbetalinger-dp.v1])
	aap.utbetaling.v1([aap.utbetaling.v1])
	from-aap.utbetaling.v1-repartition([from-aap.utbetaling.v1-repartition])
	helved.utbetalinger-aap.v1([helved.utbetalinger-aap.v1])
	tilleggsstonader.utbetaling.v1([tilleggsstonader.utbetaling.v1])
	from-tilleggsstonader.utbetaling.v1-repartition([from-tilleggsstonader.utbetaling.v1-repartition])
	helved.utbetalinger-ts.v1([helved.utbetalinger-ts.v1])
	helved.utbetalinger-tp.v1([helved.utbetalinger-tp.v1])
	historisk.utbetaling.v1([historisk.utbetaling.v1])
	from-historisk.utbetaling.v1-repartition([from-historisk.utbetaling.v1-repartition])
	helved.utbetalinger-historisk.v1([helved.utbetalinger-historisk.v1])

    %% JOINS
    pk-leftjoin-pending{leftjoin}
	dptuple-leftjoin-saker{leftjoin}
	tstuple-leftjoin-saker{leftjoin}
	aaptuple-leftjoin-saker{leftjoin}
	historisktuple-leftjoin-saker{leftjoin}
	tptuple-leftjoin-saker{leftjoin}

    %% STATE PROCESSORS
    
    
    %% STATE STORES
    helved.pending-utbetalinger.v1-state-store-v4[(helved.pending-utbetalinger.v1-state-store-v4)]
	helved.saker.v1-state-store[(helved.saker.v1-state-store)]
    
    %% DATABASES
    
    

    %% PROCESSOR API JOBS
    
    
    %% JOIN STREAMS
    pk-leftjoin-pending-repartition --> pk-leftjoin-pending
	helved.pending-utbetalinger.v1-state-store-v4 --> pk-leftjoin-pending
	pk-leftjoin-pending --> helved.utbetalinger.v1
	dptuple-leftjoin-saker-repartition --> dptuple-leftjoin-saker
	helved.saker.v1-state-store --> dptuple-leftjoin-saker
	dptuple-leftjoin-saker --> helved.simuleringer.v1
	dptuple-leftjoin-saker --> helved.pending-utbetalinger.v1
	dptuple-leftjoin-saker --> helved.status.v1
	dptuple-leftjoin-saker --> helved.oppdrag.v1
	dptuple-leftjoin-saker --> helved.dryrun-aap.v1
	dptuple-leftjoin-saker --> helved.dryrun-dp.v1
	dptuple-leftjoin-saker --> helved.dryrun-ts.v1
	dptuple-leftjoin-saker --> helved.dryrun-tp.v1
	tstuple-leftjoin-saker-repartition --> tstuple-leftjoin-saker
	helved.saker.v1-state-store --> tstuple-leftjoin-saker
	tstuple-leftjoin-saker --> helved.dryrun-aap.v1
	tstuple-leftjoin-saker --> helved.dryrun-dp.v1
	tstuple-leftjoin-saker --> helved.dryrun-ts.v1
	tstuple-leftjoin-saker --> helved.dryrun-tp.v1
	tstuple-leftjoin-saker --> helved.simuleringer.v1
	tstuple-leftjoin-saker --> helved.pending-utbetalinger.v1
	tstuple-leftjoin-saker --> helved.status.v1
	tstuple-leftjoin-saker --> helved.oppdrag.v1
	aaptuple-leftjoin-saker-repartition --> aaptuple-leftjoin-saker
	helved.saker.v1-state-store --> aaptuple-leftjoin-saker
	aaptuple-leftjoin-saker --> helved.status.v1
	aaptuple-leftjoin-saker --> helved.oppdrag.v1
	aaptuple-leftjoin-saker --> helved.simuleringer.v1
	aaptuple-leftjoin-saker --> helved.dryrun-tp.v1
	aaptuple-leftjoin-saker --> helved.dryrun-aap.v1
	aaptuple-leftjoin-saker --> helved.dryrun-dp.v1
	aaptuple-leftjoin-saker --> helved.dryrun-ts.v1
	aaptuple-leftjoin-saker --> helved.pending-utbetalinger.v1
	historisktuple-leftjoin-saker-repartition --> historisktuple-leftjoin-saker
	helved.saker.v1-state-store --> historisktuple-leftjoin-saker
	historisktuple-leftjoin-saker --> helved.dryrun-aap.v1
	historisktuple-leftjoin-saker --> helved.dryrun-dp.v1
	historisktuple-leftjoin-saker --> helved.dryrun-ts.v1
	historisktuple-leftjoin-saker --> helved.dryrun-tp.v1
	historisktuple-leftjoin-saker --> helved.pending-utbetalinger.v1
	historisktuple-leftjoin-saker --> helved.status.v1
	historisktuple-leftjoin-saker --> helved.simuleringer.v1
	historisktuple-leftjoin-saker --> helved.oppdrag.v1
	tptuple-leftjoin-saker-repartition --> tptuple-leftjoin-saker
	helved.saker.v1-state-store --> tptuple-leftjoin-saker
	tptuple-leftjoin-saker --> helved.status.v1
	tptuple-leftjoin-saker --> helved.dryrun-aap.v1
	tptuple-leftjoin-saker --> helved.dryrun-dp.v1
	tptuple-leftjoin-saker --> helved.dryrun-ts.v1
	tptuple-leftjoin-saker --> helved.dryrun-tp.v1
	tptuple-leftjoin-saker --> helved.oppdrag.v1
	tptuple-leftjoin-saker --> helved.pending-utbetalinger.v1
	tptuple-leftjoin-saker --> helved.simuleringer.v1

    %% TABLE STREAMS
    

    %% JOB STREAMS
    
    
    %% BRANCH STREAMS
    

    %% REPARTITION STREAMS
    
    
    %% BASIC STREAMS
    helved.pending-utbetalinger.v1 --> ktable-helved.pending-utbetalinger.v1-repartition
	helved.saker.v1 --> ktable-helved.saker.v1-repartition
	teamdagpenger.utbetaling.v1 --> from-teamdagpenger.utbetaling.v1-repartition
	helved.utbetalinger-dp.v1 --> dptuple-leftjoin-saker-repartition
	from-teamdagpenger.utbetaling.v1-repartition --> dptuple-leftjoin-saker-repartition
	aap.utbetaling.v1 --> from-aap.utbetaling.v1-repartition
	helved.utbetalinger-aap.v1 --> aaptuple-leftjoin-saker-repartition
	from-aap.utbetaling.v1-repartition --> aaptuple-leftjoin-saker-repartition
	tilleggsstonader.utbetaling.v1 --> from-tilleggsstonader.utbetaling.v1-repartition
	helved.utbetalinger-ts.v1 --> tstuple-leftjoin-saker-repartition
	from-tilleggsstonader.utbetaling.v1-repartition --> tstuple-leftjoin-saker-repartition
	helved.utbetalinger-tp.v1 --> tptuple-leftjoin-saker-repartition
	historisk.utbetaling.v1 --> from-historisk.utbetaling.v1-repartition
	helved.utbetalinger-historisk.v1 --> historisktuple-leftjoin-saker-repartition
	from-historisk.utbetaling.v1-repartition --> historisktuple-leftjoin-saker-repartition
	helved.oppdrag.v1 --> pk-leftjoin-pending-repartition
    
    %% CUSTOM PROCESS STREAMS
    
end

%% COLORS
%% light    #dad9e0
%% purple   #78369f
%% pink     #c233b4
%% dark     #2a204a
%% blue     #07cff6

%% STYLES
style helved.pending-utbetalinger.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style ktable-helved.pending-utbetalinger.v1-repartition fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style pk-leftjoin-pending-repartition fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style helved.utbetalinger.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style helved.saker.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style ktable-helved.saker.v1-repartition fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style dptuple-leftjoin-saker-repartition fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style tstuple-leftjoin-saker-repartition fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style aaptuple-leftjoin-saker-repartition fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style historisktuple-leftjoin-saker-repartition fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style tptuple-leftjoin-saker-repartition fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style helved.status.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style helved.simuleringer.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style helved.oppdrag.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style helved.dryrun-aap.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style helved.dryrun-dp.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style helved.dryrun-ts.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style helved.dryrun-tp.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style teamdagpenger.utbetaling.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style from-teamdagpenger.utbetaling.v1-repartition fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style helved.utbetalinger-dp.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style aap.utbetaling.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style from-aap.utbetaling.v1-repartition fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style helved.utbetalinger-aap.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style tilleggsstonader.utbetaling.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style from-tilleggsstonader.utbetaling.v1-repartition fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style helved.utbetalinger-ts.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style helved.utbetalinger-tp.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style historisk.utbetaling.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style from-historisk.utbetaling.v1-repartition fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style helved.utbetalinger-historisk.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style helved.pending-utbetalinger.v1-state-store-v4 fill:#78369f, stroke:#2a204a, stroke-width:2px, color:#2a204a
style helved.saker.v1-state-store fill:#78369f, stroke:#2a204a, stroke-width:2px, color:#2a204a

