@startuml
!theme black-knight
queue "helved.utbetalinger.v1" <<topic>> as helved_utbetalinger_v1
queue "ktable-helved.pending-utbetalinger.v1-repartition" <<topic>> as ktable_helved_pending_utbetalinger_v1_repartition
queue "helved.pending-utbetalinger.v1" <<topic>> as helved_pending_utbetalinger_v1
queue "helved.retry-oppdrag.v1" <<topic>> as helved_retry_oppdrag_v1
queue "pk-leftjoin-pending-repartition" <<topic>> as pk_leftjoin_pending_repartition
queue "ktable-helved.saker.v1-repartition" <<topic>> as ktable_helved_saker_v1_repartition
queue "helved.saker.v1" <<topic>> as helved_saker_v1
queue "helved.status.v1" <<topic>> as helved_status_v1
queue "helved.oppdrag.v1" <<topic>> as helved_oppdrag_v1
queue "helved.dryrun-aap.v1" <<topic>> as helved_dryrun_aap_v1
queue "helved.dryrun-dp.v1" <<topic>> as helved_dryrun_dp_v1
queue "helved.dryrun-ts.v1" <<topic>> as helved_dryrun_ts_v1
queue "helved.dryrun-tp.v1" <<topic>> as helved_dryrun_tp_v1
queue "helved.simuleringer.v1" <<topic>> as helved_simuleringer_v1
queue "dptuple-leftjoin-saker-repartition" <<topic>> as dptuple_leftjoin_saker_repartition
queue "tstuple-leftjoin-saker-repartition" <<topic>> as tstuple_leftjoin_saker_repartition
queue "aaptuple-leftjoin-saker-repartition" <<topic>> as aaptuple_leftjoin_saker_repartition
queue "historisktuple-leftjoin-saker-repartition" <<topic>> as historisktuple_leftjoin_saker_repartition
queue "tptuple-leftjoin-saker-repartition" <<topic>> as tptuple_leftjoin_saker_repartition
queue "from-teamdagpenger.utbetaling.v1-repartition" <<topic>> as from_teamdagpenger_utbetaling_v1_repartition
queue "teamdagpenger.utbetaling.v1" <<topic>> as teamdagpenger_utbetaling_v1
queue "helved.utbetalinger-dp.v1" <<topic>> as helved_utbetalinger_dp_v1
queue "from-aap.utbetaling.v1-repartition" <<topic>> as from_aap_utbetaling_v1_repartition
queue "aap.utbetaling.v1" <<topic>> as aap_utbetaling_v1
queue "helved.utbetalinger-aap.v1" <<topic>> as helved_utbetalinger_aap_v1
queue "from-tilleggsstonader.utbetaling.v1-repartition" <<topic>> as from_tilleggsstonader_utbetaling_v1_repartition
queue "tilleggsstonader.utbetaling.v1" <<topic>> as tilleggsstonader_utbetaling_v1
queue "helved.utbetalinger-ts.v1" <<topic>> as helved_utbetalinger_ts_v1
queue "helved.utbetalinger-tp.v1" <<topic>> as helved_utbetalinger_tp_v1
queue "from-historisk.utbetaling.v1-repartition" <<topic>> as from_historisk_utbetaling_v1_repartition
queue "historisk.utbetaling.v1" <<topic>> as historisk_utbetaling_v1
queue "helved.utbetalinger-historisk.v1" <<topic>> as helved_utbetalinger_historisk_v1
package "Sub-topology: 0" {
	database "helved.utbetalinger.v1-state-store-v4" <<State Store>> as helved_utbetalinger_v1_state_store_v4
	helved_utbetalinger_v1 --> KSTREAM_SOURCE_0000000000
	helved_utbetalinger_v1_state_store_v4 -- KTABLE_SOURCE_0000000001
}
package "Sub-topology: 1" {
	agent "consume-helved.pending-utbetalinger.v1" <<Source>> as consume_helved_pending_utbetalinger_v1
	agent "KSTREAM-PROCESSOR-0000000003" <<Processor>> as KSTREAM_PROCESSOR_0000000003
	agent "KSTREAM-PROCESSOR-0000000004" <<Processor>> as KSTREAM_PROCESSOR_0000000004
	agent "ktable-helved.pending-utbetalinger.v1-repartition-filter" <<Processor>> as ktable_helved_pending_utbetalinger_v1_repartition_filter
	agent "ktable-helved.pending-utbetalinger.v1-repartition-sink" <<Sink>> as ktable_helved_pending_utbetalinger_v1_repartition_sink
	helved_pending_utbetalinger_v1 --> consume_helved_pending_utbetalinger_v1
	ktable_helved_pending_utbetalinger_v1_repartition <-- ktable_helved_pending_utbetalinger_v1_repartition_sink
	consume_helved_pending_utbetalinger_v1 --> KSTREAM_PROCESSOR_0000000003
	KSTREAM_PROCESSOR_0000000003 --> KSTREAM_PROCESSOR_0000000004
	KSTREAM_PROCESSOR_0000000004 --> ktable_helved_pending_utbetalinger_v1_repartition_filter
	ktable_helved_pending_utbetalinger_v1_repartition_filter --> ktable_helved_pending_utbetalinger_v1_repartition_sink
}
package "Sub-topology: 2" {
	database "helved.pending-utbetalinger.v1-state-store-v4" <<State Store>> as helved_pending_utbetalinger_v1_state_store_v4
	agent "pk-leftjoin-pending-repartition-source" <<Source>> as pk_leftjoin_pending_repartition_source
	agent "pk-leftjoin-pending" <<Processor>> as pk_leftjoin_pending
	agent "KSTREAM-BRANCH-0000000470" <<Processor>> as KSTREAM_BRANCH_0000000470
	agent "KSTREAM-BRANCH-00000004701" <<Processor>> as KSTREAM_BRANCH_00000004701
	agent "KSTREAM-PROCESSOR-0000000472" <<Processor>> as KSTREAM_PROCESSOR_0000000472
	agent "KSTREAM-PROCESSOR-0000000473" <<Processor>> as KSTREAM_PROCESSOR_0000000473
	agent "KSTREAM-BRANCH-00000004702" <<Processor>> as KSTREAM_BRANCH_00000004702
	agent "KSTREAM-PROCESSOR-0000000474" <<Processor>> as KSTREAM_PROCESSOR_0000000474
	agent "KSTREAM-MAP-0000000475" <<Processor>> as KSTREAM_MAP_0000000475
	agent "KSTREAM-MAPVALUES-0000000479" <<Processor>> as KSTREAM_MAPVALUES_0000000479
	agent "KSTREAM-BRANCH-00000004700" <<Processor>> as KSTREAM_BRANCH_00000004700
	agent "KSTREAM-PROCESSOR-0000000476" <<Processor>> as KSTREAM_PROCESSOR_0000000476
	agent "KSTREAM-PROCESSOR-0000000480" <<Processor>> as KSTREAM_PROCESSOR_0000000480
	agent "ktable-helved.pending-utbetalinger.v1-repartition-source" <<Source>> as ktable_helved_pending_utbetalinger_v1_repartition_source
	agent "KSTREAM-FOREACH-0000000483" <<Processor>> as KSTREAM_FOREACH_0000000483
	agent "KSTREAM-SINK-0000000477" <<Sink>> as KSTREAM_SINK_0000000477
	agent "KSTREAM-SINK-0000000481" <<Sink>> as KSTREAM_SINK_0000000481
	agent "ktable-helved.pending-utbetalinger.v1" <<Processor>> as ktable_helved_pending_utbetalinger_v1
	pk_leftjoin_pending_repartition --> pk_leftjoin_pending_repartition_source
	helved_pending_utbetalinger_v1_state_store_v4 -- pk_leftjoin_pending
	ktable_helved_pending_utbetalinger_v1_repartition --> ktable_helved_pending_utbetalinger_v1_repartition_source
	helved_retry_oppdrag_v1 <-- KSTREAM_SINK_0000000477
	helved_utbetalinger_v1 <-- KSTREAM_SINK_0000000481
	helved_pending_utbetalinger_v1_state_store_v4 -- ktable_helved_pending_utbetalinger_v1
	pk_leftjoin_pending_repartition_source --> pk_leftjoin_pending
	pk_leftjoin_pending --> KSTREAM_BRANCH_0000000470
	KSTREAM_BRANCH_0000000470 --> KSTREAM_BRANCH_00000004702
	KSTREAM_BRANCH_0000000470 --> KSTREAM_BRANCH_00000004700
	KSTREAM_BRANCH_0000000470 --> KSTREAM_BRANCH_00000004701
	KSTREAM_BRANCH_00000004701 --> KSTREAM_PROCESSOR_0000000472
	KSTREAM_PROCESSOR_0000000472 --> KSTREAM_PROCESSOR_0000000473
	KSTREAM_PROCESSOR_0000000473 --> KSTREAM_PROCESSOR_0000000474
	KSTREAM_BRANCH_00000004702 --> KSTREAM_MAPVALUES_0000000479
	KSTREAM_PROCESSOR_0000000474 --> KSTREAM_MAP_0000000475
	KSTREAM_MAP_0000000475 --> KSTREAM_PROCESSOR_0000000476
	KSTREAM_MAPVALUES_0000000479 --> KSTREAM_PROCESSOR_0000000480
	KSTREAM_BRANCH_00000004700 --> KSTREAM_FOREACH_0000000483
	KSTREAM_PROCESSOR_0000000476 --> KSTREAM_SINK_0000000477
	KSTREAM_PROCESSOR_0000000480 --> KSTREAM_SINK_0000000481
	ktable_helved_pending_utbetalinger_v1_repartition_source --> ktable_helved_pending_utbetalinger_v1
}
package "Sub-topology: 3" {
	agent "consume-helved.saker.v1" <<Source>> as consume_helved_saker_v1
	agent "KSTREAM-PROCESSOR-0000000010" <<Processor>> as KSTREAM_PROCESSOR_0000000010
	agent "KSTREAM-PROCESSOR-0000000011" <<Processor>> as KSTREAM_PROCESSOR_0000000011
	agent "ktable-helved.saker.v1-repartition-filter" <<Processor>> as ktable_helved_saker_v1_repartition_filter
	agent "ktable-helved.saker.v1-repartition-sink" <<Sink>> as ktable_helved_saker_v1_repartition_sink
	helved_saker_v1 --> consume_helved_saker_v1
	ktable_helved_saker_v1_repartition <-- ktable_helved_saker_v1_repartition_sink
	consume_helved_saker_v1 --> KSTREAM_PROCESSOR_0000000010
	KSTREAM_PROCESSOR_0000000010 --> KSTREAM_PROCESSOR_0000000011
	KSTREAM_PROCESSOR_0000000011 --> ktable_helved_saker_v1_repartition_filter
	ktable_helved_saker_v1_repartition_filter --> ktable_helved_saker_v1_repartition_sink
}
package "Sub-topology: 4" {
	database "helved.saker.v1-state-store" <<State Store>> as helved_saker_v1_state_store
	agent "dptuple-leftjoin-saker-repartition-source" <<Source>> as dptuple_leftjoin_saker_repartition_source
	agent "dptuple-leftjoin-saker" <<Processor>> as dptuple_leftjoin_saker
	agent "KSTREAM-PEEK-0000000032" <<Processor>> as KSTREAM_PEEK_0000000032
	agent "tstuple-leftjoin-saker-repartition-source" <<Source>> as tstuple_leftjoin_saker_repartition_source
	agent "KSTREAM-PROCESSOR-0000000033" <<Processor>> as KSTREAM_PROCESSOR_0000000033
	agent "tstuple-leftjoin-saker" <<Processor>> as tstuple_leftjoin_saker
	agent "KSTREAM-BRANCH-0000000034" <<Processor>> as KSTREAM_BRANCH_0000000034
	agent "KSTREAM-PEEK-0000000213" <<Processor>> as KSTREAM_PEEK_0000000213
	agent "KSTREAM-PROCESSOR-0000000214" <<Processor>> as KSTREAM_PROCESSOR_0000000214
	agent "KSTREAM-KEY-SELECT-0000000215" <<Processor>> as KSTREAM_KEY_SELECT_0000000215
	agent "KSTREAM-BRANCH-0000000216" <<Processor>> as KSTREAM_BRANCH_0000000216
	agent "aaptuple-leftjoin-saker-repartition-source" <<Source>> as aaptuple_leftjoin_saker_repartition_source
	agent "historisktuple-leftjoin-saker-repartition-source" <<Source>> as historisktuple_leftjoin_saker_repartition_source
	agent "tptuple-leftjoin-saker-repartition-source" <<Source>> as tptuple_leftjoin_saker_repartition_source
	agent "aaptuple-leftjoin-saker" <<Processor>> as aaptuple_leftjoin_saker
	agent "historisktuple-leftjoin-saker" <<Processor>> as historisktuple_leftjoin_saker
	agent "tptuple-leftjoin-saker" <<Processor>> as tptuple_leftjoin_saker
	agent "KSTREAM-PEEK-0000000126" <<Processor>> as KSTREAM_PEEK_0000000126
	agent "KSTREAM-PEEK-0000000298" <<Processor>> as KSTREAM_PEEK_0000000298
	agent "KSTREAM-PEEK-0000000385" <<Processor>> as KSTREAM_PEEK_0000000385
	agent "KSTREAM-BRANCH-00000000340" <<Processor>> as KSTREAM_BRANCH_00000000340
	agent "KSTREAM-PROCESSOR-0000000127" <<Processor>> as KSTREAM_PROCESSOR_0000000127
	agent "KSTREAM-PROCESSOR-0000000299" <<Processor>> as KSTREAM_PROCESSOR_0000000299
	agent "KSTREAM-PROCESSOR-0000000386" <<Processor>> as KSTREAM_PROCESSOR_0000000386
	agent "KSTREAM-MAPVALUES-0000000041" <<Processor>> as KSTREAM_MAPVALUES_0000000041
	agent "KSTREAM-MAPVALUES-0000000128" <<Processor>> as KSTREAM_MAPVALUES_0000000128
	agent "KSTREAM-MAPVALUES-0000000300" <<Processor>> as KSTREAM_MAPVALUES_0000000300
	agent "KSTREAM-MAPVALUES-0000000387" <<Processor>> as KSTREAM_MAPVALUES_0000000387
	agent "KSTREAM-BRANCH-00000002160" <<Processor>> as KSTREAM_BRANCH_00000002160
	agent "KSTREAM-KEY-SELECT-0000000042" <<Processor>> as KSTREAM_KEY_SELECT_0000000042
	agent "KSTREAM-KEY-SELECT-0000000129" <<Processor>> as KSTREAM_KEY_SELECT_0000000129
	agent "KSTREAM-KEY-SELECT-0000000301" <<Processor>> as KSTREAM_KEY_SELECT_0000000301
	agent "KSTREAM-KEY-SELECT-0000000388" <<Processor>> as KSTREAM_KEY_SELECT_0000000388
	agent "KSTREAM-MAPVALUES-0000000043" <<Processor>> as KSTREAM_MAPVALUES_0000000043
	agent "KSTREAM-MAPVALUES-0000000130" <<Processor>> as KSTREAM_MAPVALUES_0000000130
	agent "KSTREAM-MAPVALUES-0000000222" <<Processor>> as KSTREAM_MAPVALUES_0000000222
	agent "KSTREAM-MAPVALUES-0000000302" <<Processor>> as KSTREAM_MAPVALUES_0000000302
	agent "KSTREAM-MAPVALUES-0000000389" <<Processor>> as KSTREAM_MAPVALUES_0000000389
	agent "KSTREAM-BRANCH-0000000044" <<Processor>> as KSTREAM_BRANCH_0000000044
	agent "KSTREAM-BRANCH-0000000131" <<Processor>> as KSTREAM_BRANCH_0000000131
	agent "KSTREAM-BRANCH-0000000223" <<Processor>> as KSTREAM_BRANCH_0000000223
	agent "KSTREAM-BRANCH-0000000303" <<Processor>> as KSTREAM_BRANCH_0000000303
	agent "KSTREAM-BRANCH-0000000390" <<Processor>> as KSTREAM_BRANCH_0000000390
	agent "KSTREAM-BRANCH-00000000443" <<Processor>> as KSTREAM_BRANCH_00000000443
	agent "KSTREAM-BRANCH-00000001313" <<Processor>> as KSTREAM_BRANCH_00000001313
	agent "KSTREAM-BRANCH-00000002233" <<Processor>> as KSTREAM_BRANCH_00000002233
	agent "KSTREAM-BRANCH-00000003033" <<Processor>> as KSTREAM_BRANCH_00000003033
	agent "KSTREAM-BRANCH-00000003903" <<Processor>> as KSTREAM_BRANCH_00000003903
	agent "KSTREAM-MAPVALUES-0000000054" <<Processor>> as KSTREAM_MAPVALUES_0000000054
	agent "KSTREAM-MAPVALUES-0000000141" <<Processor>> as KSTREAM_MAPVALUES_0000000141
	agent "KSTREAM-MAPVALUES-0000000233" <<Processor>> as KSTREAM_MAPVALUES_0000000233
	agent "KSTREAM-MAPVALUES-0000000313" <<Processor>> as KSTREAM_MAPVALUES_0000000313
	agent "KSTREAM-MAPVALUES-0000000400" <<Processor>> as KSTREAM_MAPVALUES_0000000400
	agent "KSTREAM-BRANCH-00000000444" <<Processor>> as KSTREAM_BRANCH_00000000444
	agent "KSTREAM-BRANCH-00000001314" <<Processor>> as KSTREAM_BRANCH_00000001314
	agent "KSTREAM-BRANCH-00000002234" <<Processor>> as KSTREAM_BRANCH_00000002234
	agent "KSTREAM-BRANCH-00000003034" <<Processor>> as KSTREAM_BRANCH_00000003034
	agent "KSTREAM-BRANCH-00000003904" <<Processor>> as KSTREAM_BRANCH_00000003904
	agent "KSTREAM-MAPVALUES-0000000087" <<Processor>> as KSTREAM_MAPVALUES_0000000087
	agent "KSTREAM-MAPVALUES-0000000174" <<Processor>> as KSTREAM_MAPVALUES_0000000174
	agent "KSTREAM-MAPVALUES-0000000266" <<Processor>> as KSTREAM_MAPVALUES_0000000266
	agent "KSTREAM-MAPVALUES-0000000346" <<Processor>> as KSTREAM_MAPVALUES_0000000346
	agent "KSTREAM-MAPVALUES-0000000433" <<Processor>> as KSTREAM_MAPVALUES_0000000433
	agent "KSTREAM-FILTER-0000000095" <<Processor>> as KSTREAM_FILTER_0000000095
	agent "KSTREAM-FILTER-0000000182" <<Processor>> as KSTREAM_FILTER_0000000182
	agent "KSTREAM-FILTER-0000000274" <<Processor>> as KSTREAM_FILTER_0000000274
	agent "KSTREAM-FILTER-0000000354" <<Processor>> as KSTREAM_FILTER_0000000354
	agent "KSTREAM-FILTER-0000000441" <<Processor>> as KSTREAM_FILTER_0000000441
	agent "KSTREAM-MAPVALUES-0000000072" <<Processor>> as KSTREAM_MAPVALUES_0000000072
	agent "KSTREAM-MAPVALUES-0000000096" <<Processor>> as KSTREAM_MAPVALUES_0000000096
	agent "KSTREAM-MAPVALUES-0000000159" <<Processor>> as KSTREAM_MAPVALUES_0000000159
	agent "KSTREAM-MAPVALUES-0000000183" <<Processor>> as KSTREAM_MAPVALUES_0000000183
	agent "KSTREAM-MAPVALUES-0000000251" <<Processor>> as KSTREAM_MAPVALUES_0000000251
	agent "KSTREAM-MAPVALUES-0000000275" <<Processor>> as KSTREAM_MAPVALUES_0000000275
	agent "KSTREAM-MAPVALUES-0000000331" <<Processor>> as KSTREAM_MAPVALUES_0000000331
	agent "KSTREAM-MAPVALUES-0000000355" <<Processor>> as KSTREAM_MAPVALUES_0000000355
	agent "KSTREAM-MAPVALUES-0000000418" <<Processor>> as KSTREAM_MAPVALUES_0000000418
	agent "KSTREAM-MAPVALUES-0000000442" <<Processor>> as KSTREAM_MAPVALUES_0000000442
	agent "KSTREAM-BRANCH-0000000073" <<Processor>> as KSTREAM_BRANCH_0000000073
	agent "KSTREAM-BRANCH-0000000097" <<Processor>> as KSTREAM_BRANCH_0000000097
	agent "KSTREAM-BRANCH-0000000160" <<Processor>> as KSTREAM_BRANCH_0000000160
	agent "KSTREAM-BRANCH-0000000184" <<Processor>> as KSTREAM_BRANCH_0000000184
	agent "KSTREAM-BRANCH-0000000252" <<Processor>> as KSTREAM_BRANCH_0000000252
	agent "KSTREAM-BRANCH-0000000276" <<Processor>> as KSTREAM_BRANCH_0000000276
	agent "KSTREAM-BRANCH-0000000332" <<Processor>> as KSTREAM_BRANCH_0000000332
	agent "KSTREAM-BRANCH-0000000356" <<Processor>> as KSTREAM_BRANCH_0000000356
	agent "KSTREAM-BRANCH-0000000419" <<Processor>> as KSTREAM_BRANCH_0000000419
	agent "KSTREAM-BRANCH-0000000443" <<Processor>> as KSTREAM_BRANCH_0000000443
	agent "KSTREAM-FLATMAPVALUES-0000000060" <<Processor>> as KSTREAM_FLATMAPVALUES_0000000060
	agent "KSTREAM-FLATMAPVALUES-0000000147" <<Processor>> as KSTREAM_FLATMAPVALUES_0000000147
	agent "KSTREAM-FLATMAPVALUES-0000000239" <<Processor>> as KSTREAM_FLATMAPVALUES_0000000239
	agent "KSTREAM-FLATMAPVALUES-0000000319" <<Processor>> as KSTREAM_FLATMAPVALUES_0000000319
	agent "KSTREAM-FLATMAPVALUES-0000000406" <<Processor>> as KSTREAM_FLATMAPVALUES_0000000406
	agent "KSTREAM-PROCESSOR-0000000061" <<Processor>> as KSTREAM_PROCESSOR_0000000061
	agent "KSTREAM-PROCESSOR-0000000148" <<Processor>> as KSTREAM_PROCESSOR_0000000148
	agent "KSTREAM-PROCESSOR-0000000240" <<Processor>> as KSTREAM_PROCESSOR_0000000240
	agent "KSTREAM-PROCESSOR-0000000320" <<Processor>> as KSTREAM_PROCESSOR_0000000320
	agent "KSTREAM-PROCESSOR-0000000407" <<Processor>> as KSTREAM_PROCESSOR_0000000407
	agent "KSTREAM-MAPVALUES-0000000062" <<Processor>> as KSTREAM_MAPVALUES_0000000062
	agent "KSTREAM-MAPVALUES-0000000149" <<Processor>> as KSTREAM_MAPVALUES_0000000149
	agent "KSTREAM-MAPVALUES-0000000241" <<Processor>> as KSTREAM_MAPVALUES_0000000241
	agent "KSTREAM-MAPVALUES-0000000321" <<Processor>> as KSTREAM_MAPVALUES_0000000321
	agent "KSTREAM-MAPVALUES-0000000408" <<Processor>> as KSTREAM_MAPVALUES_0000000408
	agent "KSTREAM-BRANCH-00000000341" <<Processor>> as KSTREAM_BRANCH_00000000341
	agent "KSTREAM-FLATMAPVALUES-0000000055" <<Processor>> as KSTREAM_FLATMAPVALUES_0000000055
	agent "KSTREAM-FLATMAPVALUES-0000000142" <<Processor>> as KSTREAM_FLATMAPVALUES_0000000142
	agent "KSTREAM-FLATMAPVALUES-0000000234" <<Processor>> as KSTREAM_FLATMAPVALUES_0000000234
	agent "KSTREAM-FLATMAPVALUES-0000000314" <<Processor>> as KSTREAM_FLATMAPVALUES_0000000314
	agent "KSTREAM-FLATMAPVALUES-0000000401" <<Processor>> as KSTREAM_FLATMAPVALUES_0000000401
	agent "KSTREAM-BRANCH-00000000441" <<Processor>> as KSTREAM_BRANCH_00000000441
	agent "KSTREAM-BRANCH-00000000442" <<Processor>> as KSTREAM_BRANCH_00000000442
	agent "KSTREAM-BRANCH-00000001311" <<Processor>> as KSTREAM_BRANCH_00000001311
	agent "KSTREAM-BRANCH-00000001312" <<Processor>> as KSTREAM_BRANCH_00000001312
	agent "KSTREAM-BRANCH-00000002161" <<Processor>> as KSTREAM_BRANCH_00000002161
	agent "KSTREAM-BRANCH-00000002231" <<Processor>> as KSTREAM_BRANCH_00000002231
	agent "KSTREAM-BRANCH-00000002232" <<Processor>> as KSTREAM_BRANCH_00000002232
	agent "KSTREAM-BRANCH-00000003031" <<Processor>> as KSTREAM_BRANCH_00000003031
	agent "KSTREAM-BRANCH-00000003032" <<Processor>> as KSTREAM_BRANCH_00000003032
	agent "KSTREAM-BRANCH-00000003901" <<Processor>> as KSTREAM_BRANCH_00000003901
	agent "KSTREAM-BRANCH-00000003902" <<Processor>> as KSTREAM_BRANCH_00000003902
	agent "KSTREAM-FILTER-0000000068" <<Processor>> as KSTREAM_FILTER_0000000068
	agent "KSTREAM-FILTER-0000000091" <<Processor>> as KSTREAM_FILTER_0000000091
	agent "KSTREAM-FILTER-0000000155" <<Processor>> as KSTREAM_FILTER_0000000155
	agent "KSTREAM-FILTER-0000000178" <<Processor>> as KSTREAM_FILTER_0000000178
	agent "KSTREAM-FILTER-0000000247" <<Processor>> as KSTREAM_FILTER_0000000247
	agent "KSTREAM-FILTER-0000000270" <<Processor>> as KSTREAM_FILTER_0000000270
	agent "KSTREAM-FILTER-0000000327" <<Processor>> as KSTREAM_FILTER_0000000327
	agent "KSTREAM-FILTER-0000000350" <<Processor>> as KSTREAM_FILTER_0000000350
	agent "KSTREAM-FILTER-0000000414" <<Processor>> as KSTREAM_FILTER_0000000414
	agent "KSTREAM-FILTER-0000000437" <<Processor>> as KSTREAM_FILTER_0000000437
	agent "KSTREAM-KEY-SELECT-0000000036" <<Processor>> as KSTREAM_KEY_SELECT_0000000036
	agent "KSTREAM-PROCESSOR-0000000056" <<Processor>> as KSTREAM_PROCESSOR_0000000056
	agent "KSTREAM-PROCESSOR-0000000143" <<Processor>> as KSTREAM_PROCESSOR_0000000143
	agent "KSTREAM-PROCESSOR-0000000235" <<Processor>> as KSTREAM_PROCESSOR_0000000235
	agent "KSTREAM-PROCESSOR-0000000315" <<Processor>> as KSTREAM_PROCESSOR_0000000315
	agent "KSTREAM-PROCESSOR-0000000402" <<Processor>> as KSTREAM_PROCESSOR_0000000402
	agent "KSTREAM-BRANCH-00000000731" <<Processor>> as KSTREAM_BRANCH_00000000731
	agent "KSTREAM-BRANCH-00000000732" <<Processor>> as KSTREAM_BRANCH_00000000732
	agent "KSTREAM-BRANCH-00000000733" <<Processor>> as KSTREAM_BRANCH_00000000733
	agent "KSTREAM-BRANCH-00000000734" <<Processor>> as KSTREAM_BRANCH_00000000734
	agent "KSTREAM-BRANCH-00000000971" <<Processor>> as KSTREAM_BRANCH_00000000971
	agent "KSTREAM-BRANCH-00000000972" <<Processor>> as KSTREAM_BRANCH_00000000972
	agent "KSTREAM-BRANCH-00000000973" <<Processor>> as KSTREAM_BRANCH_00000000973
	agent "KSTREAM-BRANCH-00000000974" <<Processor>> as KSTREAM_BRANCH_00000000974
	agent "KSTREAM-BRANCH-00000001601" <<Processor>> as KSTREAM_BRANCH_00000001601
	agent "KSTREAM-BRANCH-00000001602" <<Processor>> as KSTREAM_BRANCH_00000001602
	agent "KSTREAM-BRANCH-00000001603" <<Processor>> as KSTREAM_BRANCH_00000001603
	agent "KSTREAM-BRANCH-00000001604" <<Processor>> as KSTREAM_BRANCH_00000001604
	agent "KSTREAM-BRANCH-00000001841" <<Processor>> as KSTREAM_BRANCH_00000001841
	agent "KSTREAM-BRANCH-00000001842" <<Processor>> as KSTREAM_BRANCH_00000001842
	agent "KSTREAM-BRANCH-00000001843" <<Processor>> as KSTREAM_BRANCH_00000001843
	agent "KSTREAM-BRANCH-00000001844" <<Processor>> as KSTREAM_BRANCH_00000001844
	agent "KSTREAM-BRANCH-00000002521" <<Processor>> as KSTREAM_BRANCH_00000002521
	agent "KSTREAM-BRANCH-00000002522" <<Processor>> as KSTREAM_BRANCH_00000002522
	agent "KSTREAM-BRANCH-00000002523" <<Processor>> as KSTREAM_BRANCH_00000002523
	agent "KSTREAM-BRANCH-00000002524" <<Processor>> as KSTREAM_BRANCH_00000002524
	agent "KSTREAM-BRANCH-00000002761" <<Processor>> as KSTREAM_BRANCH_00000002761
	agent "KSTREAM-BRANCH-00000002762" <<Processor>> as KSTREAM_BRANCH_00000002762
	agent "KSTREAM-BRANCH-00000002763" <<Processor>> as KSTREAM_BRANCH_00000002763
	agent "KSTREAM-BRANCH-00000002764" <<Processor>> as KSTREAM_BRANCH_00000002764
	agent "KSTREAM-BRANCH-00000003321" <<Processor>> as KSTREAM_BRANCH_00000003321
	agent "KSTREAM-BRANCH-00000003322" <<Processor>> as KSTREAM_BRANCH_00000003322
	agent "KSTREAM-BRANCH-00000003323" <<Processor>> as KSTREAM_BRANCH_00000003323
	agent "KSTREAM-BRANCH-00000003324" <<Processor>> as KSTREAM_BRANCH_00000003324
	agent "KSTREAM-BRANCH-00000003561" <<Processor>> as KSTREAM_BRANCH_00000003561
	agent "KSTREAM-BRANCH-00000003562" <<Processor>> as KSTREAM_BRANCH_00000003562
	agent "KSTREAM-BRANCH-00000003563" <<Processor>> as KSTREAM_BRANCH_00000003563
	agent "KSTREAM-BRANCH-00000003564" <<Processor>> as KSTREAM_BRANCH_00000003564
	agent "KSTREAM-BRANCH-00000004191" <<Processor>> as KSTREAM_BRANCH_00000004191
	agent "KSTREAM-BRANCH-00000004192" <<Processor>> as KSTREAM_BRANCH_00000004192
	agent "KSTREAM-BRANCH-00000004193" <<Processor>> as KSTREAM_BRANCH_00000004193
	agent "KSTREAM-BRANCH-00000004194" <<Processor>> as KSTREAM_BRANCH_00000004194
	agent "KSTREAM-BRANCH-00000004431" <<Processor>> as KSTREAM_BRANCH_00000004431
	agent "KSTREAM-BRANCH-00000004432" <<Processor>> as KSTREAM_BRANCH_00000004432
	agent "KSTREAM-BRANCH-00000004433" <<Processor>> as KSTREAM_BRANCH_00000004433
	agent "KSTREAM-BRANCH-00000004434" <<Processor>> as KSTREAM_BRANCH_00000004434
	agent "KSTREAM-FLATMAP-0000000057" <<Processor>> as KSTREAM_FLATMAP_0000000057
	agent "KSTREAM-FLATMAP-0000000144" <<Processor>> as KSTREAM_FLATMAP_0000000144
	agent "KSTREAM-FLATMAP-0000000236" <<Processor>> as KSTREAM_FLATMAP_0000000236
	agent "KSTREAM-FLATMAP-0000000316" <<Processor>> as KSTREAM_FLATMAP_0000000316
	agent "KSTREAM-FLATMAP-0000000403" <<Processor>> as KSTREAM_FLATMAP_0000000403
	agent "KSTREAM-FLATMAPVALUES-0000000088" <<Processor>> as KSTREAM_FLATMAPVALUES_0000000088
	agent "KSTREAM-FLATMAPVALUES-0000000175" <<Processor>> as KSTREAM_FLATMAPVALUES_0000000175
	agent "KSTREAM-FLATMAPVALUES-0000000267" <<Processor>> as KSTREAM_FLATMAPVALUES_0000000267
	agent "KSTREAM-FLATMAPVALUES-0000000347" <<Processor>> as KSTREAM_FLATMAPVALUES_0000000347
	agent "KSTREAM-FLATMAPVALUES-0000000434" <<Processor>> as KSTREAM_FLATMAPVALUES_0000000434
	agent "KSTREAM-MAPVALUES-0000000037" <<Processor>> as KSTREAM_MAPVALUES_0000000037
	agent "KSTREAM-MAPVALUES-0000000046" <<Processor>> as KSTREAM_MAPVALUES_0000000046
	agent "KSTREAM-MAPVALUES-0000000050" <<Processor>> as KSTREAM_MAPVALUES_0000000050
	agent "KSTREAM-MAPVALUES-0000000065" <<Processor>> as KSTREAM_MAPVALUES_0000000065
	agent "KSTREAM-MAPVALUES-0000000069" <<Processor>> as KSTREAM_MAPVALUES_0000000069
	agent "KSTREAM-MAPVALUES-0000000092" <<Processor>> as KSTREAM_MAPVALUES_0000000092
	agent "KSTREAM-MAPVALUES-0000000133" <<Processor>> as KSTREAM_MAPVALUES_0000000133
	agent "KSTREAM-MAPVALUES-0000000137" <<Processor>> as KSTREAM_MAPVALUES_0000000137
	agent "KSTREAM-MAPVALUES-0000000152" <<Processor>> as KSTREAM_MAPVALUES_0000000152
	agent "KSTREAM-MAPVALUES-0000000156" <<Processor>> as KSTREAM_MAPVALUES_0000000156
	agent "KSTREAM-MAPVALUES-0000000179" <<Processor>> as KSTREAM_MAPVALUES_0000000179
	agent "KSTREAM-MAPVALUES-0000000218" <<Processor>> as KSTREAM_MAPVALUES_0000000218
	agent "KSTREAM-MAPVALUES-0000000225" <<Processor>> as KSTREAM_MAPVALUES_0000000225
	agent "KSTREAM-MAPVALUES-0000000229" <<Processor>> as KSTREAM_MAPVALUES_0000000229
	agent "KSTREAM-MAPVALUES-0000000244" <<Processor>> as KSTREAM_MAPVALUES_0000000244
	agent "KSTREAM-MAPVALUES-0000000248" <<Processor>> as KSTREAM_MAPVALUES_0000000248
	agent "KSTREAM-MAPVALUES-0000000271" <<Processor>> as KSTREAM_MAPVALUES_0000000271
	agent "KSTREAM-MAPVALUES-0000000305" <<Processor>> as KSTREAM_MAPVALUES_0000000305
	agent "KSTREAM-MAPVALUES-0000000309" <<Processor>> as KSTREAM_MAPVALUES_0000000309
	agent "KSTREAM-MAPVALUES-0000000324" <<Processor>> as KSTREAM_MAPVALUES_0000000324
	agent "KSTREAM-MAPVALUES-0000000328" <<Processor>> as KSTREAM_MAPVALUES_0000000328
	agent "KSTREAM-MAPVALUES-0000000351" <<Processor>> as KSTREAM_MAPVALUES_0000000351
	agent "KSTREAM-MAPVALUES-0000000392" <<Processor>> as KSTREAM_MAPVALUES_0000000392
	agent "KSTREAM-MAPVALUES-0000000396" <<Processor>> as KSTREAM_MAPVALUES_0000000396
	agent "KSTREAM-MAPVALUES-0000000411" <<Processor>> as KSTREAM_MAPVALUES_0000000411
	agent "KSTREAM-MAPVALUES-0000000415" <<Processor>> as KSTREAM_MAPVALUES_0000000415
	agent "KSTREAM-MAPVALUES-0000000438" <<Processor>> as KSTREAM_MAPVALUES_0000000438
	agent "KSTREAM-PROCESSOR-0000000038" <<Processor>> as KSTREAM_PROCESSOR_0000000038
	agent "KSTREAM-PROCESSOR-0000000047" <<Processor>> as KSTREAM_PROCESSOR_0000000047
	agent "KSTREAM-PROCESSOR-0000000051" <<Processor>> as KSTREAM_PROCESSOR_0000000051
	agent "KSTREAM-PROCESSOR-0000000058" <<Processor>> as KSTREAM_PROCESSOR_0000000058
	agent "KSTREAM-PROCESSOR-0000000063" <<Processor>> as KSTREAM_PROCESSOR_0000000063
	agent "KSTREAM-PROCESSOR-0000000066" <<Processor>> as KSTREAM_PROCESSOR_0000000066
	agent "KSTREAM-PROCESSOR-0000000070" <<Processor>> as KSTREAM_PROCESSOR_0000000070
	agent "KSTREAM-PROCESSOR-0000000075" <<Processor>> as KSTREAM_PROCESSOR_0000000075
	agent "KSTREAM-PROCESSOR-0000000078" <<Processor>> as KSTREAM_PROCESSOR_0000000078
	agent "KSTREAM-PROCESSOR-0000000081" <<Processor>> as KSTREAM_PROCESSOR_0000000081
	agent "KSTREAM-PROCESSOR-0000000084" <<Processor>> as KSTREAM_PROCESSOR_0000000084
	agent "KSTREAM-PROCESSOR-0000000089" <<Processor>> as KSTREAM_PROCESSOR_0000000089
	agent "KSTREAM-PROCESSOR-0000000093" <<Processor>> as KSTREAM_PROCESSOR_0000000093
	agent "KSTREAM-PROCESSOR-0000000099" <<Processor>> as KSTREAM_PROCESSOR_0000000099
	agent "KSTREAM-PROCESSOR-0000000102" <<Processor>> as KSTREAM_PROCESSOR_0000000102
	agent "KSTREAM-PROCESSOR-0000000105" <<Processor>> as KSTREAM_PROCESSOR_0000000105
	agent "KSTREAM-PROCESSOR-0000000108" <<Processor>> as KSTREAM_PROCESSOR_0000000108
	agent "KSTREAM-PROCESSOR-0000000134" <<Processor>> as KSTREAM_PROCESSOR_0000000134
	agent "KSTREAM-PROCESSOR-0000000138" <<Processor>> as KSTREAM_PROCESSOR_0000000138
	agent "KSTREAM-PROCESSOR-0000000145" <<Processor>> as KSTREAM_PROCESSOR_0000000145
	agent "KSTREAM-PROCESSOR-0000000150" <<Processor>> as KSTREAM_PROCESSOR_0000000150
	agent "KSTREAM-PROCESSOR-0000000153" <<Processor>> as KSTREAM_PROCESSOR_0000000153
	agent "KSTREAM-PROCESSOR-0000000157" <<Processor>> as KSTREAM_PROCESSOR_0000000157
	agent "KSTREAM-PROCESSOR-0000000162" <<Processor>> as KSTREAM_PROCESSOR_0000000162
	agent "KSTREAM-PROCESSOR-0000000165" <<Processor>> as KSTREAM_PROCESSOR_0000000165
	agent "KSTREAM-PROCESSOR-0000000168" <<Processor>> as KSTREAM_PROCESSOR_0000000168
	agent "KSTREAM-PROCESSOR-0000000171" <<Processor>> as KSTREAM_PROCESSOR_0000000171
	agent "KSTREAM-PROCESSOR-0000000176" <<Processor>> as KSTREAM_PROCESSOR_0000000176
	agent "KSTREAM-PROCESSOR-0000000180" <<Processor>> as KSTREAM_PROCESSOR_0000000180
	agent "KSTREAM-PROCESSOR-0000000186" <<Processor>> as KSTREAM_PROCESSOR_0000000186
	agent "KSTREAM-PROCESSOR-0000000189" <<Processor>> as KSTREAM_PROCESSOR_0000000189
	agent "KSTREAM-PROCESSOR-0000000192" <<Processor>> as KSTREAM_PROCESSOR_0000000192
	agent "KSTREAM-PROCESSOR-0000000195" <<Processor>> as KSTREAM_PROCESSOR_0000000195
	agent "KSTREAM-PROCESSOR-0000000219" <<Processor>> as KSTREAM_PROCESSOR_0000000219
	agent "KSTREAM-PROCESSOR-0000000226" <<Processor>> as KSTREAM_PROCESSOR_0000000226
	agent "KSTREAM-PROCESSOR-0000000230" <<Processor>> as KSTREAM_PROCESSOR_0000000230
	agent "KSTREAM-PROCESSOR-0000000237" <<Processor>> as KSTREAM_PROCESSOR_0000000237
	agent "KSTREAM-PROCESSOR-0000000242" <<Processor>> as KSTREAM_PROCESSOR_0000000242
	agent "KSTREAM-PROCESSOR-0000000245" <<Processor>> as KSTREAM_PROCESSOR_0000000245
	agent "KSTREAM-PROCESSOR-0000000249" <<Processor>> as KSTREAM_PROCESSOR_0000000249
	agent "KSTREAM-PROCESSOR-0000000254" <<Processor>> as KSTREAM_PROCESSOR_0000000254
	agent "KSTREAM-PROCESSOR-0000000257" <<Processor>> as KSTREAM_PROCESSOR_0000000257
	agent "KSTREAM-PROCESSOR-0000000260" <<Processor>> as KSTREAM_PROCESSOR_0000000260
	agent "KSTREAM-PROCESSOR-0000000263" <<Processor>> as KSTREAM_PROCESSOR_0000000263
	agent "KSTREAM-PROCESSOR-0000000268" <<Processor>> as KSTREAM_PROCESSOR_0000000268
	agent "KSTREAM-PROCESSOR-0000000272" <<Processor>> as KSTREAM_PROCESSOR_0000000272
	agent "KSTREAM-PROCESSOR-0000000278" <<Processor>> as KSTREAM_PROCESSOR_0000000278
	agent "KSTREAM-PROCESSOR-0000000281" <<Processor>> as KSTREAM_PROCESSOR_0000000281
	agent "KSTREAM-PROCESSOR-0000000284" <<Processor>> as KSTREAM_PROCESSOR_0000000284
	agent "KSTREAM-PROCESSOR-0000000287" <<Processor>> as KSTREAM_PROCESSOR_0000000287
	agent "KSTREAM-PROCESSOR-0000000306" <<Processor>> as KSTREAM_PROCESSOR_0000000306
	agent "KSTREAM-PROCESSOR-0000000310" <<Processor>> as KSTREAM_PROCESSOR_0000000310
	agent "KSTREAM-PROCESSOR-0000000317" <<Processor>> as KSTREAM_PROCESSOR_0000000317
	agent "KSTREAM-PROCESSOR-0000000322" <<Processor>> as KSTREAM_PROCESSOR_0000000322
	agent "KSTREAM-PROCESSOR-0000000325" <<Processor>> as KSTREAM_PROCESSOR_0000000325
	agent "KSTREAM-PROCESSOR-0000000329" <<Processor>> as KSTREAM_PROCESSOR_0000000329
	agent "KSTREAM-PROCESSOR-0000000334" <<Processor>> as KSTREAM_PROCESSOR_0000000334
	agent "KSTREAM-PROCESSOR-0000000337" <<Processor>> as KSTREAM_PROCESSOR_0000000337
	agent "KSTREAM-PROCESSOR-0000000340" <<Processor>> as KSTREAM_PROCESSOR_0000000340
	agent "KSTREAM-PROCESSOR-0000000343" <<Processor>> as KSTREAM_PROCESSOR_0000000343
	agent "KSTREAM-PROCESSOR-0000000348" <<Processor>> as KSTREAM_PROCESSOR_0000000348
	agent "KSTREAM-PROCESSOR-0000000352" <<Processor>> as KSTREAM_PROCESSOR_0000000352
	agent "KSTREAM-PROCESSOR-0000000358" <<Processor>> as KSTREAM_PROCESSOR_0000000358
	agent "KSTREAM-PROCESSOR-0000000361" <<Processor>> as KSTREAM_PROCESSOR_0000000361
	agent "KSTREAM-PROCESSOR-0000000364" <<Processor>> as KSTREAM_PROCESSOR_0000000364
	agent "KSTREAM-PROCESSOR-0000000367" <<Processor>> as KSTREAM_PROCESSOR_0000000367
	agent "KSTREAM-PROCESSOR-0000000393" <<Processor>> as KSTREAM_PROCESSOR_0000000393
	agent "KSTREAM-PROCESSOR-0000000397" <<Processor>> as KSTREAM_PROCESSOR_0000000397
	agent "KSTREAM-PROCESSOR-0000000404" <<Processor>> as KSTREAM_PROCESSOR_0000000404
	agent "KSTREAM-PROCESSOR-0000000409" <<Processor>> as KSTREAM_PROCESSOR_0000000409
	agent "KSTREAM-PROCESSOR-0000000412" <<Processor>> as KSTREAM_PROCESSOR_0000000412
	agent "KSTREAM-PROCESSOR-0000000416" <<Processor>> as KSTREAM_PROCESSOR_0000000416
	agent "KSTREAM-PROCESSOR-0000000421" <<Processor>> as KSTREAM_PROCESSOR_0000000421
	agent "KSTREAM-PROCESSOR-0000000424" <<Processor>> as KSTREAM_PROCESSOR_0000000424
	agent "KSTREAM-PROCESSOR-0000000427" <<Processor>> as KSTREAM_PROCESSOR_0000000427
	agent "KSTREAM-PROCESSOR-0000000430" <<Processor>> as KSTREAM_PROCESSOR_0000000430
	agent "KSTREAM-PROCESSOR-0000000435" <<Processor>> as KSTREAM_PROCESSOR_0000000435
	agent "KSTREAM-PROCESSOR-0000000439" <<Processor>> as KSTREAM_PROCESSOR_0000000439
	agent "KSTREAM-PROCESSOR-0000000445" <<Processor>> as KSTREAM_PROCESSOR_0000000445
	agent "KSTREAM-PROCESSOR-0000000448" <<Processor>> as KSTREAM_PROCESSOR_0000000448
	agent "KSTREAM-PROCESSOR-0000000451" <<Processor>> as KSTREAM_PROCESSOR_0000000451
	agent "KSTREAM-PROCESSOR-0000000454" <<Processor>> as KSTREAM_PROCESSOR_0000000454
	agent "ktable-helved.saker.v1-repartition-source" <<Source>> as ktable_helved_saker_v1_repartition_source
	agent "KSTREAM-SINK-0000000039" <<Sink>> as KSTREAM_SINK_0000000039
	agent "KSTREAM-SINK-0000000048" <<Sink>> as KSTREAM_SINK_0000000048
	agent "KSTREAM-SINK-0000000052" <<Sink>> as KSTREAM_SINK_0000000052
	agent "KSTREAM-SINK-0000000059" <<Sink>> as KSTREAM_SINK_0000000059
	agent "KSTREAM-SINK-0000000064" <<Sink>> as KSTREAM_SINK_0000000064
	agent "KSTREAM-SINK-0000000067" <<Sink>> as KSTREAM_SINK_0000000067
	agent "KSTREAM-SINK-0000000071" <<Sink>> as KSTREAM_SINK_0000000071
	agent "KSTREAM-SINK-0000000076" <<Sink>> as KSTREAM_SINK_0000000076
	agent "KSTREAM-SINK-0000000079" <<Sink>> as KSTREAM_SINK_0000000079
	agent "KSTREAM-SINK-0000000082" <<Sink>> as KSTREAM_SINK_0000000082
	agent "KSTREAM-SINK-0000000085" <<Sink>> as KSTREAM_SINK_0000000085
	agent "KSTREAM-SINK-0000000090" <<Sink>> as KSTREAM_SINK_0000000090
	agent "KSTREAM-SINK-0000000094" <<Sink>> as KSTREAM_SINK_0000000094
	agent "KSTREAM-SINK-0000000100" <<Sink>> as KSTREAM_SINK_0000000100
	agent "KSTREAM-SINK-0000000103" <<Sink>> as KSTREAM_SINK_0000000103
	agent "KSTREAM-SINK-0000000106" <<Sink>> as KSTREAM_SINK_0000000106
	agent "KSTREAM-SINK-0000000109" <<Sink>> as KSTREAM_SINK_0000000109
	agent "KSTREAM-SINK-0000000135" <<Sink>> as KSTREAM_SINK_0000000135
	agent "KSTREAM-SINK-0000000139" <<Sink>> as KSTREAM_SINK_0000000139
	agent "KSTREAM-SINK-0000000146" <<Sink>> as KSTREAM_SINK_0000000146
	agent "KSTREAM-SINK-0000000151" <<Sink>> as KSTREAM_SINK_0000000151
	agent "KSTREAM-SINK-0000000154" <<Sink>> as KSTREAM_SINK_0000000154
	agent "KSTREAM-SINK-0000000158" <<Sink>> as KSTREAM_SINK_0000000158
	agent "KSTREAM-SINK-0000000163" <<Sink>> as KSTREAM_SINK_0000000163
	agent "KSTREAM-SINK-0000000166" <<Sink>> as KSTREAM_SINK_0000000166
	agent "KSTREAM-SINK-0000000169" <<Sink>> as KSTREAM_SINK_0000000169
	agent "KSTREAM-SINK-0000000172" <<Sink>> as KSTREAM_SINK_0000000172
	agent "KSTREAM-SINK-0000000177" <<Sink>> as KSTREAM_SINK_0000000177
	agent "KSTREAM-SINK-0000000181" <<Sink>> as KSTREAM_SINK_0000000181
	agent "KSTREAM-SINK-0000000187" <<Sink>> as KSTREAM_SINK_0000000187
	agent "KSTREAM-SINK-0000000190" <<Sink>> as KSTREAM_SINK_0000000190
	agent "KSTREAM-SINK-0000000193" <<Sink>> as KSTREAM_SINK_0000000193
	agent "KSTREAM-SINK-0000000196" <<Sink>> as KSTREAM_SINK_0000000196
	agent "KSTREAM-SINK-0000000220" <<Sink>> as KSTREAM_SINK_0000000220
	agent "KSTREAM-SINK-0000000227" <<Sink>> as KSTREAM_SINK_0000000227
	agent "KSTREAM-SINK-0000000231" <<Sink>> as KSTREAM_SINK_0000000231
	agent "KSTREAM-SINK-0000000238" <<Sink>> as KSTREAM_SINK_0000000238
	agent "KSTREAM-SINK-0000000243" <<Sink>> as KSTREAM_SINK_0000000243
	agent "KSTREAM-SINK-0000000246" <<Sink>> as KSTREAM_SINK_0000000246
	agent "KSTREAM-SINK-0000000250" <<Sink>> as KSTREAM_SINK_0000000250
	agent "KSTREAM-SINK-0000000255" <<Sink>> as KSTREAM_SINK_0000000255
	agent "KSTREAM-SINK-0000000258" <<Sink>> as KSTREAM_SINK_0000000258
	agent "KSTREAM-SINK-0000000261" <<Sink>> as KSTREAM_SINK_0000000261
	agent "KSTREAM-SINK-0000000264" <<Sink>> as KSTREAM_SINK_0000000264
	agent "KSTREAM-SINK-0000000269" <<Sink>> as KSTREAM_SINK_0000000269
	agent "KSTREAM-SINK-0000000273" <<Sink>> as KSTREAM_SINK_0000000273
	agent "KSTREAM-SINK-0000000279" <<Sink>> as KSTREAM_SINK_0000000279
	agent "KSTREAM-SINK-0000000282" <<Sink>> as KSTREAM_SINK_0000000282
	agent "KSTREAM-SINK-0000000285" <<Sink>> as KSTREAM_SINK_0000000285
	agent "KSTREAM-SINK-0000000288" <<Sink>> as KSTREAM_SINK_0000000288
	agent "KSTREAM-SINK-0000000307" <<Sink>> as KSTREAM_SINK_0000000307
	agent "KSTREAM-SINK-0000000311" <<Sink>> as KSTREAM_SINK_0000000311
	agent "KSTREAM-SINK-0000000318" <<Sink>> as KSTREAM_SINK_0000000318
	agent "KSTREAM-SINK-0000000323" <<Sink>> as KSTREAM_SINK_0000000323
	agent "KSTREAM-SINK-0000000326" <<Sink>> as KSTREAM_SINK_0000000326
	agent "KSTREAM-SINK-0000000330" <<Sink>> as KSTREAM_SINK_0000000330
	agent "KSTREAM-SINK-0000000335" <<Sink>> as KSTREAM_SINK_0000000335
	agent "KSTREAM-SINK-0000000338" <<Sink>> as KSTREAM_SINK_0000000338
	agent "KSTREAM-SINK-0000000341" <<Sink>> as KSTREAM_SINK_0000000341
	agent "KSTREAM-SINK-0000000344" <<Sink>> as KSTREAM_SINK_0000000344
	agent "KSTREAM-SINK-0000000349" <<Sink>> as KSTREAM_SINK_0000000349
	agent "KSTREAM-SINK-0000000353" <<Sink>> as KSTREAM_SINK_0000000353
	agent "KSTREAM-SINK-0000000359" <<Sink>> as KSTREAM_SINK_0000000359
	agent "KSTREAM-SINK-0000000362" <<Sink>> as KSTREAM_SINK_0000000362
	agent "KSTREAM-SINK-0000000365" <<Sink>> as KSTREAM_SINK_0000000365
	agent "KSTREAM-SINK-0000000368" <<Sink>> as KSTREAM_SINK_0000000368
	agent "KSTREAM-SINK-0000000394" <<Sink>> as KSTREAM_SINK_0000000394
	agent "KSTREAM-SINK-0000000398" <<Sink>> as KSTREAM_SINK_0000000398
	agent "KSTREAM-SINK-0000000405" <<Sink>> as KSTREAM_SINK_0000000405
	agent "KSTREAM-SINK-0000000410" <<Sink>> as KSTREAM_SINK_0000000410
	agent "KSTREAM-SINK-0000000413" <<Sink>> as KSTREAM_SINK_0000000413
	agent "KSTREAM-SINK-0000000417" <<Sink>> as KSTREAM_SINK_0000000417
	agent "KSTREAM-SINK-0000000422" <<Sink>> as KSTREAM_SINK_0000000422
	agent "KSTREAM-SINK-0000000425" <<Sink>> as KSTREAM_SINK_0000000425
	agent "KSTREAM-SINK-0000000428" <<Sink>> as KSTREAM_SINK_0000000428
	agent "KSTREAM-SINK-0000000431" <<Sink>> as KSTREAM_SINK_0000000431
	agent "KSTREAM-SINK-0000000436" <<Sink>> as KSTREAM_SINK_0000000436
	agent "KSTREAM-SINK-0000000440" <<Sink>> as KSTREAM_SINK_0000000440
	agent "KSTREAM-SINK-0000000446" <<Sink>> as KSTREAM_SINK_0000000446
	agent "KSTREAM-SINK-0000000449" <<Sink>> as KSTREAM_SINK_0000000449
	agent "KSTREAM-SINK-0000000452" <<Sink>> as KSTREAM_SINK_0000000452
	agent "KSTREAM-SINK-0000000455" <<Sink>> as KSTREAM_SINK_0000000455
	agent "ktable-helved.saker.v1" <<Processor>> as ktable_helved_saker_v1
	dptuple_leftjoin_saker_repartition --> dptuple_leftjoin_saker_repartition_source
	helved_saker_v1_state_store -- dptuple_leftjoin_saker
	tstuple_leftjoin_saker_repartition --> tstuple_leftjoin_saker_repartition_source
	helved_saker_v1_state_store -- tstuple_leftjoin_saker
	aaptuple_leftjoin_saker_repartition --> aaptuple_leftjoin_saker_repartition_source
	historisktuple_leftjoin_saker_repartition --> historisktuple_leftjoin_saker_repartition_source
	tptuple_leftjoin_saker_repartition --> tptuple_leftjoin_saker_repartition_source
	helved_saker_v1_state_store -- aaptuple_leftjoin_saker
	helved_saker_v1_state_store -- historisktuple_leftjoin_saker
	helved_saker_v1_state_store -- tptuple_leftjoin_saker
	ktable_helved_saker_v1_repartition --> ktable_helved_saker_v1_repartition_source
	helved_status_v1 <-- KSTREAM_SINK_0000000039
	helved_status_v1 <-- KSTREAM_SINK_0000000048
	helved_status_v1 <-- KSTREAM_SINK_0000000052
	helved_pending_utbetalinger_v1 <-- KSTREAM_SINK_0000000059
	helved_oppdrag_v1 <-- KSTREAM_SINK_0000000064
	helved_status_v1 <-- KSTREAM_SINK_0000000067
	helved_status_v1 <-- KSTREAM_SINK_0000000071
	helved_dryrun_aap_v1 <-- KSTREAM_SINK_0000000076
	helved_dryrun_dp_v1 <-- KSTREAM_SINK_0000000079
	helved_dryrun_ts_v1 <-- KSTREAM_SINK_0000000082
	helved_dryrun_tp_v1 <-- KSTREAM_SINK_0000000085
	helved_simuleringer_v1 <-- KSTREAM_SINK_0000000090
	helved_status_v1 <-- KSTREAM_SINK_0000000094
	helved_dryrun_aap_v1 <-- KSTREAM_SINK_0000000100
	helved_dryrun_dp_v1 <-- KSTREAM_SINK_0000000103
	helved_dryrun_ts_v1 <-- KSTREAM_SINK_0000000106
	helved_dryrun_tp_v1 <-- KSTREAM_SINK_0000000109
	helved_status_v1 <-- KSTREAM_SINK_0000000135
	helved_status_v1 <-- KSTREAM_SINK_0000000139
	helved_pending_utbetalinger_v1 <-- KSTREAM_SINK_0000000146
	helved_oppdrag_v1 <-- KSTREAM_SINK_0000000151
	helved_status_v1 <-- KSTREAM_SINK_0000000154
	helved_status_v1 <-- KSTREAM_SINK_0000000158
	helved_dryrun_aap_v1 <-- KSTREAM_SINK_0000000163
	helved_dryrun_dp_v1 <-- KSTREAM_SINK_0000000166
	helved_dryrun_ts_v1 <-- KSTREAM_SINK_0000000169
	helved_dryrun_tp_v1 <-- KSTREAM_SINK_0000000172
	helved_simuleringer_v1 <-- KSTREAM_SINK_0000000177
	helved_status_v1 <-- KSTREAM_SINK_0000000181
	helved_dryrun_aap_v1 <-- KSTREAM_SINK_0000000187
	helved_dryrun_dp_v1 <-- KSTREAM_SINK_0000000190
	helved_dryrun_ts_v1 <-- KSTREAM_SINK_0000000193
	helved_dryrun_tp_v1 <-- KSTREAM_SINK_0000000196
	helved_status_v1 <-- KSTREAM_SINK_0000000220
	helved_status_v1 <-- KSTREAM_SINK_0000000227
	helved_status_v1 <-- KSTREAM_SINK_0000000231
	helved_pending_utbetalinger_v1 <-- KSTREAM_SINK_0000000238
	helved_oppdrag_v1 <-- KSTREAM_SINK_0000000243
	helved_status_v1 <-- KSTREAM_SINK_0000000246
	helved_status_v1 <-- KSTREAM_SINK_0000000250
	helved_dryrun_aap_v1 <-- KSTREAM_SINK_0000000255
	helved_dryrun_dp_v1 <-- KSTREAM_SINK_0000000258
	helved_dryrun_ts_v1 <-- KSTREAM_SINK_0000000261
	helved_dryrun_tp_v1 <-- KSTREAM_SINK_0000000264
	helved_simuleringer_v1 <-- KSTREAM_SINK_0000000269
	helved_status_v1 <-- KSTREAM_SINK_0000000273
	helved_dryrun_aap_v1 <-- KSTREAM_SINK_0000000279
	helved_dryrun_dp_v1 <-- KSTREAM_SINK_0000000282
	helved_dryrun_ts_v1 <-- KSTREAM_SINK_0000000285
	helved_dryrun_tp_v1 <-- KSTREAM_SINK_0000000288
	helved_status_v1 <-- KSTREAM_SINK_0000000307
	helved_status_v1 <-- KSTREAM_SINK_0000000311
	helved_pending_utbetalinger_v1 <-- KSTREAM_SINK_0000000318
	helved_oppdrag_v1 <-- KSTREAM_SINK_0000000323
	helved_status_v1 <-- KSTREAM_SINK_0000000326
	helved_status_v1 <-- KSTREAM_SINK_0000000330
	helved_dryrun_aap_v1 <-- KSTREAM_SINK_0000000335
	helved_dryrun_dp_v1 <-- KSTREAM_SINK_0000000338
	helved_dryrun_ts_v1 <-- KSTREAM_SINK_0000000341
	helved_dryrun_tp_v1 <-- KSTREAM_SINK_0000000344
	helved_simuleringer_v1 <-- KSTREAM_SINK_0000000349
	helved_status_v1 <-- KSTREAM_SINK_0000000353
	helved_dryrun_aap_v1 <-- KSTREAM_SINK_0000000359
	helved_dryrun_dp_v1 <-- KSTREAM_SINK_0000000362
	helved_dryrun_ts_v1 <-- KSTREAM_SINK_0000000365
	helved_dryrun_tp_v1 <-- KSTREAM_SINK_0000000368
	helved_status_v1 <-- KSTREAM_SINK_0000000394
	helved_status_v1 <-- KSTREAM_SINK_0000000398
	helved_pending_utbetalinger_v1 <-- KSTREAM_SINK_0000000405
	helved_oppdrag_v1 <-- KSTREAM_SINK_0000000410
	helved_status_v1 <-- KSTREAM_SINK_0000000413
	helved_status_v1 <-- KSTREAM_SINK_0000000417
	helved_dryrun_aap_v1 <-- KSTREAM_SINK_0000000422
	helved_dryrun_dp_v1 <-- KSTREAM_SINK_0000000425
	helved_dryrun_ts_v1 <-- KSTREAM_SINK_0000000428
	helved_dryrun_tp_v1 <-- KSTREAM_SINK_0000000431
	helved_simuleringer_v1 <-- KSTREAM_SINK_0000000436
	helved_status_v1 <-- KSTREAM_SINK_0000000440
	helved_dryrun_aap_v1 <-- KSTREAM_SINK_0000000446
	helved_dryrun_dp_v1 <-- KSTREAM_SINK_0000000449
	helved_dryrun_ts_v1 <-- KSTREAM_SINK_0000000452
	helved_dryrun_tp_v1 <-- KSTREAM_SINK_0000000455
	helved_saker_v1_state_store -- ktable_helved_saker_v1
	dptuple_leftjoin_saker_repartition_source --> dptuple_leftjoin_saker
	dptuple_leftjoin_saker --> KSTREAM_PEEK_0000000032
	KSTREAM_PEEK_0000000032 --> KSTREAM_PROCESSOR_0000000033
	tstuple_leftjoin_saker_repartition_source --> tstuple_leftjoin_saker
	KSTREAM_PROCESSOR_0000000033 --> KSTREAM_BRANCH_0000000034
	tstuple_leftjoin_saker --> KSTREAM_PEEK_0000000213
	KSTREAM_BRANCH_0000000034 --> KSTREAM_BRANCH_00000000340
	KSTREAM_BRANCH_0000000034 --> KSTREAM_BRANCH_00000000341
	KSTREAM_PEEK_0000000213 --> KSTREAM_PROCESSOR_0000000214
	KSTREAM_PROCESSOR_0000000214 --> KSTREAM_KEY_SELECT_0000000215
	KSTREAM_KEY_SELECT_0000000215 --> KSTREAM_BRANCH_0000000216
	KSTREAM_BRANCH_0000000216 --> KSTREAM_BRANCH_00000002161
	KSTREAM_BRANCH_0000000216 --> KSTREAM_BRANCH_00000002160
	aaptuple_leftjoin_saker_repartition_source --> aaptuple_leftjoin_saker
	historisktuple_leftjoin_saker_repartition_source --> historisktuple_leftjoin_saker
	tptuple_leftjoin_saker_repartition_source --> tptuple_leftjoin_saker
	aaptuple_leftjoin_saker --> KSTREAM_PEEK_0000000126
	historisktuple_leftjoin_saker --> KSTREAM_PEEK_0000000385
	tptuple_leftjoin_saker --> KSTREAM_PEEK_0000000298
	KSTREAM_PEEK_0000000126 --> KSTREAM_PROCESSOR_0000000127
	KSTREAM_PEEK_0000000298 --> KSTREAM_PROCESSOR_0000000299
	KSTREAM_PEEK_0000000385 --> KSTREAM_PROCESSOR_0000000386
	KSTREAM_BRANCH_00000000340 --> KSTREAM_MAPVALUES_0000000041
	KSTREAM_PROCESSOR_0000000127 --> KSTREAM_MAPVALUES_0000000128
	KSTREAM_PROCESSOR_0000000299 --> KSTREAM_MAPVALUES_0000000300
	KSTREAM_PROCESSOR_0000000386 --> KSTREAM_MAPVALUES_0000000387
	KSTREAM_MAPVALUES_0000000041 --> KSTREAM_KEY_SELECT_0000000042
	KSTREAM_MAPVALUES_0000000128 --> KSTREAM_KEY_SELECT_0000000129
	KSTREAM_MAPVALUES_0000000300 --> KSTREAM_KEY_SELECT_0000000301
	KSTREAM_MAPVALUES_0000000387 --> KSTREAM_KEY_SELECT_0000000388
	KSTREAM_BRANCH_00000002160 --> KSTREAM_MAPVALUES_0000000222
	KSTREAM_KEY_SELECT_0000000042 --> KSTREAM_MAPVALUES_0000000043
	KSTREAM_KEY_SELECT_0000000129 --> KSTREAM_MAPVALUES_0000000130
	KSTREAM_KEY_SELECT_0000000301 --> KSTREAM_MAPVALUES_0000000302
	KSTREAM_KEY_SELECT_0000000388 --> KSTREAM_MAPVALUES_0000000389
	KSTREAM_MAPVALUES_0000000043 --> KSTREAM_BRANCH_0000000044
	KSTREAM_MAPVALUES_0000000130 --> KSTREAM_BRANCH_0000000131
	KSTREAM_MAPVALUES_0000000222 --> KSTREAM_BRANCH_0000000223
	KSTREAM_MAPVALUES_0000000302 --> KSTREAM_BRANCH_0000000303
	KSTREAM_MAPVALUES_0000000389 --> KSTREAM_BRANCH_0000000390
	KSTREAM_BRANCH_0000000044 --> KSTREAM_BRANCH_00000000441
	KSTREAM_BRANCH_0000000044 --> KSTREAM_BRANCH_00000000442
	KSTREAM_BRANCH_0000000044 --> KSTREAM_BRANCH_00000000443
	KSTREAM_BRANCH_0000000044 --> KSTREAM_BRANCH_00000000444
	KSTREAM_BRANCH_0000000131 --> KSTREAM_BRANCH_00000001311
	KSTREAM_BRANCH_0000000131 --> KSTREAM_BRANCH_00000001312
	KSTREAM_BRANCH_0000000131 --> KSTREAM_BRANCH_00000001313
	KSTREAM_BRANCH_0000000131 --> KSTREAM_BRANCH_00000001314
	KSTREAM_BRANCH_0000000223 --> KSTREAM_BRANCH_00000002231
	KSTREAM_BRANCH_0000000223 --> KSTREAM_BRANCH_00000002232
	KSTREAM_BRANCH_0000000223 --> KSTREAM_BRANCH_00000002233
	KSTREAM_BRANCH_0000000223 --> KSTREAM_BRANCH_00000002234
	KSTREAM_BRANCH_0000000303 --> KSTREAM_BRANCH_00000003033
	KSTREAM_BRANCH_0000000303 --> KSTREAM_BRANCH_00000003031
	KSTREAM_BRANCH_0000000303 --> KSTREAM_BRANCH_00000003032
	KSTREAM_BRANCH_0000000303 --> KSTREAM_BRANCH_00000003034
	KSTREAM_BRANCH_0000000390 --> KSTREAM_BRANCH_00000003901
	KSTREAM_BRANCH_0000000390 --> KSTREAM_BRANCH_00000003902
	KSTREAM_BRANCH_0000000390 --> KSTREAM_BRANCH_00000003903
	KSTREAM_BRANCH_0000000390 --> KSTREAM_BRANCH_00000003904
	KSTREAM_BRANCH_00000000443 --> KSTREAM_MAPVALUES_0000000054
	KSTREAM_BRANCH_00000001313 --> KSTREAM_MAPVALUES_0000000141
	KSTREAM_BRANCH_00000002233 --> KSTREAM_MAPVALUES_0000000233
	KSTREAM_BRANCH_00000003033 --> KSTREAM_MAPVALUES_0000000313
	KSTREAM_BRANCH_00000003903 --> KSTREAM_MAPVALUES_0000000400
	KSTREAM_MAPVALUES_0000000054 --> KSTREAM_FLATMAPVALUES_0000000055
	KSTREAM_MAPVALUES_0000000054 --> KSTREAM_FLATMAPVALUES_0000000060
	KSTREAM_MAPVALUES_0000000054 --> KSTREAM_MAPVALUES_0000000072
	KSTREAM_MAPVALUES_0000000054 --> KSTREAM_FILTER_0000000068
	KSTREAM_MAPVALUES_0000000141 --> KSTREAM_MAPVALUES_0000000159
	KSTREAM_MAPVALUES_0000000141 --> KSTREAM_FLATMAPVALUES_0000000147
	KSTREAM_MAPVALUES_0000000141 --> KSTREAM_FLATMAPVALUES_0000000142
	KSTREAM_MAPVALUES_0000000141 --> KSTREAM_FILTER_0000000155
	KSTREAM_MAPVALUES_0000000233 --> KSTREAM_FLATMAPVALUES_0000000239
	KSTREAM_MAPVALUES_0000000233 --> KSTREAM_FLATMAPVALUES_0000000234
	KSTREAM_MAPVALUES_0000000233 --> KSTREAM_FILTER_0000000247
	KSTREAM_MAPVALUES_0000000233 --> KSTREAM_MAPVALUES_0000000251
	KSTREAM_MAPVALUES_0000000313 --> KSTREAM_MAPVALUES_0000000331
	KSTREAM_MAPVALUES_0000000313 --> KSTREAM_FLATMAPVALUES_0000000314
	KSTREAM_MAPVALUES_0000000313 --> KSTREAM_FLATMAPVALUES_0000000319
	KSTREAM_MAPVALUES_0000000313 --> KSTREAM_FILTER_0000000327
	KSTREAM_MAPVALUES_0000000400 --> KSTREAM_MAPVALUES_0000000418
	KSTREAM_MAPVALUES_0000000400 --> KSTREAM_FILTER_0000000414
	KSTREAM_MAPVALUES_0000000400 --> KSTREAM_FLATMAPVALUES_0000000401
	KSTREAM_MAPVALUES_0000000400 --> KSTREAM_FLATMAPVALUES_0000000406
	KSTREAM_BRANCH_00000000444 --> KSTREAM_MAPVALUES_0000000087
	KSTREAM_BRANCH_00000001314 --> KSTREAM_MAPVALUES_0000000174
	KSTREAM_BRANCH_00000002234 --> KSTREAM_MAPVALUES_0000000266
	KSTREAM_BRANCH_00000003034 --> KSTREAM_MAPVALUES_0000000346
	KSTREAM_BRANCH_00000003904 --> KSTREAM_MAPVALUES_0000000433
	KSTREAM_MAPVALUES_0000000087 --> KSTREAM_FILTER_0000000091
	KSTREAM_MAPVALUES_0000000087 --> KSTREAM_FILTER_0000000095
	KSTREAM_MAPVALUES_0000000087 --> KSTREAM_FLATMAPVALUES_0000000088
	KSTREAM_MAPVALUES_0000000174 --> KSTREAM_FLATMAPVALUES_0000000175
	KSTREAM_MAPVALUES_0000000174 --> KSTREAM_FILTER_0000000178
	KSTREAM_MAPVALUES_0000000174 --> KSTREAM_FILTER_0000000182
	KSTREAM_MAPVALUES_0000000266 --> KSTREAM_FLATMAPVALUES_0000000267
	KSTREAM_MAPVALUES_0000000266 --> KSTREAM_FILTER_0000000270
	KSTREAM_MAPVALUES_0000000266 --> KSTREAM_FILTER_0000000274
	KSTREAM_MAPVALUES_0000000346 --> KSTREAM_FILTER_0000000350
	KSTREAM_MAPVALUES_0000000346 --> KSTREAM_FLATMAPVALUES_0000000347
	KSTREAM_MAPVALUES_0000000346 --> KSTREAM_FILTER_0000000354
	KSTREAM_MAPVALUES_0000000433 --> KSTREAM_FILTER_0000000441
	KSTREAM_MAPVALUES_0000000433 --> KSTREAM_FILTER_0000000437
	KSTREAM_MAPVALUES_0000000433 --> KSTREAM_FLATMAPVALUES_0000000434
	KSTREAM_FILTER_0000000095 --> KSTREAM_MAPVALUES_0000000096
	KSTREAM_FILTER_0000000182 --> KSTREAM_MAPVALUES_0000000183
	KSTREAM_FILTER_0000000274 --> KSTREAM_MAPVALUES_0000000275
	KSTREAM_FILTER_0000000354 --> KSTREAM_MAPVALUES_0000000355
	KSTREAM_FILTER_0000000441 --> KSTREAM_MAPVALUES_0000000442
	KSTREAM_MAPVALUES_0000000072 --> KSTREAM_BRANCH_0000000073
	KSTREAM_MAPVALUES_0000000096 --> KSTREAM_BRANCH_0000000097
	KSTREAM_MAPVALUES_0000000159 --> KSTREAM_BRANCH_0000000160
	KSTREAM_MAPVALUES_0000000183 --> KSTREAM_BRANCH_0000000184
	KSTREAM_MAPVALUES_0000000251 --> KSTREAM_BRANCH_0000000252
	KSTREAM_MAPVALUES_0000000275 --> KSTREAM_BRANCH_0000000276
	KSTREAM_MAPVALUES_0000000331 --> KSTREAM_BRANCH_0000000332
	KSTREAM_MAPVALUES_0000000355 --> KSTREAM_BRANCH_0000000356
	KSTREAM_MAPVALUES_0000000418 --> KSTREAM_BRANCH_0000000419
	KSTREAM_MAPVALUES_0000000442 --> KSTREAM_BRANCH_0000000443
	KSTREAM_BRANCH_0000000073 --> KSTREAM_BRANCH_00000000731
	KSTREAM_BRANCH_0000000073 --> KSTREAM_BRANCH_00000000732
	KSTREAM_BRANCH_0000000073 --> KSTREAM_BRANCH_00000000733
	KSTREAM_BRANCH_0000000073 --> KSTREAM_BRANCH_00000000734
	KSTREAM_BRANCH_0000000097 --> KSTREAM_BRANCH_00000000971
	KSTREAM_BRANCH_0000000097 --> KSTREAM_BRANCH_00000000972
	KSTREAM_BRANCH_0000000097 --> KSTREAM_BRANCH_00000000973
	KSTREAM_BRANCH_0000000097 --> KSTREAM_BRANCH_00000000974
	KSTREAM_BRANCH_0000000160 --> KSTREAM_BRANCH_00000001601
	KSTREAM_BRANCH_0000000160 --> KSTREAM_BRANCH_00000001602
	KSTREAM_BRANCH_0000000160 --> KSTREAM_BRANCH_00000001603
	KSTREAM_BRANCH_0000000160 --> KSTREAM_BRANCH_00000001604
	KSTREAM_BRANCH_0000000184 --> KSTREAM_BRANCH_00000001841
	KSTREAM_BRANCH_0000000184 --> KSTREAM_BRANCH_00000001842
	KSTREAM_BRANCH_0000000184 --> KSTREAM_BRANCH_00000001843
	KSTREAM_BRANCH_0000000184 --> KSTREAM_BRANCH_00000001844
	KSTREAM_BRANCH_0000000252 --> KSTREAM_BRANCH_00000002521
	KSTREAM_BRANCH_0000000252 --> KSTREAM_BRANCH_00000002522
	KSTREAM_BRANCH_0000000252 --> KSTREAM_BRANCH_00000002523
	KSTREAM_BRANCH_0000000252 --> KSTREAM_BRANCH_00000002524
	KSTREAM_BRANCH_0000000276 --> KSTREAM_BRANCH_00000002761
	KSTREAM_BRANCH_0000000276 --> KSTREAM_BRANCH_00000002762
	KSTREAM_BRANCH_0000000276 --> KSTREAM_BRANCH_00000002763
	KSTREAM_BRANCH_0000000276 --> KSTREAM_BRANCH_00000002764
	KSTREAM_BRANCH_0000000332 --> KSTREAM_BRANCH_00000003321
	KSTREAM_BRANCH_0000000332 --> KSTREAM_BRANCH_00000003322
	KSTREAM_BRANCH_0000000332 --> KSTREAM_BRANCH_00000003323
	KSTREAM_BRANCH_0000000332 --> KSTREAM_BRANCH_00000003324
	KSTREAM_BRANCH_0000000356 --> KSTREAM_BRANCH_00000003561
	KSTREAM_BRANCH_0000000356 --> KSTREAM_BRANCH_00000003562
	KSTREAM_BRANCH_0000000356 --> KSTREAM_BRANCH_00000003563
	KSTREAM_BRANCH_0000000356 --> KSTREAM_BRANCH_00000003564
	KSTREAM_BRANCH_0000000419 --> KSTREAM_BRANCH_00000004191
	KSTREAM_BRANCH_0000000419 --> KSTREAM_BRANCH_00000004192
	KSTREAM_BRANCH_0000000419 --> KSTREAM_BRANCH_00000004193
	KSTREAM_BRANCH_0000000419 --> KSTREAM_BRANCH_00000004194
	KSTREAM_BRANCH_0000000443 --> KSTREAM_BRANCH_00000004431
	KSTREAM_BRANCH_0000000443 --> KSTREAM_BRANCH_00000004432
	KSTREAM_BRANCH_0000000443 --> KSTREAM_BRANCH_00000004433
	KSTREAM_BRANCH_0000000443 --> KSTREAM_BRANCH_00000004434
	KSTREAM_FLATMAPVALUES_0000000060 --> KSTREAM_PROCESSOR_0000000061
	KSTREAM_FLATMAPVALUES_0000000147 --> KSTREAM_PROCESSOR_0000000148
	KSTREAM_FLATMAPVALUES_0000000239 --> KSTREAM_PROCESSOR_0000000240
	KSTREAM_FLATMAPVALUES_0000000319 --> KSTREAM_PROCESSOR_0000000320
	KSTREAM_FLATMAPVALUES_0000000406 --> KSTREAM_PROCESSOR_0000000407
	KSTREAM_PROCESSOR_0000000061 --> KSTREAM_MAPVALUES_0000000062
	KSTREAM_PROCESSOR_0000000148 --> KSTREAM_MAPVALUES_0000000149
	KSTREAM_PROCESSOR_0000000240 --> KSTREAM_MAPVALUES_0000000241
	KSTREAM_PROCESSOR_0000000320 --> KSTREAM_MAPVALUES_0000000321
	KSTREAM_PROCESSOR_0000000407 --> KSTREAM_MAPVALUES_0000000408
	KSTREAM_MAPVALUES_0000000062 --> KSTREAM_MAPVALUES_0000000065
	KSTREAM_MAPVALUES_0000000062 --> KSTREAM_PROCESSOR_0000000063
	KSTREAM_MAPVALUES_0000000149 --> KSTREAM_MAPVALUES_0000000152
	KSTREAM_MAPVALUES_0000000149 --> KSTREAM_PROCESSOR_0000000150
	KSTREAM_MAPVALUES_0000000241 --> KSTREAM_MAPVALUES_0000000244
	KSTREAM_MAPVALUES_0000000241 --> KSTREAM_PROCESSOR_0000000242
	KSTREAM_MAPVALUES_0000000321 --> KSTREAM_MAPVALUES_0000000324
	KSTREAM_MAPVALUES_0000000321 --> KSTREAM_PROCESSOR_0000000322
	KSTREAM_MAPVALUES_0000000408 --> KSTREAM_PROCESSOR_0000000409
	KSTREAM_MAPVALUES_0000000408 --> KSTREAM_MAPVALUES_0000000411
	KSTREAM_BRANCH_00000000341 --> KSTREAM_KEY_SELECT_0000000036
	KSTREAM_FLATMAPVALUES_0000000055 --> KSTREAM_PROCESSOR_0000000056
	KSTREAM_FLATMAPVALUES_0000000142 --> KSTREAM_PROCESSOR_0000000143
	KSTREAM_FLATMAPVALUES_0000000234 --> KSTREAM_PROCESSOR_0000000235
	KSTREAM_FLATMAPVALUES_0000000314 --> KSTREAM_PROCESSOR_0000000315
	KSTREAM_FLATMAPVALUES_0000000401 --> KSTREAM_PROCESSOR_0000000402
	KSTREAM_BRANCH_00000000441 --> KSTREAM_MAPVALUES_0000000046
	KSTREAM_BRANCH_00000000442 --> KSTREAM_MAPVALUES_0000000050
	KSTREAM_BRANCH_00000001311 --> KSTREAM_MAPVALUES_0000000133
	KSTREAM_BRANCH_00000001312 --> KSTREAM_MAPVALUES_0000000137
	KSTREAM_BRANCH_00000002161 --> KSTREAM_MAPVALUES_0000000218
	KSTREAM_BRANCH_00000002231 --> KSTREAM_MAPVALUES_0000000225
	KSTREAM_BRANCH_00000002232 --> KSTREAM_MAPVALUES_0000000229
	KSTREAM_BRANCH_00000003031 --> KSTREAM_MAPVALUES_0000000305
	KSTREAM_BRANCH_00000003032 --> KSTREAM_MAPVALUES_0000000309
	KSTREAM_BRANCH_00000003901 --> KSTREAM_MAPVALUES_0000000392
	KSTREAM_BRANCH_00000003902 --> KSTREAM_MAPVALUES_0000000396
	KSTREAM_FILTER_0000000068 --> KSTREAM_MAPVALUES_0000000069
	KSTREAM_FILTER_0000000091 --> KSTREAM_MAPVALUES_0000000092
	KSTREAM_FILTER_0000000155 --> KSTREAM_MAPVALUES_0000000156
	KSTREAM_FILTER_0000000178 --> KSTREAM_MAPVALUES_0000000179
	KSTREAM_FILTER_0000000247 --> KSTREAM_MAPVALUES_0000000248
	KSTREAM_FILTER_0000000270 --> KSTREAM_MAPVALUES_0000000271
	KSTREAM_FILTER_0000000327 --> KSTREAM_MAPVALUES_0000000328
	KSTREAM_FILTER_0000000350 --> KSTREAM_MAPVALUES_0000000351
	KSTREAM_FILTER_0000000414 --> KSTREAM_MAPVALUES_0000000415
	KSTREAM_FILTER_0000000437 --> KSTREAM_MAPVALUES_0000000438
	KSTREAM_KEY_SELECT_0000000036 --> KSTREAM_MAPVALUES_0000000037
	KSTREAM_PROCESSOR_0000000056 --> KSTREAM_FLATMAP_0000000057
	KSTREAM_PROCESSOR_0000000143 --> KSTREAM_FLATMAP_0000000144
	KSTREAM_PROCESSOR_0000000235 --> KSTREAM_FLATMAP_0000000236
	KSTREAM_PROCESSOR_0000000315 --> KSTREAM_FLATMAP_0000000316
	KSTREAM_PROCESSOR_0000000402 --> KSTREAM_FLATMAP_0000000403
	KSTREAM_BRANCH_00000000731 --> KSTREAM_PROCESSOR_0000000075
	KSTREAM_BRANCH_00000000732 --> KSTREAM_PROCESSOR_0000000078
	KSTREAM_BRANCH_00000000733 --> KSTREAM_PROCESSOR_0000000081
	KSTREAM_BRANCH_00000000734 --> KSTREAM_PROCESSOR_0000000084
	KSTREAM_BRANCH_00000000971 --> KSTREAM_PROCESSOR_0000000099
	KSTREAM_BRANCH_00000000972 --> KSTREAM_PROCESSOR_0000000102
	KSTREAM_BRANCH_00000000973 --> KSTREAM_PROCESSOR_0000000105
	KSTREAM_BRANCH_00000000974 --> KSTREAM_PROCESSOR_0000000108
	KSTREAM_BRANCH_00000001601 --> KSTREAM_PROCESSOR_0000000162
	KSTREAM_BRANCH_00000001602 --> KSTREAM_PROCESSOR_0000000165
	KSTREAM_BRANCH_00000001603 --> KSTREAM_PROCESSOR_0000000168
	KSTREAM_BRANCH_00000001604 --> KSTREAM_PROCESSOR_0000000171
	KSTREAM_BRANCH_00000001841 --> KSTREAM_PROCESSOR_0000000186
	KSTREAM_BRANCH_00000001842 --> KSTREAM_PROCESSOR_0000000189
	KSTREAM_BRANCH_00000001843 --> KSTREAM_PROCESSOR_0000000192
	KSTREAM_BRANCH_00000001844 --> KSTREAM_PROCESSOR_0000000195
	KSTREAM_BRANCH_00000002521 --> KSTREAM_PROCESSOR_0000000254
	KSTREAM_BRANCH_00000002522 --> KSTREAM_PROCESSOR_0000000257
	KSTREAM_BRANCH_00000002523 --> KSTREAM_PROCESSOR_0000000260
	KSTREAM_BRANCH_00000002524 --> KSTREAM_PROCESSOR_0000000263
	KSTREAM_BRANCH_00000002761 --> KSTREAM_PROCESSOR_0000000278
	KSTREAM_BRANCH_00000002762 --> KSTREAM_PROCESSOR_0000000281
	KSTREAM_BRANCH_00000002763 --> KSTREAM_PROCESSOR_0000000284
	KSTREAM_BRANCH_00000002764 --> KSTREAM_PROCESSOR_0000000287
	KSTREAM_BRANCH_00000003321 --> KSTREAM_PROCESSOR_0000000334
	KSTREAM_BRANCH_00000003322 --> KSTREAM_PROCESSOR_0000000337
	KSTREAM_BRANCH_00000003323 --> KSTREAM_PROCESSOR_0000000340
	KSTREAM_BRANCH_00000003324 --> KSTREAM_PROCESSOR_0000000343
	KSTREAM_BRANCH_00000003561 --> KSTREAM_PROCESSOR_0000000358
	KSTREAM_BRANCH_00000003562 --> KSTREAM_PROCESSOR_0000000361
	KSTREAM_BRANCH_00000003563 --> KSTREAM_PROCESSOR_0000000364
	KSTREAM_BRANCH_00000003564 --> KSTREAM_PROCESSOR_0000000367
	KSTREAM_BRANCH_00000004191 --> KSTREAM_PROCESSOR_0000000421
	KSTREAM_BRANCH_00000004192 --> KSTREAM_PROCESSOR_0000000424
	KSTREAM_BRANCH_00000004193 --> KSTREAM_PROCESSOR_0000000427
	KSTREAM_BRANCH_00000004194 --> KSTREAM_PROCESSOR_0000000430
	KSTREAM_BRANCH_00000004431 --> KSTREAM_PROCESSOR_0000000445
	KSTREAM_BRANCH_00000004432 --> KSTREAM_PROCESSOR_0000000448
	KSTREAM_BRANCH_00000004433 --> KSTREAM_PROCESSOR_0000000451
	KSTREAM_BRANCH_00000004434 --> KSTREAM_PROCESSOR_0000000454
	KSTREAM_FLATMAP_0000000057 --> KSTREAM_PROCESSOR_0000000058
	KSTREAM_FLATMAP_0000000144 --> KSTREAM_PROCESSOR_0000000145
	KSTREAM_FLATMAP_0000000236 --> KSTREAM_PROCESSOR_0000000237
	KSTREAM_FLATMAP_0000000316 --> KSTREAM_PROCESSOR_0000000317
	KSTREAM_FLATMAP_0000000403 --> KSTREAM_PROCESSOR_0000000404
	KSTREAM_FLATMAPVALUES_0000000088 --> KSTREAM_PROCESSOR_0000000089
	KSTREAM_FLATMAPVALUES_0000000175 --> KSTREAM_PROCESSOR_0000000176
	KSTREAM_FLATMAPVALUES_0000000267 --> KSTREAM_PROCESSOR_0000000268
	KSTREAM_FLATMAPVALUES_0000000347 --> KSTREAM_PROCESSOR_0000000348
	KSTREAM_FLATMAPVALUES_0000000434 --> KSTREAM_PROCESSOR_0000000435
	KSTREAM_MAPVALUES_0000000037 --> KSTREAM_PROCESSOR_0000000038
	KSTREAM_MAPVALUES_0000000046 --> KSTREAM_PROCESSOR_0000000047
	KSTREAM_MAPVALUES_0000000050 --> KSTREAM_PROCESSOR_0000000051
	KSTREAM_MAPVALUES_0000000065 --> KSTREAM_PROCESSOR_0000000066
	KSTREAM_MAPVALUES_0000000069 --> KSTREAM_PROCESSOR_0000000070
	KSTREAM_MAPVALUES_0000000092 --> KSTREAM_PROCESSOR_0000000093
	KSTREAM_MAPVALUES_0000000133 --> KSTREAM_PROCESSOR_0000000134
	KSTREAM_MAPVALUES_0000000137 --> KSTREAM_PROCESSOR_0000000138
	KSTREAM_MAPVALUES_0000000152 --> KSTREAM_PROCESSOR_0000000153
	KSTREAM_MAPVALUES_0000000156 --> KSTREAM_PROCESSOR_0000000157
	KSTREAM_MAPVALUES_0000000179 --> KSTREAM_PROCESSOR_0000000180
	KSTREAM_MAPVALUES_0000000218 --> KSTREAM_PROCESSOR_0000000219
	KSTREAM_MAPVALUES_0000000225 --> KSTREAM_PROCESSOR_0000000226
	KSTREAM_MAPVALUES_0000000229 --> KSTREAM_PROCESSOR_0000000230
	KSTREAM_MAPVALUES_0000000244 --> KSTREAM_PROCESSOR_0000000245
	KSTREAM_MAPVALUES_0000000248 --> KSTREAM_PROCESSOR_0000000249
	KSTREAM_MAPVALUES_0000000271 --> KSTREAM_PROCESSOR_0000000272
	KSTREAM_MAPVALUES_0000000305 --> KSTREAM_PROCESSOR_0000000306
	KSTREAM_MAPVALUES_0000000309 --> KSTREAM_PROCESSOR_0000000310
	KSTREAM_MAPVALUES_0000000324 --> KSTREAM_PROCESSOR_0000000325
	KSTREAM_MAPVALUES_0000000328 --> KSTREAM_PROCESSOR_0000000329
	KSTREAM_MAPVALUES_0000000351 --> KSTREAM_PROCESSOR_0000000352
	KSTREAM_MAPVALUES_0000000392 --> KSTREAM_PROCESSOR_0000000393
	KSTREAM_MAPVALUES_0000000396 --> KSTREAM_PROCESSOR_0000000397
	KSTREAM_MAPVALUES_0000000411 --> KSTREAM_PROCESSOR_0000000412
	KSTREAM_MAPVALUES_0000000415 --> KSTREAM_PROCESSOR_0000000416
	KSTREAM_MAPVALUES_0000000438 --> KSTREAM_PROCESSOR_0000000439
	KSTREAM_PROCESSOR_0000000038 --> KSTREAM_SINK_0000000039
	KSTREAM_PROCESSOR_0000000047 --> KSTREAM_SINK_0000000048
	KSTREAM_PROCESSOR_0000000051 --> KSTREAM_SINK_0000000052
	KSTREAM_PROCESSOR_0000000058 --> KSTREAM_SINK_0000000059
	KSTREAM_PROCESSOR_0000000063 --> KSTREAM_SINK_0000000064
	KSTREAM_PROCESSOR_0000000066 --> KSTREAM_SINK_0000000067
	KSTREAM_PROCESSOR_0000000070 --> KSTREAM_SINK_0000000071
	KSTREAM_PROCESSOR_0000000075 --> KSTREAM_SINK_0000000076
	KSTREAM_PROCESSOR_0000000078 --> KSTREAM_SINK_0000000079
	KSTREAM_PROCESSOR_0000000081 --> KSTREAM_SINK_0000000082
	KSTREAM_PROCESSOR_0000000084 --> KSTREAM_SINK_0000000085
	KSTREAM_PROCESSOR_0000000089 --> KSTREAM_SINK_0000000090
	KSTREAM_PROCESSOR_0000000093 --> KSTREAM_SINK_0000000094
	KSTREAM_PROCESSOR_0000000099 --> KSTREAM_SINK_0000000100
	KSTREAM_PROCESSOR_0000000102 --> KSTREAM_SINK_0000000103
	KSTREAM_PROCESSOR_0000000105 --> KSTREAM_SINK_0000000106
	KSTREAM_PROCESSOR_0000000108 --> KSTREAM_SINK_0000000109
	KSTREAM_PROCESSOR_0000000134 --> KSTREAM_SINK_0000000135
	KSTREAM_PROCESSOR_0000000138 --> KSTREAM_SINK_0000000139
	KSTREAM_PROCESSOR_0000000145 --> KSTREAM_SINK_0000000146
	KSTREAM_PROCESSOR_0000000150 --> KSTREAM_SINK_0000000151
	KSTREAM_PROCESSOR_0000000153 --> KSTREAM_SINK_0000000154
	KSTREAM_PROCESSOR_0000000157 --> KSTREAM_SINK_0000000158
	KSTREAM_PROCESSOR_0000000162 --> KSTREAM_SINK_0000000163
	KSTREAM_PROCESSOR_0000000165 --> KSTREAM_SINK_0000000166
	KSTREAM_PROCESSOR_0000000168 --> KSTREAM_SINK_0000000169
	KSTREAM_PROCESSOR_0000000171 --> KSTREAM_SINK_0000000172
	KSTREAM_PROCESSOR_0000000176 --> KSTREAM_SINK_0000000177
	KSTREAM_PROCESSOR_0000000180 --> KSTREAM_SINK_0000000181
	KSTREAM_PROCESSOR_0000000186 --> KSTREAM_SINK_0000000187
	KSTREAM_PROCESSOR_0000000189 --> KSTREAM_SINK_0000000190
	KSTREAM_PROCESSOR_0000000192 --> KSTREAM_SINK_0000000193
	KSTREAM_PROCESSOR_0000000195 --> KSTREAM_SINK_0000000196
	KSTREAM_PROCESSOR_0000000219 --> KSTREAM_SINK_0000000220
	KSTREAM_PROCESSOR_0000000226 --> KSTREAM_SINK_0000000227
	KSTREAM_PROCESSOR_0000000230 --> KSTREAM_SINK_0000000231
	KSTREAM_PROCESSOR_0000000237 --> KSTREAM_SINK_0000000238
	KSTREAM_PROCESSOR_0000000242 --> KSTREAM_SINK_0000000243
	KSTREAM_PROCESSOR_0000000245 --> KSTREAM_SINK_0000000246
	KSTREAM_PROCESSOR_0000000249 --> KSTREAM_SINK_0000000250
	KSTREAM_PROCESSOR_0000000254 --> KSTREAM_SINK_0000000255
	KSTREAM_PROCESSOR_0000000257 --> KSTREAM_SINK_0000000258
	KSTREAM_PROCESSOR_0000000260 --> KSTREAM_SINK_0000000261
	KSTREAM_PROCESSOR_0000000263 --> KSTREAM_SINK_0000000264
	KSTREAM_PROCESSOR_0000000268 --> KSTREAM_SINK_0000000269
	KSTREAM_PROCESSOR_0000000272 --> KSTREAM_SINK_0000000273
	KSTREAM_PROCESSOR_0000000278 --> KSTREAM_SINK_0000000279
	KSTREAM_PROCESSOR_0000000281 --> KSTREAM_SINK_0000000282
	KSTREAM_PROCESSOR_0000000284 --> KSTREAM_SINK_0000000285
	KSTREAM_PROCESSOR_0000000287 --> KSTREAM_SINK_0000000288
	KSTREAM_PROCESSOR_0000000306 --> KSTREAM_SINK_0000000307
	KSTREAM_PROCESSOR_0000000310 --> KSTREAM_SINK_0000000311
	KSTREAM_PROCESSOR_0000000317 --> KSTREAM_SINK_0000000318
	KSTREAM_PROCESSOR_0000000322 --> KSTREAM_SINK_0000000323
	KSTREAM_PROCESSOR_0000000325 --> KSTREAM_SINK_0000000326
	KSTREAM_PROCESSOR_0000000329 --> KSTREAM_SINK_0000000330
	KSTREAM_PROCESSOR_0000000334 --> KSTREAM_SINK_0000000335
	KSTREAM_PROCESSOR_0000000337 --> KSTREAM_SINK_0000000338
	KSTREAM_PROCESSOR_0000000340 --> KSTREAM_SINK_0000000341
	KSTREAM_PROCESSOR_0000000343 --> KSTREAM_SINK_0000000344
	KSTREAM_PROCESSOR_0000000348 --> KSTREAM_SINK_0000000349
	KSTREAM_PROCESSOR_0000000352 --> KSTREAM_SINK_0000000353
	KSTREAM_PROCESSOR_0000000358 --> KSTREAM_SINK_0000000359
	KSTREAM_PROCESSOR_0000000361 --> KSTREAM_SINK_0000000362
	KSTREAM_PROCESSOR_0000000364 --> KSTREAM_SINK_0000000365
	KSTREAM_PROCESSOR_0000000367 --> KSTREAM_SINK_0000000368
	KSTREAM_PROCESSOR_0000000393 --> KSTREAM_SINK_0000000394
	KSTREAM_PROCESSOR_0000000397 --> KSTREAM_SINK_0000000398
	KSTREAM_PROCESSOR_0000000404 --> KSTREAM_SINK_0000000405
	KSTREAM_PROCESSOR_0000000409 --> KSTREAM_SINK_0000000410
	KSTREAM_PROCESSOR_0000000412 --> KSTREAM_SINK_0000000413
	KSTREAM_PROCESSOR_0000000416 --> KSTREAM_SINK_0000000417
	KSTREAM_PROCESSOR_0000000421 --> KSTREAM_SINK_0000000422
	KSTREAM_PROCESSOR_0000000424 --> KSTREAM_SINK_0000000425
	KSTREAM_PROCESSOR_0000000427 --> KSTREAM_SINK_0000000428
	KSTREAM_PROCESSOR_0000000430 --> KSTREAM_SINK_0000000431
	KSTREAM_PROCESSOR_0000000435 --> KSTREAM_SINK_0000000436
	KSTREAM_PROCESSOR_0000000439 --> KSTREAM_SINK_0000000440
	KSTREAM_PROCESSOR_0000000445 --> KSTREAM_SINK_0000000446
	KSTREAM_PROCESSOR_0000000448 --> KSTREAM_SINK_0000000449
	KSTREAM_PROCESSOR_0000000451 --> KSTREAM_SINK_0000000452
	KSTREAM_PROCESSOR_0000000454 --> KSTREAM_SINK_0000000455
	ktable_helved_saker_v1_repartition_source --> ktable_helved_saker_v1
}
package "Sub-topology: 5" {
	agent "consume-teamdagpenger.utbetaling.v1" <<Source>> as consume_teamdagpenger_utbetaling_v1
	agent "KSTREAM-PROCESSOR-0000000017" <<Processor>> as KSTREAM_PROCESSOR_0000000017
	agent "KSTREAM-FILTER-0000000018" <<Processor>> as KSTREAM_FILTER_0000000018
	agent "from-teamdagpenger.utbetaling.v1-repartition-filter" <<Processor>> as from_teamdagpenger_utbetaling_v1_repartition_filter
	agent "from-teamdagpenger.utbetaling.v1-repartition-sink" <<Sink>> as from_teamdagpenger_utbetaling_v1_repartition_sink
	teamdagpenger_utbetaling_v1 --> consume_teamdagpenger_utbetaling_v1
	from_teamdagpenger_utbetaling_v1_repartition <-- from_teamdagpenger_utbetaling_v1_repartition_sink
	consume_teamdagpenger_utbetaling_v1 --> KSTREAM_PROCESSOR_0000000017
	KSTREAM_PROCESSOR_0000000017 --> KSTREAM_FILTER_0000000018
	KSTREAM_FILTER_0000000018 --> from_teamdagpenger_utbetaling_v1_repartition_filter
	from_teamdagpenger_utbetaling_v1_repartition_filter --> from_teamdagpenger_utbetaling_v1_repartition_sink
}
package "Sub-topology: 6" {
	agent "consume-helved.utbetalinger-dp.v1" <<Source>> as consume_helved_utbetalinger_dp_v1
	agent "KSTREAM-PROCESSOR-0000000023" <<Processor>> as KSTREAM_PROCESSOR_0000000023
	agent "KSTREAM-FILTER-0000000024" <<Processor>> as KSTREAM_FILTER_0000000024
	agent "from-teamdagpenger.utbetaling.v1-repartition-source" <<Source>> as from_teamdagpenger_utbetaling_v1_repartition_source
	agent "KSTREAM-MERGE-0000000025" <<Processor>> as KSTREAM_MERGE_0000000025
	agent "KSTREAM-MAPVALUES-0000000026" <<Processor>> as KSTREAM_MAPVALUES_0000000026
	agent "KSTREAM-KEY-SELECT-0000000027" <<Processor>> as KSTREAM_KEY_SELECT_0000000027
	agent "dptuple-leftjoin-saker-repartition-filter" <<Processor>> as dptuple_leftjoin_saker_repartition_filter
	agent "dptuple-leftjoin-saker-repartition-sink" <<Sink>> as dptuple_leftjoin_saker_repartition_sink
	helved_utbetalinger_dp_v1 --> consume_helved_utbetalinger_dp_v1
	from_teamdagpenger_utbetaling_v1_repartition --> from_teamdagpenger_utbetaling_v1_repartition_source
	dptuple_leftjoin_saker_repartition <-- dptuple_leftjoin_saker_repartition_sink
	consume_helved_utbetalinger_dp_v1 --> KSTREAM_PROCESSOR_0000000023
	KSTREAM_PROCESSOR_0000000023 --> KSTREAM_FILTER_0000000024
	KSTREAM_FILTER_0000000024 --> KSTREAM_MERGE_0000000025
	from_teamdagpenger_utbetaling_v1_repartition_source --> KSTREAM_MERGE_0000000025
	KSTREAM_MERGE_0000000025 --> KSTREAM_MAPVALUES_0000000026
	KSTREAM_MAPVALUES_0000000026 --> KSTREAM_KEY_SELECT_0000000027
	KSTREAM_KEY_SELECT_0000000027 --> dptuple_leftjoin_saker_repartition_filter
	dptuple_leftjoin_saker_repartition_filter --> dptuple_leftjoin_saker_repartition_sink
}
package "Sub-topology: 7" {
	agent "consume-aap.utbetaling.v1" <<Source>> as consume_aap_utbetaling_v1
	agent "KSTREAM-PROCESSOR-0000000111" <<Processor>> as KSTREAM_PROCESSOR_0000000111
	agent "KSTREAM-FILTER-0000000112" <<Processor>> as KSTREAM_FILTER_0000000112
	agent "from-aap.utbetaling.v1-repartition-filter" <<Processor>> as from_aap_utbetaling_v1_repartition_filter
	agent "from-aap.utbetaling.v1-repartition-sink" <<Sink>> as from_aap_utbetaling_v1_repartition_sink
	aap_utbetaling_v1 --> consume_aap_utbetaling_v1
	from_aap_utbetaling_v1_repartition <-- from_aap_utbetaling_v1_repartition_sink
	consume_aap_utbetaling_v1 --> KSTREAM_PROCESSOR_0000000111
	KSTREAM_PROCESSOR_0000000111 --> KSTREAM_FILTER_0000000112
	KSTREAM_FILTER_0000000112 --> from_aap_utbetaling_v1_repartition_filter
	from_aap_utbetaling_v1_repartition_filter --> from_aap_utbetaling_v1_repartition_sink
}
package "Sub-topology: 8" {
	agent "consume-helved.utbetalinger-aap.v1" <<Source>> as consume_helved_utbetalinger_aap_v1
	agent "KSTREAM-PROCESSOR-0000000117" <<Processor>> as KSTREAM_PROCESSOR_0000000117
	agent "KSTREAM-FILTER-0000000118" <<Processor>> as KSTREAM_FILTER_0000000118
	agent "from-aap.utbetaling.v1-repartition-source" <<Source>> as from_aap_utbetaling_v1_repartition_source
	agent "KSTREAM-MERGE-0000000119" <<Processor>> as KSTREAM_MERGE_0000000119
	agent "KSTREAM-MAPVALUES-0000000120" <<Processor>> as KSTREAM_MAPVALUES_0000000120
	agent "KSTREAM-KEY-SELECT-0000000121" <<Processor>> as KSTREAM_KEY_SELECT_0000000121
	agent "aaptuple-leftjoin-saker-repartition-filter" <<Processor>> as aaptuple_leftjoin_saker_repartition_filter
	agent "aaptuple-leftjoin-saker-repartition-sink" <<Sink>> as aaptuple_leftjoin_saker_repartition_sink
	helved_utbetalinger_aap_v1 --> consume_helved_utbetalinger_aap_v1
	from_aap_utbetaling_v1_repartition --> from_aap_utbetaling_v1_repartition_source
	aaptuple_leftjoin_saker_repartition <-- aaptuple_leftjoin_saker_repartition_sink
	consume_helved_utbetalinger_aap_v1 --> KSTREAM_PROCESSOR_0000000117
	KSTREAM_PROCESSOR_0000000117 --> KSTREAM_FILTER_0000000118
	KSTREAM_FILTER_0000000118 --> KSTREAM_MERGE_0000000119
	from_aap_utbetaling_v1_repartition_source --> KSTREAM_MERGE_0000000119
	KSTREAM_MERGE_0000000119 --> KSTREAM_MAPVALUES_0000000120
	KSTREAM_MAPVALUES_0000000120 --> KSTREAM_KEY_SELECT_0000000121
	KSTREAM_KEY_SELECT_0000000121 --> aaptuple_leftjoin_saker_repartition_filter
	aaptuple_leftjoin_saker_repartition_filter --> aaptuple_leftjoin_saker_repartition_sink
}
package "Sub-topology: 9" {
	agent "consume-tilleggsstonader.utbetaling.v1" <<Source>> as consume_tilleggsstonader_utbetaling_v1
	agent "KSTREAM-PROCESSOR-0000000198" <<Processor>> as KSTREAM_PROCESSOR_0000000198
	agent "KSTREAM-FILTER-0000000199" <<Processor>> as KSTREAM_FILTER_0000000199
	agent "from-tilleggsstonader.utbetaling.v1-repartition-filter" <<Processor>> as from_tilleggsstonader_utbetaling_v1_repartition_filter
	agent "from-tilleggsstonader.utbetaling.v1-repartition-sink" <<Sink>> as from_tilleggsstonader_utbetaling_v1_repartition_sink
	tilleggsstonader_utbetaling_v1 --> consume_tilleggsstonader_utbetaling_v1
	from_tilleggsstonader_utbetaling_v1_repartition <-- from_tilleggsstonader_utbetaling_v1_repartition_sink
	consume_tilleggsstonader_utbetaling_v1 --> KSTREAM_PROCESSOR_0000000198
	KSTREAM_PROCESSOR_0000000198 --> KSTREAM_FILTER_0000000199
	KSTREAM_FILTER_0000000199 --> from_tilleggsstonader_utbetaling_v1_repartition_filter
	from_tilleggsstonader_utbetaling_v1_repartition_filter --> from_tilleggsstonader_utbetaling_v1_repartition_sink
}
package "Sub-topology: 10" {
	agent "consume-helved.utbetalinger-ts.v1" <<Source>> as consume_helved_utbetalinger_ts_v1
	agent "KSTREAM-PROCESSOR-0000000204" <<Processor>> as KSTREAM_PROCESSOR_0000000204
	agent "KSTREAM-FILTER-0000000205" <<Processor>> as KSTREAM_FILTER_0000000205
	agent "from-tilleggsstonader.utbetaling.v1-repartition-source" <<Source>> as from_tilleggsstonader_utbetaling_v1_repartition_source
	agent "KSTREAM-MERGE-0000000206" <<Processor>> as KSTREAM_MERGE_0000000206
	agent "KSTREAM-MAPVALUES-0000000207" <<Processor>> as KSTREAM_MAPVALUES_0000000207
	agent "KSTREAM-KEY-SELECT-0000000208" <<Processor>> as KSTREAM_KEY_SELECT_0000000208
	agent "tstuple-leftjoin-saker-repartition-filter" <<Processor>> as tstuple_leftjoin_saker_repartition_filter
	agent "tstuple-leftjoin-saker-repartition-sink" <<Sink>> as tstuple_leftjoin_saker_repartition_sink
	helved_utbetalinger_ts_v1 --> consume_helved_utbetalinger_ts_v1
	from_tilleggsstonader_utbetaling_v1_repartition --> from_tilleggsstonader_utbetaling_v1_repartition_source
	tstuple_leftjoin_saker_repartition <-- tstuple_leftjoin_saker_repartition_sink
	consume_helved_utbetalinger_ts_v1 --> KSTREAM_PROCESSOR_0000000204
	KSTREAM_PROCESSOR_0000000204 --> KSTREAM_FILTER_0000000205
	KSTREAM_FILTER_0000000205 --> KSTREAM_MERGE_0000000206
	from_tilleggsstonader_utbetaling_v1_repartition_source --> KSTREAM_MERGE_0000000206
	KSTREAM_MERGE_0000000206 --> KSTREAM_MAPVALUES_0000000207
	KSTREAM_MAPVALUES_0000000207 --> KSTREAM_KEY_SELECT_0000000208
	KSTREAM_KEY_SELECT_0000000208 --> tstuple_leftjoin_saker_repartition_filter
	tstuple_leftjoin_saker_repartition_filter --> tstuple_leftjoin_saker_repartition_sink
}
package "Sub-topology: 11" {
	agent "consume-helved.utbetalinger-tp.v1" <<Source>> as consume_helved_utbetalinger_tp_v1
	agent "KSTREAM-PROCESSOR-0000000290" <<Processor>> as KSTREAM_PROCESSOR_0000000290
	agent "KSTREAM-FILTER-0000000291" <<Processor>> as KSTREAM_FILTER_0000000291
	agent "KSTREAM-MAPVALUES-0000000292" <<Processor>> as KSTREAM_MAPVALUES_0000000292
	agent "KSTREAM-KEY-SELECT-0000000293" <<Processor>> as KSTREAM_KEY_SELECT_0000000293
	agent "tptuple-leftjoin-saker-repartition-filter" <<Processor>> as tptuple_leftjoin_saker_repartition_filter
	agent "tptuple-leftjoin-saker-repartition-sink" <<Sink>> as tptuple_leftjoin_saker_repartition_sink
	helved_utbetalinger_tp_v1 --> consume_helved_utbetalinger_tp_v1
	tptuple_leftjoin_saker_repartition <-- tptuple_leftjoin_saker_repartition_sink
	consume_helved_utbetalinger_tp_v1 --> KSTREAM_PROCESSOR_0000000290
	KSTREAM_PROCESSOR_0000000290 --> KSTREAM_FILTER_0000000291
	KSTREAM_FILTER_0000000291 --> KSTREAM_MAPVALUES_0000000292
	KSTREAM_MAPVALUES_0000000292 --> KSTREAM_KEY_SELECT_0000000293
	KSTREAM_KEY_SELECT_0000000293 --> tptuple_leftjoin_saker_repartition_filter
	tptuple_leftjoin_saker_repartition_filter --> tptuple_leftjoin_saker_repartition_sink
}
package "Sub-topology: 12" {
	agent "consume-historisk.utbetaling.v1" <<Source>> as consume_historisk_utbetaling_v1
	agent "KSTREAM-PROCESSOR-0000000370" <<Processor>> as KSTREAM_PROCESSOR_0000000370
	agent "KSTREAM-FILTER-0000000371" <<Processor>> as KSTREAM_FILTER_0000000371
	agent "from-historisk.utbetaling.v1-repartition-filter" <<Processor>> as from_historisk_utbetaling_v1_repartition_filter
	agent "from-historisk.utbetaling.v1-repartition-sink" <<Sink>> as from_historisk_utbetaling_v1_repartition_sink
	historisk_utbetaling_v1 --> consume_historisk_utbetaling_v1
	from_historisk_utbetaling_v1_repartition <-- from_historisk_utbetaling_v1_repartition_sink
	consume_historisk_utbetaling_v1 --> KSTREAM_PROCESSOR_0000000370
	KSTREAM_PROCESSOR_0000000370 --> KSTREAM_FILTER_0000000371
	KSTREAM_FILTER_0000000371 --> from_historisk_utbetaling_v1_repartition_filter
	from_historisk_utbetaling_v1_repartition_filter --> from_historisk_utbetaling_v1_repartition_sink
}
package "Sub-topology: 13" {
	agent "consume-helved.utbetalinger-historisk.v1" <<Source>> as consume_helved_utbetalinger_historisk_v1
	agent "KSTREAM-PROCESSOR-0000000376" <<Processor>> as KSTREAM_PROCESSOR_0000000376
	agent "KSTREAM-FILTER-0000000377" <<Processor>> as KSTREAM_FILTER_0000000377
	agent "from-historisk.utbetaling.v1-repartition-source" <<Source>> as from_historisk_utbetaling_v1_repartition_source
	agent "KSTREAM-MERGE-0000000378" <<Processor>> as KSTREAM_MERGE_0000000378
	agent "KSTREAM-MAPVALUES-0000000379" <<Processor>> as KSTREAM_MAPVALUES_0000000379
	agent "KSTREAM-KEY-SELECT-0000000380" <<Processor>> as KSTREAM_KEY_SELECT_0000000380
	agent "historisktuple-leftjoin-saker-repartition-filter" <<Processor>> as historisktuple_leftjoin_saker_repartition_filter
	agent "historisktuple-leftjoin-saker-repartition-sink" <<Sink>> as historisktuple_leftjoin_saker_repartition_sink
	helved_utbetalinger_historisk_v1 --> consume_helved_utbetalinger_historisk_v1
	from_historisk_utbetaling_v1_repartition --> from_historisk_utbetaling_v1_repartition_source
	historisktuple_leftjoin_saker_repartition <-- historisktuple_leftjoin_saker_repartition_sink
	consume_helved_utbetalinger_historisk_v1 --> KSTREAM_PROCESSOR_0000000376
	KSTREAM_PROCESSOR_0000000376 --> KSTREAM_FILTER_0000000377
	KSTREAM_FILTER_0000000377 --> KSTREAM_MERGE_0000000378
	from_historisk_utbetaling_v1_repartition_source --> KSTREAM_MERGE_0000000378
	KSTREAM_MERGE_0000000378 --> KSTREAM_MAPVALUES_0000000379
	KSTREAM_MAPVALUES_0000000379 --> KSTREAM_KEY_SELECT_0000000380
	KSTREAM_KEY_SELECT_0000000380 --> historisktuple_leftjoin_saker_repartition_filter
	historisktuple_leftjoin_saker_repartition_filter --> historisktuple_leftjoin_saker_repartition_sink
}
package "Sub-topology: 14" {
	agent "consume-helved.oppdrag.v1" <<Source>> as consume_helved_oppdrag_v1
	agent "consume-helved.retry-oppdrag.v1" <<Source>> as consume_helved_retry_oppdrag_v1
	agent "KSTREAM-PROCESSOR-0000000457" <<Processor>> as KSTREAM_PROCESSOR_0000000457
	agent "KSTREAM-PROCESSOR-0000000460" <<Processor>> as KSTREAM_PROCESSOR_0000000460
	agent "KSTREAM-FILTER-0000000458" <<Processor>> as KSTREAM_FILTER_0000000458
	agent "KSTREAM-FILTER-0000000461" <<Processor>> as KSTREAM_FILTER_0000000461
	agent "KSTREAM-MERGE-0000000462" <<Processor>> as KSTREAM_MERGE_0000000462
	agent "KSTREAM-PROCESSOR-0000000463" <<Processor>> as KSTREAM_PROCESSOR_0000000463
	agent "KSTREAM-FILTER-0000000464" <<Processor>> as KSTREAM_FILTER_0000000464
	agent "KSTREAM-FLATMAP-0000000465" <<Processor>> as KSTREAM_FLATMAP_0000000465
	agent "pk-leftjoin-pending-repartition-filter" <<Processor>> as pk_leftjoin_pending_repartition_filter
	agent "pk-leftjoin-pending-repartition-sink" <<Sink>> as pk_leftjoin_pending_repartition_sink
	helved_oppdrag_v1 --> consume_helved_oppdrag_v1
	helved_retry_oppdrag_v1 --> consume_helved_retry_oppdrag_v1
	pk_leftjoin_pending_repartition <-- pk_leftjoin_pending_repartition_sink
	consume_helved_oppdrag_v1 --> KSTREAM_PROCESSOR_0000000457
	consume_helved_retry_oppdrag_v1 --> KSTREAM_PROCESSOR_0000000460
	KSTREAM_PROCESSOR_0000000457 --> KSTREAM_FILTER_0000000458
	KSTREAM_PROCESSOR_0000000460 --> KSTREAM_FILTER_0000000461
	KSTREAM_FILTER_0000000458 --> KSTREAM_MERGE_0000000462
	KSTREAM_FILTER_0000000461 --> KSTREAM_MERGE_0000000462
	KSTREAM_MERGE_0000000462 --> KSTREAM_PROCESSOR_0000000463
	KSTREAM_PROCESSOR_0000000463 --> KSTREAM_FILTER_0000000464
	KSTREAM_FILTER_0000000464 --> KSTREAM_FLATMAP_0000000465
	KSTREAM_FLATMAP_0000000465 --> pk_leftjoin_pending_repartition_filter
	pk_leftjoin_pending_repartition_filter --> pk_leftjoin_pending_repartition_sink
}
@enduml