@startuml
!theme black-knight
queue "consume-helved.utbetalinger.v1-state-store-groupByKey-aggregate-store-repartition" <<topic>> as consume_helved_utbetalinger_v1_state_store_groupByKey_aggregate_store_repartition
queue "suppress-from-teamdagpenger.utbetaling.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-session-window-aggregate-repartition" <<topic>> as suppress_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_aggregate_repartition
queue "helved.utbetalinger.v1" <<topic>> as helved_utbetalinger_v1
queue "from-teamdagpenger.utbetaling.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-repartition" <<topic>> as from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_repartition
queue "helved.saker.v1" <<topic>> as helved_saker_v1
queue "from-teamdagpenger.utbetaling.v1-left-join-helved.saker.v1-repartition" <<topic>> as from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_repartition
queue "from-teamdagpenger.utbetaling.v1-repartition" <<topic>> as from_teamdagpenger_utbetaling_v1_repartition
queue "teamdagpenger.utbetaling.v1" <<topic>> as teamdagpenger_utbetaling_v1
queue "helved.oppdrag.v1" <<topic>> as helved_oppdrag_v1
queue "helved.simuleringer.v1" <<topic>> as helved_simuleringer_v1
queue "helved.status.v1" <<topic>> as helved_status_v1
package "Sub-topology: 0" {
	database "helved.utbetalinger.v1-state-store" <<State Store>> as helved_utbetalinger_v1_state_store
	agent "consume-helved.utbetalinger.v1" <<Source>> as consume_helved_utbetalinger_v1
	agent "stateless-operation-log-consume-helved.utbetalinger.v1" <<Processor>> as stateless_operation_log_consume_helved_utbetalinger_v1
	agent "from-teamdagpenger.utbetaling.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-repartition-source" <<Source>> as from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_repartition_source
	agent "stateless-operation-log-produced-helved.utbetalinger.v1" <<Processor>> as stateless_operation_log_produced_helved_utbetalinger_v1
	agent "from-teamdagpenger.utbetaling.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1" <<Processor>> as from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	agent "helved.utbetalinger.v1-to-table" <<Processor>> as helved_utbetalinger_v1_to_table
	agent "KSTREAM-FILTER-0000000028" <<Processor>> as KSTREAM_FILTER_0000000028
	agent "KTABLE-TOSTREAM-0000000002" <<Processor>> as KTABLE_TOSTREAM_0000000002
	agent "KSTREAM-KEY-SELECT-0000000029" <<Processor>> as KSTREAM_KEY_SELECT_0000000029
	agent "skip-helved.utbetalinger.v1-tombstoneto-stream" <<Processor>> as skip_helved_utbetalinger_v1_tombstoneto_stream
	agent "KSTREAM-KEY-SELECT-0000000004" <<Processor>> as KSTREAM_KEY_SELECT_0000000004
	agent "KSTREAM-MAPVALUES-0000000030" <<Processor>> as KSTREAM_MAPVALUES_0000000030
	agent "consume-helved.utbetalinger.v1-state-store-groupByKey-aggregate-store-repartition-filter" <<Processor>> as consume_helved_utbetalinger_v1_state_store_groupByKey_aggregate_store_repartition_filter
	agent "suppress-from-teamdagpenger.utbetaling.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-session-window-aggregate-repartition-filter" <<Processor>> as suppress_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_aggregate_repartition_filter
	agent "consume-helved.utbetalinger.v1-state-store-groupByKey-aggregate-store-repartition-sink" <<Sink>> as consume_helved_utbetalinger_v1_state_store_groupByKey_aggregate_store_repartition_sink
	agent "suppress-from-teamdagpenger.utbetaling.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-session-window-aggregate-repartition-sink" <<Sink>> as suppress_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_aggregate_repartition_sink
	helved_utbetalinger_v1 --> consume_helved_utbetalinger_v1
	from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_repartition --> from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_repartition_source
	helved_utbetalinger_v1_state_store -- from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	helved_utbetalinger_v1_state_store -- helved_utbetalinger_v1_to_table
	consume_helved_utbetalinger_v1_state_store_groupByKey_aggregate_store_repartition <-- consume_helved_utbetalinger_v1_state_store_groupByKey_aggregate_store_repartition_sink
	suppress_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_aggregate_repartition <-- suppress_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_aggregate_repartition_sink
	consume_helved_utbetalinger_v1 --> stateless_operation_log_consume_helved_utbetalinger_v1
	stateless_operation_log_consume_helved_utbetalinger_v1 --> stateless_operation_log_produced_helved_utbetalinger_v1
	from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_repartition_source --> from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	stateless_operation_log_produced_helved_utbetalinger_v1 --> helved_utbetalinger_v1_to_table
	from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1 --> KSTREAM_FILTER_0000000028
	helved_utbetalinger_v1_to_table --> KTABLE_TOSTREAM_0000000002
	KSTREAM_FILTER_0000000028 --> KSTREAM_KEY_SELECT_0000000029
	KTABLE_TOSTREAM_0000000002 --> skip_helved_utbetalinger_v1_tombstoneto_stream
	KSTREAM_KEY_SELECT_0000000029 --> KSTREAM_MAPVALUES_0000000030
	skip_helved_utbetalinger_v1_tombstoneto_stream --> KSTREAM_KEY_SELECT_0000000004
	KSTREAM_KEY_SELECT_0000000004 --> consume_helved_utbetalinger_v1_state_store_groupByKey_aggregate_store_repartition_filter
	KSTREAM_MAPVALUES_0000000030 --> suppress_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_aggregate_repartition_filter
	consume_helved_utbetalinger_v1_state_store_groupByKey_aggregate_store_repartition_filter --> consume_helved_utbetalinger_v1_state_store_groupByKey_aggregate_store_repartition_sink
	suppress_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_aggregate_repartition_filter --> suppress_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_aggregate_repartition_sink
}
package "Sub-topology: 1" {
	database "consume-helved.utbetalinger.v1-state-store-groupByKey-aggregate-store" <<State Store>> as consume_helved_utbetalinger_v1_state_store_groupByKey_aggregate_store
	agent "consume-helved.utbetalinger.v1-state-store-groupByKey-aggregate-store-repartition-source" <<Source>> as consume_helved_utbetalinger_v1_state_store_groupByKey_aggregate_store_repartition_source
	agent "KSTREAM-AGGREGATE-0000000005" <<Processor>> as KSTREAM_AGGREGATE_0000000005
	agent "from-teamdagpenger.utbetaling.v1-left-join-helved.saker.v1-repartition-source" <<Source>> as from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_repartition_source
	agent "KTABLE-TOSTREAM-0000000009" <<Processor>> as KTABLE_TOSTREAM_0000000009
	agent "from-teamdagpenger.utbetaling.v1-left-join-helved.saker.v1" <<Processor>> as from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1
	agent "KSTREAM-FLATMAP-0000000023" <<Processor>> as KSTREAM_FLATMAP_0000000023
	agent "skip-helved.saker.v1-tombstoneto-stream" <<Processor>> as skip_helved_saker_v1_tombstoneto_stream
	agent "from-teamdagpenger.utbetaling.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-repartition-filter" <<Processor>> as from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_repartition_filter
	agent "stateless-operation-log-produced-helved.saker.v1-consume-helved.saker.v1-state-store" <<Processor>> as stateless_operation_log_produced_helved_saker_v1_consume_helved_saker_v1_state_store
	agent "from-teamdagpenger.utbetaling.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-repartition-sink" <<Sink>> as from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_repartition_sink
	agent "produced-helved.saker.v1-consume-helved.saker.v1-state-store" <<Sink>> as produced_helved_saker_v1_consume_helved_saker_v1_state_store
	consume_helved_utbetalinger_v1_state_store_groupByKey_aggregate_store_repartition --> consume_helved_utbetalinger_v1_state_store_groupByKey_aggregate_store_repartition_source
	consume_helved_utbetalinger_v1_state_store_groupByKey_aggregate_store -- KSTREAM_AGGREGATE_0000000005
	from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_repartition --> from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_repartition_source
	consume_helved_utbetalinger_v1_state_store_groupByKey_aggregate_store -- from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1
	from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_repartition <-- from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_repartition_sink
	helved_saker_v1 <-- produced_helved_saker_v1_consume_helved_saker_v1_state_store
	consume_helved_utbetalinger_v1_state_store_groupByKey_aggregate_store_repartition_source --> KSTREAM_AGGREGATE_0000000005
	KSTREAM_AGGREGATE_0000000005 --> KTABLE_TOSTREAM_0000000009
	from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_repartition_source --> from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1
	KTABLE_TOSTREAM_0000000009 --> skip_helved_saker_v1_tombstoneto_stream
	from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1 --> KSTREAM_FLATMAP_0000000023
	KSTREAM_FLATMAP_0000000023 --> from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_repartition_filter
	skip_helved_saker_v1_tombstoneto_stream --> stateless_operation_log_produced_helved_saker_v1_consume_helved_saker_v1_state_store
	from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_repartition_filter --> from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_repartition_sink
	stateless_operation_log_produced_helved_saker_v1_consume_helved_saker_v1_state_store --> produced_helved_saker_v1_consume_helved_saker_v1_state_store
}
package "Sub-topology: 2" {
	agent "consume-teamdagpenger.utbetaling.v1" <<Source>> as consume_teamdagpenger_utbetaling_v1
	agent "stateless-operation-log-consume-teamdagpenger.utbetaling.v1" <<Processor>> as stateless_operation_log_consume_teamdagpenger_utbetaling_v1
	agent "skip-teamdagpenger.utbetaling.v1-tombstone" <<Processor>> as skip_teamdagpenger_utbetaling_v1_tombstone
	agent "from-teamdagpenger.utbetaling.v1-repartition-filter" <<Processor>> as from_teamdagpenger_utbetaling_v1_repartition_filter
	agent "from-teamdagpenger.utbetaling.v1-repartition-sink" <<Sink>> as from_teamdagpenger_utbetaling_v1_repartition_sink
	teamdagpenger_utbetaling_v1 --> consume_teamdagpenger_utbetaling_v1
	from_teamdagpenger_utbetaling_v1_repartition <-- from_teamdagpenger_utbetaling_v1_repartition_sink
	consume_teamdagpenger_utbetaling_v1 --> stateless_operation_log_consume_teamdagpenger_utbetaling_v1
	stateless_operation_log_consume_teamdagpenger_utbetaling_v1 --> skip_teamdagpenger_utbetaling_v1_tombstone
	skip_teamdagpenger_utbetaling_v1_tombstone --> from_teamdagpenger_utbetaling_v1_repartition_filter
	from_teamdagpenger_utbetaling_v1_repartition_filter --> from_teamdagpenger_utbetaling_v1_repartition_sink
}
package "Sub-topology: 3" {
	agent "from-teamdagpenger.utbetaling.v1-repartition-source" <<Source>> as from_teamdagpenger_utbetaling_v1_repartition_source
	agent "KSTREAM-MAPVALUES-0000000017" <<Processor>> as KSTREAM_MAPVALUES_0000000017
	agent "KSTREAM-KEY-SELECT-0000000018" <<Processor>> as KSTREAM_KEY_SELECT_0000000018
	agent "from-teamdagpenger.utbetaling.v1-left-join-helved.saker.v1-repartition-filter" <<Processor>> as from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_repartition_filter
	agent "from-teamdagpenger.utbetaling.v1-left-join-helved.saker.v1-repartition-sink" <<Sink>> as from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_repartition_sink
	from_teamdagpenger_utbetaling_v1_repartition --> from_teamdagpenger_utbetaling_v1_repartition_source
	from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_repartition <-- from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_repartition_sink
	from_teamdagpenger_utbetaling_v1_repartition_source --> KSTREAM_MAPVALUES_0000000017
	KSTREAM_MAPVALUES_0000000017 --> KSTREAM_KEY_SELECT_0000000018
	KSTREAM_KEY_SELECT_0000000018 --> from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_repartition_filter
	from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_repartition_filter --> from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_repartition_sink
}
package "Sub-topology: 4" {
	database "suppress-from-teamdagpenger.utbetaling.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-session-window-aggregate" <<State Store>> as suppress_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_aggregate
	database "dp-diff-window-agg-session-store" <<State Store>> as dp_diff_window_agg_session_store
	agent "suppress-from-teamdagpenger.utbetaling.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-session-window-aggregate-repartition-source" <<Source>> as suppress_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_aggregate_repartition_source
	agent "from-teamdagpenger.utbetaling.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-session-window-operation-reduced" <<Processor>> as from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_operation_reduced
	agent "KTABLE-TOSTREAM-0000000035" <<Processor>> as KTABLE_TOSTREAM_0000000035
	agent "suppress-from-teamdagpenger.utbetaling.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-session-window" <<Processor>> as suppress_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window
	agent "KSTREAM-KEY-SELECT-0000000036" <<Processor>> as KSTREAM_KEY_SELECT_0000000036
	agent "KSTREAM-MAPVALUES-0000000037" <<Processor>> as KSTREAM_MAPVALUES_0000000037
	agent "split-from-teamdagpenger.utbetaling.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-session-window-reduced" <<Processor>> as split_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced
	agent "split-from-teamdagpenger.utbetaling.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-session-window-reduced-branch-1" <<Processor>> as split_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced_branch_1
	agent "KSTREAM-MAPVALUES-0000000040" <<Processor>> as KSTREAM_MAPVALUES_0000000040
	agent "KSTREAM-FLATMAPVALUES-0000000045" <<Processor>> as KSTREAM_FLATMAPVALUES_0000000045
	agent "split-from-teamdagpenger.utbetaling.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-session-window-reduced-branch-default" <<Processor>> as split_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced_branch_default
	agent "KSTREAM-FLATMAP-0000000041" <<Processor>> as KSTREAM_FLATMAP_0000000041
	agent "KSTREAM-FLATMAPVALUES-0000000043" <<Processor>> as KSTREAM_FLATMAPVALUES_0000000043
	agent "KSTREAM-MAPVALUES-0000000047" <<Processor>> as KSTREAM_MAPVALUES_0000000047
	agent "KSTREAM-MAPVALUES-0000000050" <<Processor>> as KSTREAM_MAPVALUES_0000000050
	agent "stateless-operation-log-produced-helved.oppdrag.v1-via-branch-1-from-teamdagpenger.utbetaling.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-session-window-reduced" <<Processor>> as stateless_operation_log_produced_helved_oppdrag_v1_via_branch_1_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced
	agent "stateless-operation-log-produced-helved.simuleringer.v1-via-branch-1-from-teamdagpenger.utbetaling.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-session-window-reduced" <<Processor>> as stateless_operation_log_produced_helved_simuleringer_v1_via_branch_1_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced
	agent "stateless-operation-log-produced-helved.status.v1-via-branch-1-from-teamdagpenger.utbetaling.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-session-window-reduced" <<Processor>> as stateless_operation_log_produced_helved_status_v1_via_branch_1_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced
	agent "stateless-operation-log-produced-helved.status.v1-via-branch-default-from-teamdagpenger.utbetaling.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-session-window-reduced" <<Processor>> as stateless_operation_log_produced_helved_status_v1_via_branch_default_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced
	agent "stateless-operation-log-produced-helved.utbetalinger.v1-via-branch-1-from-teamdagpenger.utbetaling.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-session-window-reduced" <<Processor>> as stateless_operation_log_produced_helved_utbetalinger_v1_via_branch_1_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced
	agent "produced-helved.oppdrag.v1-via-branch-1-from-teamdagpenger.utbetaling.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-session-window-reduced" <<Sink>> as produced_helved_oppdrag_v1_via_branch_1_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced
	agent "produced-helved.simuleringer.v1-via-branch-1-from-teamdagpenger.utbetaling.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-session-window-reduced" <<Sink>> as produced_helved_simuleringer_v1_via_branch_1_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced
	agent "produced-helved.status.v1-via-branch-1-from-teamdagpenger.utbetaling.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-session-window-reduced" <<Sink>> as produced_helved_status_v1_via_branch_1_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced
	agent "produced-helved.status.v1-via-branch-default-from-teamdagpenger.utbetaling.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-session-window-reduced" <<Sink>> as produced_helved_status_v1_via_branch_default_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced
	agent "produced-helved.utbetalinger.v1-via-branch-1-from-teamdagpenger.utbetaling.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-session-window-reduced" <<Sink>> as produced_helved_utbetalinger_v1_via_branch_1_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced
	suppress_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_aggregate_repartition --> suppress_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_aggregate_repartition_source
	suppress_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_aggregate -- from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_operation_reduced
	dp_diff_window_agg_session_store -- suppress_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window
	helved_oppdrag_v1 <-- produced_helved_oppdrag_v1_via_branch_1_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced
	helved_simuleringer_v1 <-- produced_helved_simuleringer_v1_via_branch_1_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced
	helved_status_v1 <-- produced_helved_status_v1_via_branch_1_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced
	helved_status_v1 <-- produced_helved_status_v1_via_branch_default_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced
	helved_utbetalinger_v1 <-- produced_helved_utbetalinger_v1_via_branch_1_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced
	suppress_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_aggregate_repartition_source --> from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_operation_reduced
	from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_operation_reduced --> KTABLE_TOSTREAM_0000000035
	KTABLE_TOSTREAM_0000000035 --> suppress_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window
	suppress_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window --> KSTREAM_KEY_SELECT_0000000036
	KSTREAM_KEY_SELECT_0000000036 --> KSTREAM_MAPVALUES_0000000037
	KSTREAM_MAPVALUES_0000000037 --> split_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced
	split_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced --> split_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced_branch_1
	split_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced --> split_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced_branch_default
	split_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced_branch_1 --> KSTREAM_MAPVALUES_0000000040
	KSTREAM_MAPVALUES_0000000040 --> KSTREAM_FLATMAP_0000000041
	KSTREAM_MAPVALUES_0000000040 --> KSTREAM_FLATMAPVALUES_0000000045
	KSTREAM_MAPVALUES_0000000040 --> KSTREAM_FLATMAPVALUES_0000000043
	KSTREAM_FLATMAPVALUES_0000000045 --> stateless_operation_log_produced_helved_oppdrag_v1_via_branch_1_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced
	KSTREAM_FLATMAPVALUES_0000000045 --> KSTREAM_MAPVALUES_0000000047
	split_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced_branch_default --> KSTREAM_MAPVALUES_0000000050
	KSTREAM_FLATMAP_0000000041 --> stateless_operation_log_produced_helved_utbetalinger_v1_via_branch_1_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced
	KSTREAM_FLATMAPVALUES_0000000043 --> stateless_operation_log_produced_helved_simuleringer_v1_via_branch_1_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced
	KSTREAM_MAPVALUES_0000000047 --> stateless_operation_log_produced_helved_status_v1_via_branch_1_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced
	KSTREAM_MAPVALUES_0000000050 --> stateless_operation_log_produced_helved_status_v1_via_branch_default_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced
	stateless_operation_log_produced_helved_oppdrag_v1_via_branch_1_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced --> produced_helved_oppdrag_v1_via_branch_1_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced
	stateless_operation_log_produced_helved_simuleringer_v1_via_branch_1_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced --> produced_helved_simuleringer_v1_via_branch_1_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced
	stateless_operation_log_produced_helved_status_v1_via_branch_1_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced --> produced_helved_status_v1_via_branch_1_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced
	stateless_operation_log_produced_helved_status_v1_via_branch_default_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced --> produced_helved_status_v1_via_branch_default_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced
	stateless_operation_log_produced_helved_utbetalinger_v1_via_branch_1_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced --> produced_helved_utbetalinger_v1_via_branch_1_from_teamdagpenger_utbetaling_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_session_window_reduced
}
package "Sub-topology: 5" {
	database "helved.saker.v1-state-store" <<State Store>> as helved_saker_v1_state_store
	agent "consume-helved.saker.v1" <<Source>> as consume_helved_saker_v1
	agent "stateless-operation-log-consume-helved.saker.v1" <<Processor>> as stateless_operation_log_consume_helved_saker_v1
	agent "stateless-operation-log-produced-helved.saker.v1" <<Processor>> as stateless_operation_log_produced_helved_saker_v1
	agent "helved.saker.v1-to-table" <<Processor>> as helved_saker_v1_to_table
	helved_saker_v1 --> consume_helved_saker_v1
	helved_saker_v1_state_store -- helved_saker_v1_to_table
	consume_helved_saker_v1 --> stateless_operation_log_consume_helved_saker_v1
	stateless_operation_log_consume_helved_saker_v1 --> stateless_operation_log_produced_helved_saker_v1
	stateless_operation_log_produced_helved_saker_v1 --> helved_saker_v1_to_table
}
@enduml