@startuml
!theme black-knight
queue "consume-helved.utbetalinger.v1-state-store-left-join-helved.saker.v1-repartition" <<topic>> as consume_helved_utbetalinger_v1_state_store_left_join_helved_saker_v1_repartition
queue "helved.oppdrag.v1" <<topic>> as helved_oppdrag_v1
queue "helved.simulering.v1" <<topic>> as helved_simulering_v1
queue "helved.status.v1" <<topic>> as helved_status_v1
queue "helved.utbetalinger.v1" <<topic>> as helved_utbetalinger_v1
queue "from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-repartition" <<topic>> as from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_repartition
queue "helved.saker.v1" <<topic>> as helved_saker_v1
queue "from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1-repartition" <<topic>> as from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_repartition
queue "helved.aap-utbetalinger.v1" <<topic>> as helved_aap_utbetalinger_v1
package "Sub-topology: 0" {
	database "helved.utbetalinger.v1-state-store" <<State Store>> as helved_utbetalinger_v1_state_store
	agent "from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-repartition-source" <<Source>> as from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_repartition_source
	agent "from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1" <<Processor>> as from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	agent "split-from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1" <<Processor>> as split_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	agent "split-from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-branch-default" <<Processor>> as split_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_branch_default
	agent "KSTREAM-MAPVALUES-0000000031" <<Processor>> as KSTREAM_MAPVALUES_0000000031
	agent "split-via-branch-default-from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1" <<Processor>> as split_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	agent "split-from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-branch-1" <<Processor>> as split_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_branch_1
	agent "KSTREAM-MAPVALUES-0000000020" <<Processor>> as KSTREAM_MAPVALUES_0000000020
	agent "split-via-branch-1-from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1" <<Processor>> as split_via_branch_1_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	agent "split-via-branch-default-from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-branch-1" <<Processor>> as split_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_branch_1
	agent "KSTREAM-MAPVALUES-0000000034" <<Processor>> as KSTREAM_MAPVALUES_0000000034
	agent "consume-helved.utbetalinger.v1" <<Source>> as consume_helved_utbetalinger_v1
	agent "stateless-operation-log-consume-helved.utbetalinger.v1" <<Processor>> as stateless_operation_log_consume_helved_utbetalinger_v1
	agent "stateless-operation-log-produced-helved.utbetalinger.v1" <<Processor>> as stateless_operation_log_produced_helved_utbetalinger_v1
	agent "helved.utbetalinger.v1-to-table" <<Processor>> as helved_utbetalinger_v1_to_table
	agent "split-via-branch-1-from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-branch-1" <<Processor>> as split_via_branch_1_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_branch_1
	agent "KSTREAM-MAPVALUES-0000000023" <<Processor>> as KSTREAM_MAPVALUES_0000000023
	agent "KTABLE-TOSTREAM-0000000044" <<Processor>> as KTABLE_TOSTREAM_0000000044
	agent "skip-helved.utbetalinger.v1-tombstoneto-stream" <<Processor>> as skip_helved_utbetalinger_v1_tombstoneto_stream
	agent "KSTREAM-MAPVALUES-0000000046" <<Processor>> as KSTREAM_MAPVALUES_0000000046
	agent "split-via-branch-1-from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-branch-default" <<Processor>> as split_via_branch_1_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_branch_default
	agent "split-via-branch-default-from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-branch-default" <<Processor>> as split_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_branch_default
	agent "KSTREAM-KEY-SELECT-0000000047" <<Processor>> as KSTREAM_KEY_SELECT_0000000047
	agent "KSTREAM-MAPVALUES-0000000024" <<Processor>> as KSTREAM_MAPVALUES_0000000024
	agent "KSTREAM-MAPVALUES-0000000028" <<Processor>> as KSTREAM_MAPVALUES_0000000028
	agent "KSTREAM-MAPVALUES-0000000035" <<Processor>> as KSTREAM_MAPVALUES_0000000035
	agent "KSTREAM-MAPVALUES-0000000037" <<Processor>> as KSTREAM_MAPVALUES_0000000037
	agent "KSTREAM-MAPVALUES-0000000039" <<Processor>> as KSTREAM_MAPVALUES_0000000039
	agent "KSTREAM-MAPVALUES-0000000042" <<Processor>> as KSTREAM_MAPVALUES_0000000042
	agent "consume-helved.utbetalinger.v1-state-store-left-join-helved.saker.v1-repartition-filter" <<Processor>> as consume_helved_utbetalinger_v1_state_store_left_join_helved_saker_v1_repartition_filter
	agent "stateless-operation-log-produced-helved.oppdrag.v1-via-branch-1-via-branch-default-from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1" <<Processor>> as stateless_operation_log_produced_helved_oppdrag_v1_via_branch_1_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	agent "stateless-operation-log-produced-helved.simulering.v1-via-branch-1-via-branch-1-from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1" <<Processor>> as stateless_operation_log_produced_helved_simulering_v1_via_branch_1_via_branch_1_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	agent "stateless-operation-log-produced-helved.status.v1-via-branch-1-via-branch-1-from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1" <<Processor>> as stateless_operation_log_produced_helved_status_v1_via_branch_1_via_branch_1_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	agent "stateless-operation-log-produced-helved.status.v1-via-branch-1-via-branch-default-from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1" <<Processor>> as stateless_operation_log_produced_helved_status_v1_via_branch_1_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	agent "stateless-operation-log-produced-helved.status.v1-via-branch-default-via-branch-1-from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1" <<Processor>> as stateless_operation_log_produced_helved_status_v1_via_branch_default_via_branch_1_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	agent "stateless-operation-log-produced-helved.status.v1-via-branch-default-via-branch-default-from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1" <<Processor>> as stateless_operation_log_produced_helved_status_v1_via_branch_default_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	agent "stateless-operation-log-produced-helved.utbetalinger.v1-via-branch-1-via-branch-default-from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1" <<Processor>> as stateless_operation_log_produced_helved_utbetalinger_v1_via_branch_1_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	agent "consume-helved.utbetalinger.v1-state-store-left-join-helved.saker.v1-repartition-sink" <<Sink>> as consume_helved_utbetalinger_v1_state_store_left_join_helved_saker_v1_repartition_sink
	agent "produced-helved.oppdrag.v1-via-branch-1-via-branch-default-from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1" <<Sink>> as produced_helved_oppdrag_v1_via_branch_1_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	agent "produced-helved.simulering.v1-via-branch-1-via-branch-1-from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1" <<Sink>> as produced_helved_simulering_v1_via_branch_1_via_branch_1_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	agent "produced-helved.status.v1-via-branch-1-via-branch-1-from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1" <<Sink>> as produced_helved_status_v1_via_branch_1_via_branch_1_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	agent "produced-helved.status.v1-via-branch-1-via-branch-default-from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1" <<Sink>> as produced_helved_status_v1_via_branch_1_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	agent "produced-helved.status.v1-via-branch-default-via-branch-1-from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1" <<Sink>> as produced_helved_status_v1_via_branch_default_via_branch_1_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	agent "produced-helved.status.v1-via-branch-default-via-branch-default-from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1" <<Sink>> as produced_helved_status_v1_via_branch_default_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	agent "produced-helved.utbetalinger.v1-via-branch-1-via-branch-default-from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1" <<Sink>> as produced_helved_utbetalinger_v1_via_branch_1_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_repartition --> from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_repartition_source
	helved_utbetalinger_v1_state_store -- from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	helved_utbetalinger_v1 --> consume_helved_utbetalinger_v1
	helved_utbetalinger_v1_state_store -- helved_utbetalinger_v1_to_table
	consume_helved_utbetalinger_v1_state_store_left_join_helved_saker_v1_repartition <-- consume_helved_utbetalinger_v1_state_store_left_join_helved_saker_v1_repartition_sink
	helved_oppdrag_v1 <-- produced_helved_oppdrag_v1_via_branch_1_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	helved_simulering_v1 <-- produced_helved_simulering_v1_via_branch_1_via_branch_1_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	helved_status_v1 <-- produced_helved_status_v1_via_branch_1_via_branch_1_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	helved_status_v1 <-- produced_helved_status_v1_via_branch_1_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	helved_status_v1 <-- produced_helved_status_v1_via_branch_default_via_branch_1_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	helved_status_v1 <-- produced_helved_status_v1_via_branch_default_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	helved_utbetalinger_v1 <-- produced_helved_utbetalinger_v1_via_branch_1_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_repartition_source --> from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1 --> split_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	split_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1 --> split_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_branch_1
	split_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1 --> split_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_branch_default
	split_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_branch_default --> KSTREAM_MAPVALUES_0000000031
	KSTREAM_MAPVALUES_0000000031 --> split_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	split_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1 --> split_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_branch_1
	split_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1 --> split_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_branch_default
	split_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_branch_1 --> KSTREAM_MAPVALUES_0000000020
	KSTREAM_MAPVALUES_0000000020 --> split_via_branch_1_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	split_via_branch_1_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1 --> split_via_branch_1_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_branch_default
	split_via_branch_1_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1 --> split_via_branch_1_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_branch_1
	split_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_branch_1 --> KSTREAM_MAPVALUES_0000000034
	KSTREAM_MAPVALUES_0000000034 --> KSTREAM_MAPVALUES_0000000037
	KSTREAM_MAPVALUES_0000000034 --> KSTREAM_MAPVALUES_0000000039
	KSTREAM_MAPVALUES_0000000034 --> KSTREAM_MAPVALUES_0000000035
	consume_helved_utbetalinger_v1 --> stateless_operation_log_consume_helved_utbetalinger_v1
	stateless_operation_log_consume_helved_utbetalinger_v1 --> stateless_operation_log_produced_helved_utbetalinger_v1
	stateless_operation_log_produced_helved_utbetalinger_v1 --> helved_utbetalinger_v1_to_table
	helved_utbetalinger_v1_to_table --> KTABLE_TOSTREAM_0000000044
	split_via_branch_1_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_branch_1 --> KSTREAM_MAPVALUES_0000000023
	KSTREAM_MAPVALUES_0000000023 --> stateless_operation_log_produced_helved_simulering_v1_via_branch_1_via_branch_1_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	KSTREAM_MAPVALUES_0000000023 --> KSTREAM_MAPVALUES_0000000024
	KTABLE_TOSTREAM_0000000044 --> skip_helved_utbetalinger_v1_tombstoneto_stream
	skip_helved_utbetalinger_v1_tombstoneto_stream --> KSTREAM_MAPVALUES_0000000046
	KSTREAM_MAPVALUES_0000000046 --> KSTREAM_KEY_SELECT_0000000047
	split_via_branch_1_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_branch_default --> KSTREAM_MAPVALUES_0000000028
	split_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_branch_default --> KSTREAM_MAPVALUES_0000000042
	KSTREAM_KEY_SELECT_0000000047 --> consume_helved_utbetalinger_v1_state_store_left_join_helved_saker_v1_repartition_filter
	KSTREAM_MAPVALUES_0000000024 --> stateless_operation_log_produced_helved_status_v1_via_branch_1_via_branch_1_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	KSTREAM_MAPVALUES_0000000028 --> stateless_operation_log_produced_helved_status_v1_via_branch_default_via_branch_1_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	KSTREAM_MAPVALUES_0000000035 --> stateless_operation_log_produced_helved_utbetalinger_v1_via_branch_1_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	KSTREAM_MAPVALUES_0000000037 --> stateless_operation_log_produced_helved_oppdrag_v1_via_branch_1_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	KSTREAM_MAPVALUES_0000000039 --> stateless_operation_log_produced_helved_status_v1_via_branch_1_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	KSTREAM_MAPVALUES_0000000042 --> stateless_operation_log_produced_helved_status_v1_via_branch_default_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	consume_helved_utbetalinger_v1_state_store_left_join_helved_saker_v1_repartition_filter --> consume_helved_utbetalinger_v1_state_store_left_join_helved_saker_v1_repartition_sink
	stateless_operation_log_produced_helved_oppdrag_v1_via_branch_1_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1 --> produced_helved_oppdrag_v1_via_branch_1_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	stateless_operation_log_produced_helved_simulering_v1_via_branch_1_via_branch_1_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1 --> produced_helved_simulering_v1_via_branch_1_via_branch_1_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	stateless_operation_log_produced_helved_status_v1_via_branch_1_via_branch_1_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1 --> produced_helved_status_v1_via_branch_1_via_branch_1_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	stateless_operation_log_produced_helved_status_v1_via_branch_1_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1 --> produced_helved_status_v1_via_branch_1_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	stateless_operation_log_produced_helved_status_v1_via_branch_default_via_branch_1_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1 --> produced_helved_status_v1_via_branch_default_via_branch_1_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	stateless_operation_log_produced_helved_status_v1_via_branch_default_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1 --> produced_helved_status_v1_via_branch_default_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
	stateless_operation_log_produced_helved_utbetalinger_v1_via_branch_1_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1 --> produced_helved_utbetalinger_v1_via_branch_1_via_branch_default_from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1
}
package "Sub-topology: 1" {
	database "helved.saker.v1-state-store" <<State Store>> as helved_saker_v1_state_store
	agent "from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1-repartition-source" <<Source>> as from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_repartition_source
	agent "consume-helved.utbetalinger.v1-state-store-left-join-helved.saker.v1-repartition-source" <<Source>> as consume_helved_utbetalinger_v1_state_store_left_join_helved_saker_v1_repartition_source
	agent "from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1" <<Processor>> as from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1
	agent "KSTREAM-MAPVALUES-0000000012" <<Processor>> as KSTREAM_MAPVALUES_0000000012
	agent "consume-helved.saker.v1" <<Source>> as consume_helved_saker_v1
	agent "consume-helved.utbetalinger.v1-state-store-left-join-helved.saker.v1" <<Processor>> as consume_helved_utbetalinger_v1_state_store_left_join_helved_saker_v1
	agent "KSTREAM-KEY-SELECT-0000000013" <<Processor>> as KSTREAM_KEY_SELECT_0000000013
	agent "KSTREAM-MAPVALUES-0000000052" <<Processor>> as KSTREAM_MAPVALUES_0000000052
	agent "stateless-operation-log-consume-helved.saker.v1" <<Processor>> as stateless_operation_log_consume_helved_saker_v1
	agent "from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-repartition-filter" <<Processor>> as from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_repartition_filter
	agent "stateless-operation-log-produced-helved.saker.v1" <<Processor>> as stateless_operation_log_produced_helved_saker_v1
	agent "stateless-operation-log-produced-helved.saker.v1-consume-helved.utbetalinger.v1-state-store-left-join-helved.saker.v1" <<Processor>> as stateless_operation_log_produced_helved_saker_v1_consume_helved_utbetalinger_v1_state_store_left_join_helved_saker_v1
	agent "from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1-left-join-helved.utbetalinger.v1-repartition-sink" <<Sink>> as from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_repartition_sink
	agent "helved.saker.v1-to-table" <<Processor>> as helved_saker_v1_to_table
	agent "produced-helved.saker.v1-consume-helved.utbetalinger.v1-state-store-left-join-helved.saker.v1" <<Sink>> as produced_helved_saker_v1_consume_helved_utbetalinger_v1_state_store_left_join_helved_saker_v1
	from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_repartition --> from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_repartition_source
	consume_helved_utbetalinger_v1_state_store_left_join_helved_saker_v1_repartition --> consume_helved_utbetalinger_v1_state_store_left_join_helved_saker_v1_repartition_source
	helved_saker_v1_state_store -- from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1
	helved_saker_v1 --> consume_helved_saker_v1
	helved_saker_v1_state_store -- consume_helved_utbetalinger_v1_state_store_left_join_helved_saker_v1
	from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_repartition <-- from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_repartition_sink
	helved_saker_v1_state_store -- helved_saker_v1_to_table
	helved_saker_v1 <-- produced_helved_saker_v1_consume_helved_utbetalinger_v1_state_store_left_join_helved_saker_v1
	from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_repartition_source --> from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1
	consume_helved_utbetalinger_v1_state_store_left_join_helved_saker_v1_repartition_source --> consume_helved_utbetalinger_v1_state_store_left_join_helved_saker_v1
	from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1 --> KSTREAM_MAPVALUES_0000000012
	KSTREAM_MAPVALUES_0000000012 --> KSTREAM_KEY_SELECT_0000000013
	consume_helved_saker_v1 --> stateless_operation_log_consume_helved_saker_v1
	consume_helved_utbetalinger_v1_state_store_left_join_helved_saker_v1 --> KSTREAM_MAPVALUES_0000000052
	KSTREAM_KEY_SELECT_0000000013 --> from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_repartition_filter
	KSTREAM_MAPVALUES_0000000052 --> stateless_operation_log_produced_helved_saker_v1_consume_helved_utbetalinger_v1_state_store_left_join_helved_saker_v1
	stateless_operation_log_consume_helved_saker_v1 --> stateless_operation_log_produced_helved_saker_v1
	from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_repartition_filter --> from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_left_join_helved_utbetalinger_v1_repartition_sink
	stateless_operation_log_produced_helved_saker_v1 --> helved_saker_v1_to_table
	stateless_operation_log_produced_helved_saker_v1_consume_helved_utbetalinger_v1_state_store_left_join_helved_saker_v1 --> produced_helved_saker_v1_consume_helved_utbetalinger_v1_state_store_left_join_helved_saker_v1
}
package "Sub-topology: 2" {
	agent "consume-helved.aap-utbetalinger.v1" <<Source>> as consume_helved_aap_utbetalinger_v1
	agent "stateless-operation-log-consume-helved.aap-utbetalinger.v1" <<Processor>> as stateless_operation_log_consume_helved_aap_utbetalinger_v1
	agent "skip-helved.aap-utbetalinger.v1-tombstone" <<Processor>> as skip_helved_aap_utbetalinger_v1_tombstone
	agent "KSTREAM-MAPVALUES-0000000006" <<Processor>> as KSTREAM_MAPVALUES_0000000006
	agent "KSTREAM-KEY-SELECT-0000000007" <<Processor>> as KSTREAM_KEY_SELECT_0000000007
	agent "from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1-repartition-filter" <<Processor>> as from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_repartition_filter
	agent "from-helved.aap-utbetalinger.v1-left-join-helved.saker.v1-repartition-sink" <<Sink>> as from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_repartition_sink
	helved_aap_utbetalinger_v1 --> consume_helved_aap_utbetalinger_v1
	from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_repartition <-- from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_repartition_sink
	consume_helved_aap_utbetalinger_v1 --> stateless_operation_log_consume_helved_aap_utbetalinger_v1
	stateless_operation_log_consume_helved_aap_utbetalinger_v1 --> skip_helved_aap_utbetalinger_v1_tombstone
	skip_helved_aap_utbetalinger_v1_tombstone --> KSTREAM_MAPVALUES_0000000006
	KSTREAM_MAPVALUES_0000000006 --> KSTREAM_KEY_SELECT_0000000007
	KSTREAM_KEY_SELECT_0000000007 --> from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_repartition_filter
	from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_repartition_filter --> from_helved_aap_utbetalinger_v1_left_join_helved_saker_v1_repartition_sink
}
@enduml