@startuml
!theme black-knight
queue "helved.dryrun-aap.v1" <<topic>> as helved_dryrun_aap_v1
queue "helved.dryrun-dp.v1" <<topic>> as helved_dryrun_dp_v1
queue "helved.dryrun-ts.v1" <<topic>> as helved_dryrun_ts_v1
queue "helved.dryrun-tp.v1" <<topic>> as helved_dryrun_tp_v1
queue "helved.status.v1" <<topic>> as helved_status_v1
queue "helved.simuleringer.v1" <<topic>> as helved_simuleringer_v1
queue "helved.oppdrag.v1" <<topic>> as helved_oppdrag_v1
queue "helved.kvittering.v1" <<topic>> as helved_kvittering_v1
queue "fk-uid-store-materialize-repartition" <<topic>> as fk_uid_store_materialize_repartition
queue "helved.avstemming.v1" <<topic>> as helved_avstemming_v1
package "Sub-topology: 0" {
	agent "consume-helved.simuleringer.v1" <<Source>> as consume_helved_simuleringer_v1
	agent "KSTREAM-PROCESSVALUES-0000000001" <<Processor>> as KSTREAM_PROCESSVALUES_0000000001
	agent "KSTREAM-FILTER-0000000002" <<Processor>> as KSTREAM_FILTER_0000000002
	agent "KSTREAM-MAPVALUES-0000000003" <<Processor>> as KSTREAM_MAPVALUES_0000000003
	agent "KSTREAM-BRANCH-0000000004" <<Processor>> as KSTREAM_BRANCH_0000000004
	agent "KSTREAM-BRANCH-00000000041" <<Processor>> as KSTREAM_BRANCH_00000000041
	agent "KSTREAM-MAPVALUES-0000000006" <<Processor>> as KSTREAM_MAPVALUES_0000000006
	agent "KSTREAM-BRANCH-0000000007" <<Processor>> as KSTREAM_BRANCH_0000000007
	agent "KSTREAM-BRANCH-00000000071" <<Processor>> as KSTREAM_BRANCH_00000000071
	agent "KSTREAM-BRANCH-00000000072" <<Processor>> as KSTREAM_BRANCH_00000000072
	agent "KSTREAM-BRANCH-00000000073" <<Processor>> as KSTREAM_BRANCH_00000000073
	agent "KSTREAM-BRANCH-00000000074" <<Processor>> as KSTREAM_BRANCH_00000000074
	agent "KSTREAM-BRANCH-00000000040" <<Processor>> as KSTREAM_BRANCH_00000000040
	agent "KSTREAM-MAPVALUES-0000000009" <<Processor>> as KSTREAM_MAPVALUES_0000000009
	agent "KSTREAM-MAPVALUES-0000000014" <<Processor>> as KSTREAM_MAPVALUES_0000000014
	agent "KSTREAM-MAPVALUES-0000000019" <<Processor>> as KSTREAM_MAPVALUES_0000000019
	agent "KSTREAM-MAPVALUES-0000000024" <<Processor>> as KSTREAM_MAPVALUES_0000000024
	agent "KSTREAM-MAPVALUES-0000000010" <<Processor>> as KSTREAM_MAPVALUES_0000000010
	agent "KSTREAM-MAPVALUES-0000000015" <<Processor>> as KSTREAM_MAPVALUES_0000000015
	agent "KSTREAM-MAPVALUES-0000000020" <<Processor>> as KSTREAM_MAPVALUES_0000000020
	agent "KSTREAM-MAPVALUES-0000000025" <<Processor>> as KSTREAM_MAPVALUES_0000000025
	agent "KSTREAM-MAPVALUES-0000000029" <<Processor>> as KSTREAM_MAPVALUES_0000000029
	agent "KSTREAM-PROCESSVALUES-0000000011" <<Processor>> as KSTREAM_PROCESSVALUES_0000000011
	agent "KSTREAM-PROCESSVALUES-0000000016" <<Processor>> as KSTREAM_PROCESSVALUES_0000000016
	agent "KSTREAM-PROCESSVALUES-0000000021" <<Processor>> as KSTREAM_PROCESSVALUES_0000000021
	agent "KSTREAM-PROCESSVALUES-0000000026" <<Processor>> as KSTREAM_PROCESSVALUES_0000000026
	agent "KSTREAM-PROCESSVALUES-0000000030" <<Processor>> as KSTREAM_PROCESSVALUES_0000000030
	agent "KSTREAM-SINK-0000000012" <<Sink>> as KSTREAM_SINK_0000000012
	agent "KSTREAM-SINK-0000000017" <<Sink>> as KSTREAM_SINK_0000000017
	agent "KSTREAM-SINK-0000000022" <<Sink>> as KSTREAM_SINK_0000000022
	agent "KSTREAM-SINK-0000000027" <<Sink>> as KSTREAM_SINK_0000000027
	agent "KSTREAM-SINK-0000000031" <<Sink>> as KSTREAM_SINK_0000000031
	helved_simuleringer_v1 --> consume_helved_simuleringer_v1
	helved_dryrun_aap_v1 <-- KSTREAM_SINK_0000000012
	helved_dryrun_dp_v1 <-- KSTREAM_SINK_0000000017
	helved_dryrun_ts_v1 <-- KSTREAM_SINK_0000000022
	helved_dryrun_tp_v1 <-- KSTREAM_SINK_0000000027
	helved_status_v1 <-- KSTREAM_SINK_0000000031
	consume_helved_simuleringer_v1 --> KSTREAM_PROCESSVALUES_0000000001
	KSTREAM_PROCESSVALUES_0000000001 --> KSTREAM_FILTER_0000000002
	KSTREAM_FILTER_0000000002 --> KSTREAM_MAPVALUES_0000000003
	KSTREAM_MAPVALUES_0000000003 --> KSTREAM_BRANCH_0000000004
	KSTREAM_BRANCH_0000000004 --> KSTREAM_BRANCH_00000000040
	KSTREAM_BRANCH_0000000004 --> KSTREAM_BRANCH_00000000041
	KSTREAM_BRANCH_00000000041 --> KSTREAM_MAPVALUES_0000000006
	KSTREAM_MAPVALUES_0000000006 --> KSTREAM_BRANCH_0000000007
	KSTREAM_BRANCH_0000000007 --> KSTREAM_BRANCH_00000000071
	KSTREAM_BRANCH_0000000007 --> KSTREAM_BRANCH_00000000072
	KSTREAM_BRANCH_0000000007 --> KSTREAM_BRANCH_00000000073
	KSTREAM_BRANCH_0000000007 --> KSTREAM_BRANCH_00000000074
	KSTREAM_BRANCH_00000000071 --> KSTREAM_MAPVALUES_0000000009
	KSTREAM_BRANCH_00000000072 --> KSTREAM_MAPVALUES_0000000014
	KSTREAM_BRANCH_00000000073 --> KSTREAM_MAPVALUES_0000000019
	KSTREAM_BRANCH_00000000074 --> KSTREAM_MAPVALUES_0000000024
	KSTREAM_BRANCH_00000000040 --> KSTREAM_MAPVALUES_0000000029
	KSTREAM_MAPVALUES_0000000009 --> KSTREAM_MAPVALUES_0000000010
	KSTREAM_MAPVALUES_0000000014 --> KSTREAM_MAPVALUES_0000000015
	KSTREAM_MAPVALUES_0000000019 --> KSTREAM_MAPVALUES_0000000020
	KSTREAM_MAPVALUES_0000000024 --> KSTREAM_MAPVALUES_0000000025
	KSTREAM_MAPVALUES_0000000010 --> KSTREAM_PROCESSVALUES_0000000011
	KSTREAM_MAPVALUES_0000000015 --> KSTREAM_PROCESSVALUES_0000000016
	KSTREAM_MAPVALUES_0000000020 --> KSTREAM_PROCESSVALUES_0000000021
	KSTREAM_MAPVALUES_0000000025 --> KSTREAM_PROCESSVALUES_0000000026
	KSTREAM_MAPVALUES_0000000029 --> KSTREAM_PROCESSVALUES_0000000030
	KSTREAM_PROCESSVALUES_0000000011 --> KSTREAM_SINK_0000000012
	KSTREAM_PROCESSVALUES_0000000016 --> KSTREAM_SINK_0000000017
	KSTREAM_PROCESSVALUES_0000000021 --> KSTREAM_SINK_0000000022
	KSTREAM_PROCESSVALUES_0000000026 --> KSTREAM_SINK_0000000027
	KSTREAM_PROCESSVALUES_0000000030 --> KSTREAM_SINK_0000000031
}
package "Sub-topology: 1" {
	database "fk-uid-store" <<State Store>> as fk_uid_store
	database "helved.kvittering.v1-state-store" <<State Store>> as helved_kvittering_v1_state_store
	agent "consume-helved.kvittering.v1" <<Source>> as consume_helved_kvittering_v1
	agent "KSTREAM-PROCESSVALUES-0000000033" <<Processor>> as KSTREAM_PROCESSVALUES_0000000033
	agent "KSTREAM-PROCESSVALUES-0000000034" <<Processor>> as KSTREAM_PROCESSVALUES_0000000034
	agent "fk-uid-store-materialize-repartition-source" <<Source>> as fk_uid_store_materialize_repartition_source
	agent "fk-uid-store-materialize" <<Processor>> as fk_uid_store_materialize
	agent "ktable-helved.kvittering.v1" <<Processor>> as ktable_helved_kvittering_v1
	agent "KTABLE-JOINOTHER-0000000047" <<Processor>> as KTABLE_JOINOTHER_0000000047
	agent "KTABLE-JOINTHIS-0000000046" <<Processor>> as KTABLE_JOINTHIS_0000000046
	agent "KTABLE-MERGE-0000000045" <<Processor>> as KTABLE_MERGE_0000000045
	agent "KTABLE-TOSTREAM-0000000048" <<Processor>> as KTABLE_TOSTREAM_0000000048
	agent "KSTREAM-FILTER-0000000049" <<Processor>> as KSTREAM_FILTER_0000000049
	agent "KSTREAM-MAP-0000000050" <<Processor>> as KSTREAM_MAP_0000000050
	agent "KSTREAM-PROCESSVALUES-0000000051" <<Processor>> as KSTREAM_PROCESSVALUES_0000000051
	agent "KSTREAM-SINK-0000000052" <<Sink>> as KSTREAM_SINK_0000000052
	helved_kvittering_v1 --> consume_helved_kvittering_v1
	fk_uid_store_materialize_repartition --> fk_uid_store_materialize_repartition_source
	fk_uid_store -- fk_uid_store_materialize
	helved_kvittering_v1_state_store -- ktable_helved_kvittering_v1
	fk_uid_store -- KTABLE_JOINOTHER_0000000047
	helved_kvittering_v1_state_store -- KTABLE_JOINTHIS_0000000046
	helved_oppdrag_v1 <-- KSTREAM_SINK_0000000052
	consume_helved_kvittering_v1 --> KSTREAM_PROCESSVALUES_0000000033
	KSTREAM_PROCESSVALUES_0000000033 --> KSTREAM_PROCESSVALUES_0000000034
	KSTREAM_PROCESSVALUES_0000000034 --> ktable_helved_kvittering_v1
	fk_uid_store_materialize_repartition_source --> fk_uid_store_materialize
	fk_uid_store_materialize --> KTABLE_JOINTHIS_0000000046
	ktable_helved_kvittering_v1 --> KTABLE_JOINOTHER_0000000047
	KTABLE_JOINOTHER_0000000047 --> KTABLE_MERGE_0000000045
	KTABLE_JOINTHIS_0000000046 --> KTABLE_MERGE_0000000045
	KTABLE_MERGE_0000000045 --> KTABLE_TOSTREAM_0000000048
	KTABLE_TOSTREAM_0000000048 --> KSTREAM_FILTER_0000000049
	KSTREAM_FILTER_0000000049 --> KSTREAM_MAP_0000000050
	KSTREAM_MAP_0000000050 --> KSTREAM_PROCESSVALUES_0000000051
	KSTREAM_PROCESSVALUES_0000000051 --> KSTREAM_SINK_0000000052
}
package "Sub-topology: 2" {
	agent "consume-helved.oppdrag.v1" <<Source>> as consume_helved_oppdrag_v1
	agent "KSTREAM-PROCESSVALUES-0000000037" <<Processor>> as KSTREAM_PROCESSVALUES_0000000037
	agent "KSTREAM-FILTER-0000000038" <<Processor>> as KSTREAM_FILTER_0000000038
	agent "KSTREAM-BRANCH-0000000053" <<Processor>> as KSTREAM_BRANCH_0000000053
	agent "KSTREAM-BRANCH-00000000531" <<Processor>> as KSTREAM_BRANCH_00000000531
	agent "KSTREAM-BRANCH-00000000532" <<Processor>> as KSTREAM_BRANCH_00000000532
	agent "KSTREAM-FILTER-0000000039" <<Processor>> as KSTREAM_FILTER_0000000039
	agent "KSTREAM-FILTER-0000000055" <<Processor>> as KSTREAM_FILTER_0000000055
	agent "KSTREAM-FILTER-0000000061" <<Processor>> as KSTREAM_FILTER_0000000061
	agent "KSTREAM-MAP-0000000040" <<Processor>> as KSTREAM_MAP_0000000040
	agent "KSTREAM-MAPVALUES-0000000056" <<Processor>> as KSTREAM_MAPVALUES_0000000056
	agent "KSTREAM-MAPVALUES-0000000057" <<Processor>> as KSTREAM_MAPVALUES_0000000057
	agent "KSTREAM-MAPVALUES-0000000062" <<Processor>> as KSTREAM_MAPVALUES_0000000062
	agent "fk-uid-store-materialize-log" <<Processor>> as fk_uid_store_materialize_log
	agent "KSTREAM-PROCESSVALUES-0000000058" <<Processor>> as KSTREAM_PROCESSVALUES_0000000058
	agent "KSTREAM-PROCESSVALUES-0000000063" <<Processor>> as KSTREAM_PROCESSVALUES_0000000063
	agent "fk-uid-store-materialize-repartition-filter" <<Processor>> as fk_uid_store_materialize_repartition_filter
	agent "KSTREAM-SINK-0000000059" <<Sink>> as KSTREAM_SINK_0000000059
	agent "KSTREAM-SINK-0000000064" <<Sink>> as KSTREAM_SINK_0000000064
	agent "fk-uid-store-materialize-repartition-sink" <<Sink>> as fk_uid_store_materialize_repartition_sink
	helved_oppdrag_v1 --> consume_helved_oppdrag_v1
	helved_status_v1 <-- KSTREAM_SINK_0000000059
	helved_status_v1 <-- KSTREAM_SINK_0000000064
	fk_uid_store_materialize_repartition <-- fk_uid_store_materialize_repartition_sink
	consume_helved_oppdrag_v1 --> KSTREAM_PROCESSVALUES_0000000037
	KSTREAM_PROCESSVALUES_0000000037 --> KSTREAM_FILTER_0000000038
	KSTREAM_FILTER_0000000038 --> KSTREAM_BRANCH_0000000053
	KSTREAM_FILTER_0000000038 --> KSTREAM_FILTER_0000000039
	KSTREAM_BRANCH_0000000053 --> KSTREAM_BRANCH_00000000531
	KSTREAM_BRANCH_0000000053 --> KSTREAM_BRANCH_00000000532
	KSTREAM_BRANCH_00000000531 --> KSTREAM_FILTER_0000000055
	KSTREAM_BRANCH_00000000532 --> KSTREAM_FILTER_0000000061
	KSTREAM_FILTER_0000000039 --> KSTREAM_MAP_0000000040
	KSTREAM_FILTER_0000000055 --> KSTREAM_MAPVALUES_0000000056
	KSTREAM_FILTER_0000000061 --> KSTREAM_MAPVALUES_0000000062
	KSTREAM_MAP_0000000040 --> fk_uid_store_materialize_log
	KSTREAM_MAPVALUES_0000000056 --> KSTREAM_MAPVALUES_0000000057
	KSTREAM_MAPVALUES_0000000057 --> KSTREAM_PROCESSVALUES_0000000058
	KSTREAM_MAPVALUES_0000000062 --> KSTREAM_PROCESSVALUES_0000000063
	fk_uid_store_materialize_log --> fk_uid_store_materialize_repartition_filter
	KSTREAM_PROCESSVALUES_0000000058 --> KSTREAM_SINK_0000000059
	KSTREAM_PROCESSVALUES_0000000063 --> KSTREAM_SINK_0000000064
	fk_uid_store_materialize_repartition_filter --> fk_uid_store_materialize_repartition_sink
}
package "Sub-topology: 3" {
	agent "consume-helved.avstemming.v1" <<Source>> as consume_helved_avstemming_v1
	agent "KSTREAM-PROCESSVALUES-0000000066" <<Processor>> as KSTREAM_PROCESSVALUES_0000000066
	agent "KSTREAM-FILTER-0000000067" <<Processor>> as KSTREAM_FILTER_0000000067
	agent "KSTREAM-FOREACH-0000000068" <<Processor>> as KSTREAM_FOREACH_0000000068
	helved_avstemming_v1 --> consume_helved_avstemming_v1
	consume_helved_avstemming_v1 --> KSTREAM_PROCESSVALUES_0000000066
	KSTREAM_PROCESSVALUES_0000000066 --> KSTREAM_FILTER_0000000067
	KSTREAM_FILTER_0000000067 --> KSTREAM_FOREACH_0000000068
}
@enduml