
%%{init: {'theme': 'dark', 'themeVariables': { 'primaryColor': '#07cff6', 'textColor': '#dad9e0', 'lineColor': '#07cff6'}}}%%

graph LR

subgraph Topologi
    %% TOPICS
    helved.simuleringer.v1([helved.simuleringer.v1])
	helved.dryrun-aap.v1([helved.dryrun-aap.v1])
	helved.status.v1([helved.status.v1])
	helved.dryrun-dp.v1([helved.dryrun-dp.v1])
	helved.dryrun-ts.v1([helved.dryrun-ts.v1])
	helved.dryrun-tp.v1([helved.dryrun-tp.v1])
	helved.kvittering.v1([helved.kvittering.v1])
	ktable-helved.kvittering.v1-repartition([ktable-helved.kvittering.v1-repartition])
	fk-uid-store-materialize-repartition([fk-uid-store-materialize-repartition])
	helved.oppdrag.v1([helved.oppdrag.v1])
	helved.avstemming.v1([helved.avstemming.v1])

    %% JOINS
    

    %% STATE PROCESSORS
    
    
    %% STATE STORES
    fk-uid-store[(fk-uid-store)]
	helved.kvittering.v1-state-store[(helved.kvittering.v1-state-store)]
	dedup-kvittering[(dedup-kvittering)]
	dedup-oppdrag[(dedup-oppdrag)]
    
    %% DATABASES
    
    

    %% PROCESSOR API JOBS
    
    
    %% JOIN STREAMS
    

    %% TABLE STREAMS
    

    %% JOB STREAMS
    
    
    %% BRANCH STREAMS
    

    %% REPARTITION STREAMS
    helved.oppdrag.v1 --> |rekey| fk-uid-store-materialize-repartition
    
    %% BASIC STREAMS
    helved.simuleringer.v1 --> helved.status.v1
	helved.simuleringer.v1 --> helved.dryrun-dp.v1
	helved.simuleringer.v1 --> helved.dryrun-ts.v1
	helved.simuleringer.v1 --> helved.status.v1
	helved.simuleringer.v1 --> helved.status.v1
	helved.simuleringer.v1 --> helved.dryrun-aap.v1
	helved.simuleringer.v1 --> helved.status.v1
	helved.simuleringer.v1 --> helved.dryrun-tp.v1
	helved.simuleringer.v1 --> helved.status.v1
	helved.kvittering.v1 --> ktable-helved.kvittering.v1-repartition
    
    %% CUSTOM PROCESS STREAMS
    
end

%% COLORS
%% light    #dad9e0
%% purple   #78369f
%% pink     #c233b4
%% dark     #2a204a
%% blue     #07cff6

%% STYLES
style helved.simuleringer.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style helved.dryrun-aap.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style helved.status.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style helved.dryrun-dp.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style helved.dryrun-ts.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style helved.dryrun-tp.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style helved.kvittering.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style ktable-helved.kvittering.v1-repartition fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style fk-uid-store-materialize-repartition fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style helved.oppdrag.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style helved.avstemming.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style fk-uid-store fill:#78369f, stroke:#2a204a, stroke-width:2px, color:#2a204a
style helved.kvittering.v1-state-store fill:#78369f, stroke:#2a204a, stroke-width:2px, color:#2a204a
style dedup-kvittering fill:#78369f, stroke:#2a204a, stroke-width:2px, color:#2a204a
style dedup-oppdrag fill:#78369f, stroke:#2a204a, stroke-width:2px, color:#2a204a

