@startuml
!theme black-knight
queue "helved.status.v1" <<topic>> as helved_status_v1
package "Sub-topology: 0" {
	agent "consume-helved.status.v1" <<Source>> as consume_helved_status_v1
	agent "KSTREAM-PROCESSOR-0000000001" <<Processor>> as KSTREAM_PROCESSOR_0000000001
	agent "KSTREAM-FILTER-0000000002" <<Processor>> as KSTREAM_FILTER_0000000002
	agent "KSTREAM-FILTER-0000000003" <<Processor>> as KSTREAM_FILTER_0000000003
	agent "KSTREAM-FOREACH-0000000004" <<Processor>> as KSTREAM_FOREACH_0000000004
	helved_status_v1 --> consume_helved_status_v1
	consume_helved_status_v1 --> KSTREAM_PROCESSOR_0000000001
	KSTREAM_PROCESSOR_0000000001 --> KSTREAM_FILTER_0000000002
	KSTREAM_FILTER_0000000002 --> KSTREAM_FILTER_0000000003
	KSTREAM_FILTER_0000000003 --> KSTREAM_FOREACH_0000000004
}
@enduml