apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: helved
  name: vedskiva
  namespace: helved
spec:
#  schedule: "0 5 * * *"
  image: {{ image }} 
  ttlSecondsAfterFinished: 14400
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-f1-micro
        databases:
          - name: vedskiva
            envVarPrefix: DB
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  kafka:
    pool: nav-dev
    streams: true
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
        - application: peisschtappern
  env:
    - name: PEISSCHTAPPERN_SCOPE
      value: api://dev-gcp.helved.peisschtappern/.default
