apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: vedskiva
  namespace: helved
  labels:
    team: helved
spec:
  terminationGracePeriodSeconds: 70
  image: {{ image }} 
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 512Mi
      cpu: 200m
  liveness:
    path: /actuator/health
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /actuator/health
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    path: /actuator/metric
    enabled: true
  replicas:
    min: 1
    max: 1
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-custom-1-3840
        cascadingDelete: false
        highAvailability: true 
        pointInTimeRecovery: true
        databases:
          - name: vedskiva
            envVarPrefix: DB
        flags:
          - name: "cloudsql.enable_pgaudit"
            value: "on"
          - name: "pgaudit.log"
            value: "write,ddl"
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
  kafka:
    pool: nav-prod
    streams: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: smokesignal
        - application: helved-peisen
    outbound:
      rules:
        - application: logging
          namespace: nais-system
        - application: peisschtappern
  env:
    - name: PEISSCHTAPPERN_SCOPE
      value: api://prod-gcp.helved.peisschtappern/.default

