apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: statistikkern
  namespace: helved
  labels:
    team: helved
spec:
  image: {{ image }}
  terminationGracePeriodSeconds: 70
  liveness:
    path: /actuator/live
    initialDelay: 5
    periodSeconds: 2
  readiness:
    path: /actuator/ready
    initialDelay: 5
    periodSeconds: 2
  prometheus:
    path: /actuator/metric
    enabled: true
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 512Mi
      cpu: 200m
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
  kafka:
    pool: nav-prod
    streams: true
  gcp:
    bigQueryDatasets:
      - cascadingDelete: true
        name: helved_stats
        permission: READWRITE
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system