name: brannt책rn

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'apps/brannt책rn/**'
      - '.github/workflows/brannt책rn.yml'
      - 'build.gradle.kts'
      - 'apps/brannt책rn/Dockerfile'

jobs:
  build:
    if: github.event.pull_request.merged || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write  # submit dependency-graph
      id-token: write  # publish docker image
      actions: read    #
      checks: write    # write test results
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5.0.0
        with:
          java-version: 21
          distribution: temurin

      - uses: gradle/actions/setup-gradle@v4
        with:
          dependency-graph: generate-and-submit

      - run: ./gradlew apps:${{ github.workflow }}:test apps:${{ github.workflow }}:buildFatJar --continue --no-daemon

      - uses: nais/docker-build-push@v0
        with:
          team: helved
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          image_suffix: ${{ github.workflow }}
          tag: ${{ github.sha }}
          dockerfile: Dockerfile

  deploy-dev:
    if: github.event.pull_request.merged || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build
    permissions:
      contents: read    # read repository files
      id-token: write   # publish nais manifest
    steps:
      - uses: actions/checkout@v5
      - uses: nais/login@v0
        id: login
        with:
          team: helved
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
      - uses: nais/deploy/actions/deploy@v2
        env:
          PRINT_PAYLOAD: true
          CLUSTER: dev-gcp
          RESOURCE: apps/${{ github.workflow }}/dev.yml,apps/${{ github.workflow }}/alert.yml
          VAR: image=${{ steps.login.outputs.registry }}/${{ github.event.repository.name }}-${{ github.workflow }}:${{ github.sha }}

  deploy-prod:
    if: github.event.pull_request.merged || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build
    permissions:
      contents: read    # read repository files
      id-token: write   # publish nais manifest
    steps:
      - uses: actions/checkout@v5
      - uses: nais/login@v0
        id: login
        with:
          team: helved
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
      - uses: nais/deploy/actions/deploy@v2
        env:
          PRINT_PAYLOAD: true
          CLUSTER: prod-gcp
          RESOURCE: apps/${{ github.workflow }}/prod.yml,apps/${{ github.workflow }}/alert.yml
          VAR: image=${{ steps.login.outputs.registry }}/${{ github.event.repository.name }}-${{ github.workflow }}:${{ github.sha }}