name: topics

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'topics/**'
      - '.github/workflows/topics.yml'

jobs:
  deploy:
    strategy:
      matrix:
        name:
          - helved.aap-utbetalinger.v1
          - helved.kvittering.v1
          - helved.kvittering-queue.v1
          - helved.oppdrag.v1
          - helved.saker.v1
          - helved.simulering.v1
          - helved.aap-simulering.v1
          - helved.status.v1
          - helved.utbetalinger.v1
        env:
          - dev
          - prod
    name: deploy ${{ matrix.name }} to ${{ matrix.env }}
    runs-on: ubuntu-latest
    permissions:
      contents: read    # read repository files
      id-token: write   # publish nais manifest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/login@v0
        id: login
        with:
          team: helved
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
      - uses: nais/deploy/actions/deploy@v2
        env:
          PRINT_PAYLOAD: true
          CLUSTER: ${{ matrix.env }}-gcp
          RESOURCE: topics/${{ matrix.name }}
          VAR: kafkapool=nav-${{ matrix.env }}
